Roguelike: EnemiesModule Namespace Reference
EnemiesModule Namespace Reference
Functions
void createAtPosition (Enemies &enemies, Tiles const &tiles, RenderId enemyId, Vector2I tilePosition)
void createAtRandomPosition (Enemies &enemies, Tiles const &tiles, RenderId enemyId)
void fillEnemies (Enemies &enemies, Tiles const &tiles, int mapLevel)
void remove (Enemies &enemies, size_t id)
bool regenerate (snx::DenseMap< size_t, EnergyComponent > &energies)
void update (Enemies &enemies, Vector2 const &heroPosition)
size_t getActive (snx::DenseMap< size_t, EnergyComponent > const &energies, snx::DenseMap< size_t, AIComponent > const &ais, int const turn)
void replaceDead (Enemies &enemies, Tiles const &tiles)
Function Documentation
createAtPosition()
void EnemiesModule::createAtPosition (Enemies & enemies, Tiles const & tiles, RenderId enemyId, Vector2I tilePosition)
Definition at line 100 of file Enemies.cpp.
{
    if ( !isSpawnPositionValid(
             tiles,
             enemies.ids,
             tilePosition
         ) )
    {
        return;
    }
    size_t enemyId{ enemies.idManager.requestId() };
    switch ( renderId )
    {
        default:
        case RenderId::GOBLIN:
        {
            insertSingle(
                enemies,
                TransformComponent{},
                MovementComponent{},
                EnergyComponent{
                    EnemyData::goblinEnergyMax,
                    EnemyData::goblinEnergyRegenBase
                },
                HealthComponent{ EnemyData::goblinHealthBase },
                DamageComponent{ EnemyData::goblinDamageBase },
                tilePosition,
                enemyId,
                RenderId::GOBLIN,
                EnemyData::goblinScanRange
            );
            break;
        }
    }
}
References GOBLIN, EnemyData::goblinDamageBase, EnemyData::goblinEnergyMax, EnemyData::goblinEnergyRegenBase, EnemyData::goblinHealthBase, EnemyData::goblinScanRange, Enemies::idManager, Enemies::ids, insertSingle(), isSpawnPositionValid(), and snx::IdManager::requestId().
Referenced by createAtRandomPosition().
createAtRandomPosition()
void EnemiesModule::createAtRandomPosition (Enemies & enemies, Tiles const & tiles, RenderId enemyId)
Definition at line 143 of file Enemies.cpp.
{
    Vector2I tilePosition = getRandomPosition(
        tiles,
        enemies.ids
    );
    createAtPosition(
        enemies,
        tiles,
        renderId,
        tilePosition
    );
}
References createAtPosition(), getRandomPosition(), and Enemies::ids.
Referenced by fillEnemies(), and replaceDead().
fillEnemies()
void EnemiesModule::fillEnemies (Enemies & enemies, Tiles const & tiles, int mapLevel)
Definition at line 178 of file Enemies.cpp.
{
    while ( enemies.renderIds.size() < static_cast<size_t>( ( mapLevel + 1 ) * 3 ) )
    {
        EnemiesModule::createAtRandomPosition(
            enemies,
            tiles,
            RenderId::GOBLIN
        );
    }
}
References createAtRandomPosition(), GOBLIN, Enemies::renderIds, and snx::DenseMap< Key, Type >::size().
Referenced by createGridRooms().
getActive()
size_t EnemiesModule::getActive (snx::DenseMap< size_t, EnergyComponent > const & energies, snx::DenseMap< size_t, AIComponent > const & ais, int const turn)
Definition at line 243 of file Enemies.cpp.
{
    size_t activeEnemyId{ 0 };
    for ( size_t idx{ 0 }; idx < energies.size(); ++idx )
    {
        if ( energies.values().at( idx ).state == EnergyState::READY
             && ais.values().at( idx ).turn < turn )
        {
            activeEnemyId = energies.key( idx );
            break;
        }
    }
    return activeEnemyId;
}
References snx::DenseMap< Key, Type >::key(), READY, snx::DenseMap< Key, Type >::size(), and snx::DenseMap< Key, Type >::values().
Referenced by AISystem::takeActions().
regenerate()
bool EnemiesModule::regenerate (snx::DenseMap< size_t, EnergyComponent > & energies)
Definition at line 194 of file Enemies.cpp.
{
    bool isEnemyReady{ false };
    for ( EnergyComponent& energy : energies )
    {
        if ( !EnergyModule::regenerate( energy ) )
        {
            isEnemyReady = true;
        }
    }
    return isEnemyReady;
}
References EnergyModule::regenerate().
Referenced by GameModule::updateState().
remove()
void EnemiesModule::remove (Enemies & enemies, size_t id)
Definition at line 162 of file Enemies.cpp.
{
    enemies.ids.erase( Convert::worldToTile( enemies.positions.at( id ) ) );
    enemies.positions.erase( id );
    enemies.renderIds.erase( id );
    enemies.transforms.erase( id );
    enemies.movements.erase( id );
    enemies.energies.erase( id );
    enemies.healths.erase( id );
    enemies.damages.erase( id );
    enemies.ais.erase( id );
}
References Enemies::ais, snx::DenseMap< Key, Type >::at(), Enemies::damages, Enemies::energies, snx::DenseMap< Key, Type >::erase(), Enemies::healths, Enemies::ids, Enemies::movements, Enemies::positions, Enemies::renderIds, Enemies::transforms, and Convert::worldToTile().
Referenced by replaceDead().
replaceDead()
void EnemiesModule::replaceDead (Enemies & enemies, Tiles const & tiles)
Definition at line 264 of file Enemies.cpp.
{
    size_t idx{ 0 };
    while ( idx < enemies.ids.values().size() )
    {
        //* Kill enemy at 0 health
        if ( enemies.healths.values().at( idx ).currentHealth <= 0 )
        {
            EnemiesModule::remove(
                enemies,
                enemies.ids.values().at( idx )
            );
            //* Spawn new enemy
            EnemiesModule::createAtRandomPosition(
                enemies,
                tiles,
                RenderId::GOBLIN
            );
            continue;
        }
        ++idx;
    }
}
References createAtRandomPosition(), GOBLIN, Enemies::healths, Enemies::ids, remove(), and snx::DenseMap< Key, Type >::values().
Referenced by GameModule::updateState().
update()
void EnemiesModule::update (Enemies & enemies, Vector2 const & heroPosition)
Definition at line 209 of file Enemies.cpp.
{
    Vector2* currentPosition{};
    Vector2I oldPosition{};
    for ( size_t idx{ 0 }; idx < enemies.transforms.size(); ++idx )
    {
        currentPosition = &enemies.positions.values().at( idx );
        oldPosition = Convert::worldToTile( *currentPosition );
        //* Update movement
        //* Update ids_ key if tilePosition changes
        MovementSystem::updateHero(
            enemies.transforms.values().at( idx ),
            // enemies.movements.values().at(i),
            *currentPosition,
            enemies.energies.values().at( idx ),
            heroPosition
        );
        if ( oldPosition != Convert::worldToTile( *currentPosition ) )
        {
            enemies.ids.changeKey(
                oldPosition,
                Convert::worldToTile( *currentPosition )
            );
        }
    }
}
References snx::DenseMap< Key, Type >::changeKey(), Enemies::energies, Enemies::ids, Enemies::positions, snx::DenseMap< Key, Type >::size(), Enemies::transforms, MovementSystem::updateHero(), snx::DenseMap< Key, Type >::values(), and Convert::worldToTile().