Roguelike: DamageSystem Namespace Reference
DamageSystem Namespace Reference
Functions
void attack (DamageComponent const &attackerDamage, HealthComponent &defenderHealth)
Function Documentation
attack()
void DamageSystem::attack (DamageComponent const & attackerDamage, HealthComponent & defenderHealth)
Definition at line 5 of file DamageSystem.cpp.
{
    HealthModule::damage(
        defenderHealth,
        DamageModule::damageRNG( attackerDamage )
    );
}
References HealthModule::damage(), and DamageModule::damageRNG().
Referenced by performAttack(), and AISystem::takeAction().