Roguelike: GameModule Namespace Reference
GameModule Namespace Reference
Functions
void init (Game &game)
void processInput (InputMappings const &inInputMappings, bool inIsCursorActive, InputHandler &outInputHandler, InputActionId &outInputActionId)
void updateState (Game &game, GameCamera const &gameCamera, Cursor const &cursor)
void setupGameEvents (Game &game)
Function Documentation
init()
void GameModule::init (Game & game)
Definition at line 31 of file Game.cpp.
{
#if defined(DEBUG)
    snx::RNG::seed( 1 );
#endif
    //* Setup events
    GameModule::setupGameEvents( game );
#if defined(DEBUG)
    snx::PublisherStatic::publish( EventId::NEXT_LEVEL );
#endif
}
References NEXT_LEVEL, snx::PublisherStatic::publish(), snx::RNG::seed(), and setupGameEvents().
Referenced by SceneModule::init().
processInput()
void GameModule::processInput (InputMappings const & inInputMappings, bool inIsCursorActive, InputHandler & outInputHandler, InputActionId & outInputActionId)
Definition at line 45 of file Game.cpp.
{
    //* Take input from mouse, keys or gestures
    inputActionId = InputModule::checkKeyboard(
        inputHandler,
        inputMappings
    );
    if ( inputActionId != InputActionId::NONE )
    {
        return;
    }
    inputActionId = InputModule::checkMouse( inputMappings, isCursorActive );
    if ( inputActionId != InputActionId::NONE )
    {
        return;
    }
    inputActionId = InputModule::checkGesture( inputHandler );
}
References InputModule::checkGesture(), InputModule::checkKeyboard(), InputModule::checkMouse(), and NONE.
Referenced by SceneModule::processInput().
setupGameEvents()
void GameModule::setupGameEvents (Game & game)
Definition at line 154 of file Game.cpp.
{
    snx::PublisherStatic::addSubscriber(
        EventId::MULTIFRAME_ACTION_ACTIVE,
        [&]()
        {
            game.isMultiFrameActionActive = true;
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::MULTIFRAME_ACTION_DONE,
        [&]()
        {
            game.isMultiFrameActionActive = false;
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::NEXT_LEVEL,
        [&]()
        {
            snx::Logger::log( "Entered next level" );
            WorldModule::increaseMapLevel( game.world );
            //* Place Hero on the map entry position
            game.hero.position = Convert::tileToWorld( Vector2I{ 0, 0 } );
            snx::PublisherStatic::publish( EventId::HERO_MOVED );
            snx::PublisherStatic::publish( EventId::HERO_POSITION_CHANGED );
            snx::PublisherStatic::publish( EventId::MAP_CHANGE );
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::PREVIOUS_LEVEL,
        [&]()
        {
            snx::Logger::log( "Entered previous level" );
            WorldModule::decreaseMapLevel( game.world );
            //* Place Hero on the map exit
            auto const& objects{ game.world.currentMap->objects };
            auto const& renderIds{ objects.renderIds.values() };
            auto const& positions{ objects.positions.values() };
            for ( size_t idx{ 0 }; idx < renderIds.size(); ++idx )
            {
                if ( renderIds.at( idx ) == RenderId::DESCEND )
                {
                    game.hero.position = positions.at( idx );
                }
            }
            snx::PublisherStatic::publish( EventId::HERO_MOVED );
            snx::PublisherStatic::publish( EventId::HERO_POSITION_CHANGED );
            snx::PublisherStatic::publish( EventId::MAP_CHANGE );
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::INTERRUPT_MOVEMENT,
        [&]()
        {
            MovementSystem::resetTransform( game.hero.transform );
            game.hero.movement.path.clear();
        }
    );
}
References snx::PublisherStatic::addSubscriber(), World::currentMap, WorldModule::decreaseMapLevel(), DESCEND, Game::hero, HERO_MOVED, HERO_POSITION_CHANGED, WorldModule::increaseMapLevel(), INTERRUPT_MOVEMENT, Game::isMultiFrameActionActive, snx::Logger::log(), MAP_CHANGE, Hero::movement, MULTIFRAME_ACTION_ACTIVE, MULTIFRAME_ACTION_DONE, NEXT_LEVEL, Map::objects, MovementComponent::path, Hero::position, PREVIOUS_LEVEL, snx::PublisherStatic::publish(), MovementSystem::resetTransform(), Convert::tileToWorld(), Hero::transform, and Game::world.
Referenced by init().
updateState()
void GameModule::updateState (Game & game, GameCamera const & gameCamera, Cursor const & cursor)
Definition at line 73 of file Game.cpp.
{
    //* AI
    if ( !game.isMultiFrameActionActive )
    {
        game.isMultiFrameActionActive = AISystem::takeActions(
            game.world,
            game.hero,
            game.activeEnemyId,
            gameCamera,
            game.turn
        );
    }
    //* Hero
    if ( !game.isMultiFrameActionActive
         && game.hero.energy.state == EnergyState::READY )
    {
        game.isMultiFrameActionActive = UserInputSystem::takeAction(
            game.inputAction,
            game.hero,
            cursor,
            *game.world.currentMap,
            gameCamera
        );
    }
    //* Update instant actions
    if ( !game.isMultiFrameActionActive )
    {
        EnemiesModule::replaceDead(
            game.world.currentMap->enemies,
            game.world.currentMap->tiles
        );
    }
    //* Update multi-frame actions
    else
    {
        //* Update hero
        MovementSystem::updateHero(
            game.hero.transform,
            // game.hero.movement,
            game.hero.position,
            game.hero.energy,
            game.hero.position
        );
        //* Update enemies
        MovementSystem::updateEnemies(
            game.world.currentMap->enemies,
            game.hero.position
        );
    }
    //* Regenerate energy if no action in progress
    if ( !game.isMultiFrameActionActive
         && game.hero.energy.state == EnergyState::NOT_READY
         && !game.activeEnemyId )
    {
        bool isUnitReady{ false };
        //* Regenerate until one unit becomes ready
        while ( !isUnitReady )
        {
            isUnitReady = EnergyModule::regenerate( game.hero.energy );
            isUnitReady |= EnemiesModule::regenerate( game.world.currentMap->enemies.energies );
        }
        //* Progess turn when hero is ready
        if ( game.hero.energy.state == EnergyState::READY )
        {
            ++game.turn;
            snx::Logger::setStamp( std::to_string( game.turn ) );
        }
    }
}
References Game::activeEnemyId, World::currentMap, Map::enemies, Enemies::energies, Hero::energy, Game::hero, Game::inputAction, Game::isMultiFrameActionActive, NOT_READY, Hero::position, READY, EnemiesModule::regenerate(), EnergyModule::regenerate(), EnemiesModule::replaceDead(), snx::Logger::setStamp(), EnergyComponent::state, UserInputSystem::takeAction(), AISystem::takeActions(), Map::tiles, Hero::transform, Game::turn, MovementSystem::updateEnemies(), MovementSystem::updateHero(), and Game::world.
Referenced by SceneModule::updateState().