Roguelike: snx::PublisherStatic Class Reference
snx::PublisherStatic Class Reference
#include <PublisherStatic.h>
Static Public Member Functions
static void addSubscriber (EventId event, LambdaVoid subscriber, bool fireOnCreation=false)
static void publish (EventId event)
static void publishAll ()
Static Private Member Functions
static void ensureList (EventId event)
static void notifyAllSubscribers (std::forward_list< LambdaVoid > &subscriberList)
Static Private Attributes
static std::unordered_map< EventId, SubscriberList > eventToSubscriberLists_ { {} }
Detailed Description
Definition at line 18 of file PublisherStatic.h.
Member Function Documentation
addSubscriber()
static void snx::PublisherStatic::addSubscriber (EventId event, LambdaVoid subscriber, bool fireOnCreation = false) inline static
Definition at line 25 of file PublisherStatic.h.
        {
            ensureList( event );
            eventToSubscriberLists_[event].push_front( subscriber );
            if ( fireOnCreation )
            {
                publish( event );
            }
        }
References ensureList(), eventToSubscriberLists_, and publish().
Referenced by GameModule::setupGameEvents(), and SceneModule::setupSceneEvents().
ensureList()
static void snx::PublisherStatic::ensureList (EventId event) inline static private
Definition at line 62 of file PublisherStatic.h.
        {
            if ( eventToSubscriberLists_.find( event ) == eventToSubscriberLists_.end() )
            {
                eventToSubscriberLists_[event] = SubscriberList();
            }
        }
References eventToSubscriberLists_.
Referenced by addSubscriber().
notifyAllSubscribers()
static void snx::PublisherStatic::notifyAllSubscribers (std::forward_list< LambdaVoid > & subscriberList) inline static private
Definition at line 71 of file PublisherStatic.h.
        {
            for ( LambdaVoid& subscriber : subscriberList )
            {
                subscriber();
            }
        }
Referenced by publishAll().
publish()
static void snx::PublisherStatic::publish (EventId event) inline static
Definition at line 42 of file PublisherStatic.h.
        {
            for ( LambdaVoid& subscriber : eventToSubscriberLists_[event] )
            {
                subscriber();
            }
        }
References eventToSubscriberLists_.
Referenced by addSubscriber(), InputModule::checkGesture(), HealthModule::damage(), GameCameraModule::init(), GameModule::init(), PanelSystem::init(), SceneModule::processInput(), GameCameraModule::setOffset(), GameCameraModule::setTarget(), GameModule::setupGameEvents(), SceneModule::setupSceneEvents(), GameCameraModule::setZoom(), UserInputSystem::takeAction(), CursorModule::update(), MovementSystem::updateHero(), and updateWindowState().
publishAll()
static void snx::PublisherStatic::publishAll () inline static
Definition at line 51 of file PublisherStatic.h.
        {
            //* Iterate all subscribers
            for ( auto& [event, list] : eventToSubscriberLists_ )
            {
                notifyAllSubscribers( list );
            }
        }
References eventToSubscriberLists_, and notifyAllSubscribers().
Member Data Documentation
eventToSubscriberLists_
std::unordered_map<EventId, SubscriberList> snx::PublisherStatic::eventToSubscriberLists_ { {} } inline static private
Definition at line 20 of file PublisherStatic.h.
{ {} };
Referenced by addSubscriber(), ensureList(), publish(), and publishAll().
The documentation for this class was generated from the following file:
include/Observer/PublisherStatic.h