Roguelike: ThreadPool Class Reference
ThreadPool Class Reference
#include <ThreadPool.h>
Public Member Functions
ThreadPool ()
~ThreadPool ()
void queueJob (std::function< void()> const &job)
void stop ()
bool isJobQueued ()
void joinJobs ()
Private Member Functions
void start ()
void threadLoop ()
Private Attributes
bool should_terminate = false
std::mutex queue_mutex
std::condition_variable mutex_condition
std::vector< std::thread > threads
std::queue< std::function< void()> > jobs
std::mutex active_job_mutex
int active_jobs { 0 }
Detailed Description
Definition at line 16 of file ThreadPool.h.
Constructor & Destructor Documentation
ThreadPool()
ThreadPool::ThreadPool () inline
Definition at line 61 of file ThreadPool.h.
{
    start();
}
References start().
~ThreadPool()
ThreadPool::~ThreadPool () inline
Definition at line 169 of file ThreadPool.h.
{
    stop();
}
References stop().
Member Function Documentation
isJobQueued()
bool ThreadPool::isJobQueued () inline
Definition at line 130 of file ThreadPool.h.
{
    bool isPoolBusy;
    {
        std::unique_lock<std::mutex> lock( queue_mutex );
        isPoolBusy = !jobs.empty();
    }
    return isPoolBusy;
}
References jobs, and queue_mutex.
Referenced by stop().
joinJobs()
void ThreadPool::joinJobs () inline
Definition at line 142 of file ThreadPool.h.
{
    while ( active_jobs )
        ;
}
References active_jobs.
queueJob()
void ThreadPool::queueJob (std::function< void()> const & job) inline
Definition at line 120 of file ThreadPool.h.
{
    {
        std::unique_lock<std::mutex> lock( queue_mutex );
        jobs.push( job );
    }
    mutex_condition.notify_one();
}
References jobs, mutex_condition, and queue_mutex.
start()
void ThreadPool::start () inline private
Definition at line 66 of file ThreadPool.h.
{
    //* Max # of threads the system supports
    const uint32_t num_threads = std::thread::hardware_concurrency();
    threads.reserve( num_threads );
    for ( uint32_t i = 0; i < num_threads; ++i )
    {
        threads.emplace_back( std::thread( &ThreadPool::threadLoop, this ) );
    }
}
References threadLoop(), and threads.
Referenced by ThreadPool().
stop()
void ThreadPool::stop () inline
Definition at line 148 of file ThreadPool.h.
{
    //* Only need to check for empty queue, because running jobs will be finished before threads are joined
    while ( isJobQueued() )
        ;
    {
        std::unique_lock<std::mutex> lock( queue_mutex );
        should_terminate = true;
    }
    mutex_condition.notify_all();
    for ( std::thread& active_thread : threads )
    {
        active_thread.join();
    }
    threads.clear();
}
References isJobQueued(), mutex_condition, queue_mutex, should_terminate, and threads.
Referenced by ~ThreadPool().
threadLoop()
void ThreadPool::threadLoop () inline private
Definition at line 79 of file ThreadPool.h.
{
    while ( true )
    {
        std::function<void()> job;
        {
            std::unique_lock<std::mutex> lock( queue_mutex );
            mutex_condition.wait(
                lock,
                [this]
                {
                    return !jobs.empty() || should_terminate;
                }
            );
            if ( should_terminate )
            {
                return;
            }
            job = jobs.front();
            jobs.pop();
        }
        {
            std::unique_lock<std::mutex> lock( active_job_mutex );
            ++active_jobs;
        }
        job();
        {
            std::unique_lock<std::mutex> lock( active_job_mutex );
            --active_jobs;
        }
    }
}
References active_job_mutex, active_jobs, jobs, mutex_condition, queue_mutex, and should_terminate.
Referenced by start().
Member Data Documentation
active_job_mutex
std::mutex ThreadPool::active_job_mutex private
Definition at line 30 of file ThreadPool.h.
Referenced by threadLoop().
active_jobs
int ThreadPool::active_jobs { 0 } private
Definition at line 31 of file ThreadPool.h.
{ 0 };
Referenced by joinJobs(), and threadLoop().
jobs
std::queue<std::function<void()> > ThreadPool::jobs private
Definition at line 27 of file ThreadPool.h.
Referenced by isJobQueued(), queueJob(), and threadLoop().
mutex_condition
std::condition_variable ThreadPool::mutex_condition private
Definition at line 25 of file ThreadPool.h.
Referenced by queueJob(), stop(), and threadLoop().
queue_mutex
std::mutex ThreadPool::queue_mutex private
Definition at line 22 of file ThreadPool.h.
Referenced by isJobQueued(), queueJob(), stop(), and threadLoop().
should_terminate
bool ThreadPool::should_terminate = false private
Definition at line 19 of file ThreadPool.h.
Referenced by stop(), and threadLoop().
threads
std::vector<std::thread> ThreadPool::threads private
Definition at line 26 of file ThreadPool.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following file:
include/ThreadPool.h