Roguelike: RenderSystem Namespace Reference
RenderSystem Namespace Reference
Functions
void loadRenderData (RenderData &renderData)
void renderTile (Textures const &textures, RenderId renderId, Vector2 const &worldPixel, Color const &tint=WHITE)
void renderToChunk (Textures const &textures, RenderId renderId, Vector2 const &worldPixel, Chunk &chunk, Color const &tint=WHITE)
void renderChunk (Chunk const &chunk)
void renderFog (Vector2 const &fogPosition, Fog fog)
void cycleThemes (size_t &theme)
void deinit (Textures &textures)
Function Documentation
cycleThemes()
void RenderSystem::cycleThemes (size_t & theme)
Definition at line 198 of file RenderSystem.cpp.
{
    theme = ( theme < TextureData::themes.size() - 1 ) ? ++theme : 0;
}
References TextureData::themes.
Referenced by SceneModule::setupSceneEvents().
deinit()
void RenderSystem::deinit (Textures & textures)
Definition at line 203 of file RenderSystem.cpp.
{
    TexturesModule::unloadAtlas( textures );
}
References TexturesModule::unloadAtlas().
Referenced by SceneModule::deinitialize().
loadRenderData()
void RenderSystem::loadRenderData (RenderData & renderData)
Definition at line 27 of file RenderSystem.cpp.
{
    //* Load texture atlas
    TexturesModule::loadAtlas(
        renderData.textures,
        textureAtlasFileName(
            renderData.theme
        )
    );
    //* Register textures
    TexturesModule::registerTexture( renderData.textures, RenderId::NONE, { 0, 0 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::CURSOR, { 35, 0 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::HERO, { 70, 0 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::WALL, { 105, 0 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::FLOOR, { 0, 35 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::DESCEND, { 35, 35 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::ASCEND, { 70, 35 } );
    TexturesModule::registerTexture( renderData.textures, RenderId::GOBLIN, { 105, 35 } );
}
References ASCEND, CURSOR, DESCEND, FLOOR, GOBLIN, HERO, TexturesModule::loadAtlas(), NONE, TexturesModule::registerTexture(), textureAtlasFileName(), RenderData::textures, RenderData::theme, and WALL.
Referenced by SceneModule::init(), and SceneModule::setupSceneEvents().
renderChunk()
void RenderSystem::renderChunk (Chunk const & chunk)
Definition at line 127 of file RenderSystem.cpp.
{
    DrawTexturePro(
        chunk.renderTexture.texture,
        Rectangle{
            0,
            0,
            static_cast<float>( chunk.renderTexture.texture.width ),
            static_cast<float>( -chunk.renderTexture.texture.height )
        },
        Rectangle{
            chunk.position.x,
            chunk.position.y,
            ChunkData::chunkSize_f,
            ChunkData::chunkSize_f
        },
        Vector2{ 0, 0 },
        0,
        WHITE
    );
#if defined(DEBUG) && defined(DEBUG_CHUNKS)
    DrawRectangleLinesEx(
        Rectangle{
            chunk.position.x,
            chunk.position.y,
            ChunkData::CHUNK_SIZE_F,
            ChunkData::CHUNK_SIZE_F
        },
        3.0f,
        YELLOW
    );
#endif
}
References Chunk::position, and Chunk::renderTexture.
Referenced by SceneModule::renderOutput().
renderFog()
void RenderSystem::renderFog (Vector2 const & fogPosition, Fog fog)
Definition at line 162 of file RenderSystem.cpp.
{
    Color tint{};
#if defined(DEBUG) && defined(DEBUG_VISIBILITY)
    if ( fog == Fog::OPAQUE )
    {
        tint = ColorAlpha( RED, 0.5f );
    }
    else
    {
        tint = ColorAlpha( BLUE, 0.5f );
    }
#else
    if ( fog == Fog::OPAQUE )
    {
        tint = BLACK;
    }
    else
    {
        tint = ColorAlpha( BLACK, 0.5f );
    }
#endif
    DrawRectangleV(
        fogPosition,
        TileData::tileDimensions,
        tint
    );
}
References OPAQUE, and TileData::tileDimensions.
Referenced by SceneModule::renderOutput().
renderTile()
void RenderSystem::renderTile (Textures const & textures, RenderId renderId, Vector2 const & worldPixel, Color const & tint = WHITE)
Definition at line 48 of file RenderSystem.cpp.
{
    //* Use 0.5f pixel offset to avoid texture bleeding
    DrawTexturePro(
        textures.atlas,
        Rectangle{
            TexturesModule::getTexturePosition(
                textures,
                renderId
            )
                    .x
                + 0.5f,
            TexturesModule::getTexturePosition(
                textures,
                renderId
            )
                    .y
                + 0.5f,
            TextureData::textureSize - ( 2 * 0.5f ),
            TextureData::textureSize - ( 2 * 0.5f )
        },
        Rectangle{
            worldPixel.x,
            worldPixel.y,
            TileData::tileSize,
            TileData::tileSize
        },
        //* TileData::TILE_CENTER,
        Vector2{ 0, 0 },
        0,
        tint
    );
}
References Textures::atlas.
Referenced by SceneModule::renderOutput().
renderToChunk()
void RenderSystem::renderToChunk (Textures const & textures, RenderId renderId, Vector2 const & worldPixel, Chunk & chunk, Color const & tint = WHITE)
Definition at line 87 of file RenderSystem.cpp.
{
    //* Use 0.5f pixel offset to avoid texture bleeding
    DrawTexturePro(
        textures.atlas,
        Rectangle{
            TexturesModule::getTexturePosition(
                textures,
                renderId
            )
                    .x
                + 0.5f,
            TexturesModule::getTexturePosition(
                textures,
                renderId
            )
                    .y
                + 0.5f,
            TextureData::textureSize - ( 2 * 0.5f ),
            TextureData::textureSize - ( 2 * 0.5f )
        },
        Rectangle{
            worldPixel.x - chunk.position.x,
            worldPixel.y - chunk.position.y,
            TileData::tileSize,
            TileData::tileSize
        },
        //* TileData::TILE_CENTER,
        Vector2{ 0, 0 },
        0,
        tint
    );
}
References Textures::atlas.
Referenced by ChunkSystem::init().