Roguelike: src/Game/Systems/UserInputSystem.cpp File Reference
UserInputSystem.cpp File Reference
#include "UserInputSystem.h"
#include "CollisionSystem.h"
#include "Convert.h"
#include "Cursor.h"
#include "DamageSystem.h"
#include "Directions.h"
#include "EventId.h"
#include "GameCamera.h"
#include "HealthComponent.h"
#include "Hero.h"
#include "InputActionId.h"
#include "Logger.h"
#include "Map.h"
#include "MovementSystem.h"
#include "PathfinderSystem.h"
#include "PublisherStatic.h"
#include "raylibEx.h"
#include <raylib.h>
#include <raymath.h>
Functions
void performAttack (Hero &hero, Enemies &enemies, Vector2I const &target)
bool processDirectionalInput (Hero &hero, Map &map, Vector2I direction)
Function Documentation
performAttack()
void performAttack (Hero & hero, Enemies & enemies, Vector2I const & target)
Definition at line 25 of file UserInputSystem.cpp.
{
    snx::Logger::log( "Hero deals " );
    DamageSystem::attack(
        hero.damage,
        enemies.healths.at(
            enemies.ids.at(
                target
            )
        )
    );
}
References snx::DenseMap< Key, Type >::at(), DamageSystem::attack(), Hero::damage, Enemies::healths, Enemies::ids, and snx::Logger::log().
Referenced by processDirectionalInput(), and UserInputSystem::takeAction().
processDirectionalInput()
bool processDirectionalInput (Hero & hero, Map & map, Vector2I direction)
Definition at line 43 of file UserInputSystem.cpp.
{
    bool isActionMultiFrame = false;
    Vector2I target{
        Vector2Add(
            Convert::worldToTile( hero.position ),
            direction
        )
    };
    if ( map.enemies.ids.contains( target ) )
    {
        performAttack(
            hero,
            map.enemies,
            target
        );
        EnergyModule::consume( hero.energy );
    }
    else if ( !CollisionSystem::checkCollision(
                  map.tiles,
                  map.enemies,
                  target,
                  Convert::worldToTile( hero.position )
              ) )
    {
        MovementSystem::prepareByDirection(
            hero.movement,
            direction,
            hero.transform
        );
        EnergyModule::consume( hero.energy );
        isActionMultiFrame = true;
    }
    return isActionMultiFrame;
}
References CollisionSystem::checkCollision(), EnergyModule::consume(), snx::DenseMap< Key, Type >::contains(), Map::enemies, Hero::energy, Enemies::ids, Hero::movement, performAttack(), Hero::position, MovementSystem::prepareByDirection(), Map::tiles, Hero::transform, Vector2Add(), and Convert::worldToTile().
Referenced by UserInputSystem::takeAction().