Roguelike: AppModule Namespace Reference
AppModule Namespace Reference
Functions
void init (Scene &scene, AppConfig const &config)
void update (Scene &scene)
void deinit (Scene &scene)
Function Documentation
deinit()
void AppModule::deinit (Scene & scene)
Definition at line 99 of file App.cpp.
{
    GameFont::unload();
    SceneModule::deinitialize( scene );
    //* Close window and opengl context
    CloseWindow();
}
References SceneModule::deinitialize(), and GameFont::unload().
Referenced by main().
init()
void AppModule::init (Scene & scene, AppConfig const & config)
Definition at line 50 of file App.cpp.
{
    //* TODO: Import configs from user file
    //* Raylib flags
    SetConfigFlags( FLAG_WINDOW_RESIZABLE );
    if ( config.vSync )
    {
        SetConfigFlags( FLAG_VSYNC_HINT );
    }
    //* Initialize window
    InitWindow( config.windowWidth, config.windowHeight, "Roguelike" );
    //* Raylib Settings
    SetWindowIcon( config.favicon );
    SetWindowMinSize( 640, 480 );
#if defined(EMSCRIPTEN)
    MaximizeWindow();
#endif
    SetExitKey( KEY_F4 );
    SetTargetFPS( config.fpsTarget );
    //* Fonts
    GameFont::load();
    GuiSetStyle( DEFAULT, TEXT_SIZE, GameFont::fontHeight );
    //* Scene
    SceneModule::init( scene );
}
References AppConfig::favicon, GameFont::fontHeight, AppConfig::fpsTarget, SceneModule::init(), GameFont::load(), AppConfig::vSync, AppConfig::windowHeight, and AppConfig::windowWidth.
Referenced by main().
update()
void AppModule::update (Scene & scene)
Definition at line 84 of file App.cpp.
{
#if defined(EMSCRIPTEN)
    emscripten_set_main_loop_arg( emscriptenLoop, &app, 60 /*FPS*/, 1 /*Simulate infinite loop*/ );
#else
    while ( !( WindowShouldClose() ) )
    {
        updateWindowState();
        updateDeveloperMode();
        SceneModule::update( scene );
    }
#endif
}
References emscriptenLoop(), SceneModule::update(), updateDeveloperMode(), and updateWindowState().
Referenced by main().