Roguelike: EnergyModule Namespace Reference
EnergyModule Namespace Reference
Functions
bool consume (EnergyComponent &energy)
bool consume (EnergyComponent &energy, int value)
bool regenerate (EnergyComponent &energy)
Function Documentation
consume() [1/2]
bool EnergyModule::consume (EnergyComponent & energy)
Definition at line 3 of file EnergyComponent.cpp.
{
    if ( energy.currentEnergy <= 0 )
    {
        return false;
    }
    //* Consume all available energy
    energy.currentEnergy = 0;
    energy.state = EnergyState::NOT_READY;
    return true;
}
References EnergyComponent::currentEnergy, NOT_READY, and EnergyComponent::state.
Referenced by processDirectionalInput(), AISystem::takeAction(), UserInputSystem::takeAction(), and MovementSystem::updateHero().
consume() [2/2]
bool EnergyModule::consume (EnergyComponent & energy, int value)
Definition at line 18 of file EnergyComponent.cpp.
{
    if ( energy.currentEnergy <= 0 )
    {
        return false;
    }
    //* Consume energy
    energy.currentEnergy -= value;
    if ( energy.currentEnergy <= 0 )
    {
        energy.state = EnergyState::NOT_READY;
    }
    return true;
}
References EnergyComponent::currentEnergy, NOT_READY, and EnergyComponent::state.
regenerate()
bool EnergyModule::regenerate (EnergyComponent & energy)
Definition at line 39 of file EnergyComponent.cpp.
{
    if ( energy.currentEnergy >= energy.maxEnergy )
    {
        return false;
    }
    //* Regen energy until full
    energy.currentEnergy += energy.regenRate;
    if ( energy.currentEnergy < energy.maxEnergy )
    {
        return true;
    }
    //* Ensure energy does not exceed maxEnergy
    energy.currentEnergy = energy.maxEnergy;
    energy.state = EnergyState::READY;
    return true;
}
References EnergyComponent::currentEnergy, EnergyComponent::maxEnergy, READY, EnergyComponent::regenRate, and EnergyComponent::state.
Referenced by EnemiesModule::regenerate(), and GameModule::updateState().