Roguelike: src/Game/Systems/MapGeneratorSystem.cpp File Reference
MapGeneratorSystem.cpp File Reference
#include "MapGeneratorSystem.h"
#include "Directions.h"
#include "Enemies.h"
#include "EventId.h"
#include "Map.h"
#include "Objects.h"
#include "RNG.h"
#include "RenderId.h"
#include "Tiles.h"
#include "raylibEx.h"
#include <array>
#include <raylib.h>
#include <string>
#include <unordered_set>
Functions
void addTiles (Tiles &tiles, RectangleExI const &rectangle, RenderId renderId, bool isSolid=false, bool isOpaque=false)
void addRoom (Tiles &tiles, RectangleExI const &room)
Map createGridRooms (int level)
Function Documentation
addRoom()
void addRoom (Tiles & tiles, RectangleExI const & room)
Definition at line 44 of file MapGeneratorSystem.cpp.
{
    if ( room.width() < 2 || room.height() < 2 )
    {
        return;
    }
    //* Top wall
    addTiles(
        tiles,
        RectangleExI{
            room.left(),
            room.top(),
            room.width() - 1,
            1
        },
        RenderId::WALL,
        true,
        true
    );
    //* Right wall
    addTiles(
        tiles,
        RectangleExI{
            room.right(),
            room.top(),
            1,
            room.height() - 1
        },
        RenderId::WALL,
        true,
        true
    );
    //* Bottom wall
    addTiles(
        tiles,
        RectangleExI{
            room.left() + 1,
            room.bottom(),
            room.width() - 1,
            1
        },
        RenderId::WALL,
        true,
        true
    );
    //* Left wall
    addTiles(
        tiles,
        RectangleExI{
            room.left(),
            room.top() + 1,
            1,
            room.height() - 1
        },
        RenderId::WALL,
        true,
        true
    );
    //* Floor
    addTiles(
        tiles,
        RectangleExI{
            room.left() + 1,
            room.top() + 1,
            room.width() - 2,
            room.height() - 2
        },
        RenderId::FLOOR,
        false,
        false
    );
}
References addTiles(), RectangleExI::bottom(), FLOOR, RectangleExI::height(), RectangleExI::left(), RectangleExI::right(), RectangleExI::top(), WALL, and RectangleExI::width().
Referenced by createGridRooms(), MapGeneratorSystem::createStartRoom(), and MapGeneratorSystem::createTestRoom().
addTiles()
void addTiles (Tiles & tiles, RectangleExI const & rectangle, RenderId renderId, bool isSolid = false, bool isOpaque = false)
Definition at line 17 of file MapGeneratorSystem.cpp.
{
    for ( int x{ 0 }; x < rectangle.width(); ++x )
    {
        for ( int y{ 0 }; y < rectangle.height(); ++y )
        {
            TilesModule::createSingle(
                tiles,
                Vector2I{
                    rectangle.left() + x,
                    rectangle.top() + y
                },
                renderId,
                isSolid,
                isOpaque
            );
        }
    }
}
References TilesModule::createSingle(), RectangleExI::height(), RectangleExI::left(), RectangleExI::top(), and RectangleExI::width().
Referenced by addRoom(), and createGridRooms().
createGridRooms()
Map createGridRooms (int level)
Definition at line 122 of file MapGeneratorSystem.cpp.
{
    Map map{};
    Vector2I roomPosition{ 0, 0 };
    int const roomWidth{ 15 };
    int maxRoomOffset{ ( 2 + level ) * roomWidth };
    //* Add first room
    addRoom(
        map.tiles,
        RectangleExI{
            roomPosition,
            roomWidth,
            roomWidth
        }
    );
    std::unordered_set<Vector2I> usedPositions{ roomPosition };
    //* Take random direction and add room
    while ( Vector2Sum( roomPosition ) < maxRoomOffset )
    {
        //* (Update) Old room position used for room connection
        Vector2I oldRoomPosition{ roomPosition };
        //* Choose random direction
        Vector2I direction{ Directions::directions[snx::RNG::random( 0, 3 )] };
        //* Update new room position
        roomPosition += Vector2Scale( direction, roomWidth );
        //* Add new room if room position unused
        if ( !usedPositions.contains( roomPosition ) )
        {
            usedPositions.insert( roomPosition );
            addRoom(
                map.tiles,
                RectangleExI{
                    roomPosition,
                    roomWidth,
                    roomWidth
                }
            );
        }
        //* Add connection gap in wall between old and new room
        addTiles(
            map.tiles,
            RectangleExI{
                oldRoomPosition,
                roomPosition
            },
            RenderId::FLOOR
        );
    }
    //* Add previous level trigger
    ObjectsModule::createSingle(
        map.objects,
        Vector2I{
            0,
            0
        },
        RenderId::ASCEND,
        "Stairs",
        "Ascend",
        EventId::PREVIOUS_LEVEL
    );
    // Add next level trigger
    // setObject(
    //     map.objects_,
    //     "Descend",
    //     Vector2I{
    //         0,
    //         -5},
    //     RenderId::descend,
    //     EventId::nextLevel);
    //* Add enemies
    EnemiesModule::fillEnemies(
        map.enemies,
        map.tiles,
        level
    );
    return map;
}
References addRoom(), addTiles(), ASCEND, ObjectsModule::createSingle(), Directions::directions, EnemiesModule::fillEnemies(), FLOOR, PREVIOUS_LEVEL, snx::RNG::random(), Vector2Scale(), and Vector2Sum().
Referenced by MapGeneratorSystem::createRandomMap().