Roguelike: snx::Singleton< Type > Class Template Reference
snx::Singleton< Type > Class Template Reference
#include <Singleton.h>
Static Public Member Functions
static Type & instance ()
Protected Member Functions
Singleton ()=default
virtual ~Singleton ()=default
Singleton (Singleton const &)=delete
Singleton & operator= (Singleton const &)=delete
Detailed Description
template<typename Type>
class snx::Singleton< Type >
Definition at line 12 of file Singleton.h.
Constructor & Destructor Documentation
Singleton() [1/2]
template<typename Type> snx::Singleton< Type >::Singleton () protected default
Referenced by operator=(), and Singleton().
~Singleton()
template<typename Type> virtual snx::Singleton< Type >::~Singleton () protected virtual default
Singleton() [2/2]
template<typename Type> snx::Singleton< Type >::Singleton (Singleton< Type > const &) protected delete
References Singleton().
Member Function Documentation
instance()
template<typename Type> static Type & snx::Singleton< Type >::instance () inline static
Definition at line 15 of file Singleton.h.
        {
            static Type instance;
            return instance;
        }
References instance().
Referenced by instance().
operator=()
template<typename Type> Singleton & snx::Singleton< Type >::operator= (Singleton< Type > const &) protected delete
References Singleton().
The documentation for this class was generated from the following file:
include/Singleton.h