Roguelike: snx::BM Class Reference
snx::BM Class Reference
#include <Benchmark.h>
Static Public Member Functions
static void start (std::string bmName="")
static void stop (std::string bmName="")
static void report (std::string bmName="")
static void stopAndReport (std::string bmName="")
Static Private Attributes
static std::unordered_map< std::string, std::chrono::time_point< std::chrono::high_resolution_clock > > starts_
static std::unordered_map< std::string, std::chrono::nanoseconds::rep > durations_
static std::unordered_map< std::string, size_t > measurementCounts_
Detailed Description
Definition at line 13 of file Benchmark.h.
Member Function Documentation
report()
static void snx::BM::report (std::string bmName = "") inline static
Definition at line 49 of file Benchmark.h.
        {
            auto average = ( durations_.at( bmName ) / measurementCounts_.at( bmName ) );
            std::cout
                << "\""
                << bmName
                << "\""
                << ": "
                << average * 10E-6
                << " ms / "
                << 1 / ( average * 10E-9 )
                << " 1/s over "
                << measurementCounts_.at( bmName )
                << " iterations\n";
        }
References durations_, and measurementCounts_.
Referenced by stopAndReport().
start()
static void snx::BM::start (std::string bmName = "") inline static
Definition at line 20 of file Benchmark.h.
        {
            if ( !starts_.contains( bmName ) )
            {
                starts_.insert( { bmName, std::chrono::high_resolution_clock::now() } );
                return;
            }
            starts_.at( bmName ) = std::chrono::high_resolution_clock::now();
        }
References starts_.
stop()
static void snx::BM::stop (std::string bmName = "") inline static
Definition at line 31 of file Benchmark.h.
        {
            auto end = std::chrono::high_resolution_clock::now();
            if ( !durations_.contains( bmName ) )
            {
                durations_.insert( { bmName, ( end - starts_[bmName] ).count() } );
                measurementCounts_.insert( { bmName, 1 } );
            }
            else
            {
                durations_.at( bmName ) += ( end - starts_[bmName] ).count();
                ++measurementCounts_.at( bmName );
            }
        }
References durations_, measurementCounts_, and starts_.
Referenced by stopAndReport().
stopAndReport()
static void snx::BM::stopAndReport (std::string bmName = "") inline static
Definition at line 65 of file Benchmark.h.
        {
            stop( bmName );
            report( bmName );
        }
References report(), and stop().
Member Data Documentation
durations_
std::unordered_map<std::string, std::chrono::nanoseconds::rep> snx::BM::durations_ inline static private
Definition at line 16 of file Benchmark.h.
Referenced by report(), and stop().
measurementCounts_
std::unordered_map<std::string, size_t> snx::BM::measurementCounts_ inline static private
Definition at line 17 of file Benchmark.h.
Referenced by report(), and stop().
starts_
std::unordered_map<std::string, std::chrono::time_point<std::chrono::high_resolution_clock> > snx::BM::starts_ inline static private
Definition at line 15 of file Benchmark.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following file:
include/Benchmark.h