Roguelike: DeveloperMode Class Reference
DeveloperMode Class Reference
#include <DeveloperMode.h>
Static Public Member Functions
static bool isActive ()
static void toggle ()
Static Public Member Functions inherited from snx::Singleton< DeveloperMode >
static DeveloperMode & instance ()
Static Private Attributes
static bool debugMode_ { true }
Additional Inherited Members
Protected Member Functions inherited from snx::Singleton< DeveloperMode >
Singleton ()=default
Singleton (Singleton const &)=delete
virtual ~Singleton ()=default
Singleton & operator= (Singleton const &)=delete
Detailed Description
Definition at line 6 of file DeveloperMode.h.
Member Function Documentation
isActive()
static bool DeveloperMode::isActive () inline static
Definition at line 12 of file DeveloperMode.h.
    {
        return instance().debugMode_;
    }
References debugMode_, and snx::Singleton< DeveloperMode >::instance().
Referenced by SceneModule::update().
toggle()
static void DeveloperMode::toggle () inline static
Definition at line 17 of file DeveloperMode.h.
{ instance().debugMode_ = !instance().debugMode_; }
References debugMode_, and snx::Singleton< DeveloperMode >::instance().
Referenced by updateDeveloperMode().
Member Data Documentation
debugMode_
bool DeveloperMode::debugMode_ { true } inline static private
Definition at line 9 of file DeveloperMode.h.
{ true };
Referenced by isActive(), and toggle().
The documentation for this class was generated from the following file:
include/DeveloperMode.h