Roguelike: Convert Namespace Reference
Convert Namespace Reference
Functions
Vector2I worldToTile (Vector2 const &pixel)
Vector2 tileToWorld (Vector2I const &tilePosition)
Vector2I screenToTile (Vector2 const &pixel, Camera2D const &camera)
Vector2 tileToScreen (Vector2I const &tilePosition, Camera2D const &camera)
Vector2I getMouseTile (Camera2D const &camera)
Vector2I tileToChunk (Vector2I const &tilePosition)
template<typename Type>
Type transformFromOctant (Type const &octantPosition, int octant)
Vector2I octantToTile (Vector2I const &octantPosition, int octant, Vector2I const &origin)
Vector2 octantToWorld (Vector2 const &octantPosition, int octant, Vector2I const &origin)
Vector2 octantToScreen (Vector2 const &octantPosition, int octant, Vector2I const &origin, Camera2D const &camera)
Function Documentation
getMouseTile()
Vector2I Convert::getMouseTile (Camera2D const & camera) inline
Definition at line 60 of file Convert.h.
    {
        return screenToTile(
            GetMousePosition(),
            camera
        );
    }
References screenToTile().
octantToScreen()
Vector2 Convert::octantToScreen (Vector2 const & octantPosition, int octant, Vector2I const & origin, Camera2D const & camera) inline
Definition at line 134 of file Convert.h.
    {
        return GetWorldToScreen2D( octantToWorld( octantPosition, octant, origin ), camera );
    }
References octantToWorld().
octantToTile()
Vector2I Convert::octantToTile (Vector2I const & octantPosition, int octant, Vector2I const & origin) inline
Definition at line 116 of file Convert.h.
    {
        return Vector2Add( origin, transformFromOctant<Vector2I>( octantPosition, octant ) );
    }
References transformFromOctant(), and Vector2Add().
Referenced by VisibilitySystem::calculateVisibilitiesInOctant().
octantToWorld()
Vector2 Convert::octantToWorld (Vector2 const & octantPosition, int octant, Vector2I const & origin) inline
Definition at line 125 of file Convert.h.
    {
        return Vector2Add( tileToWorld( origin ), transformFromOctant<Vector2>( octantPosition, octant ) );
    }
References tileToWorld(), transformFromOctant(), and Vector2Add().
Referenced by octantToScreen().
screenToTile()
Vector2I Convert::screenToTile (Vector2 const & pixel, Camera2D const & camera) inline
Definition at line 39 of file Convert.h.
    {
        Vector2 worldPixel{ GetScreenToWorld2D( pixel, camera ) };
        return worldToTile( worldPixel );
    }
References worldToTile().
Referenced by getMouseTile(), CursorModule::update(), and GameCameraModule::viewportInTiles().
tileToChunk()
Vector2I Convert::tileToChunk (Vector2I const & tilePosition) inline
Definition at line 69 of file Convert.h.
    {
        return Vector2I{
            static_cast<int>( std::floor( tilePosition.x / static_cast<float>( ChunkData::chunkSize ) ) ) * ChunkData::chunkSize,
            static_cast<int>( std::floor( tilePosition.y / static_cast<float>( ChunkData::chunkSize ) ) ) * ChunkData::chunkSize
        };
    }
References ChunkData::chunkSize, Vector2I::x, and Vector2I::y.
Referenced by verifyRequiredChunkExists().
tileToScreen()
Vector2 Convert::tileToScreen (Vector2I const & tilePosition, Camera2D const & camera) inline
Definition at line 50 of file Convert.h.
    {
        Vector2 worldPixel{ tileToWorld( tilePosition ) };
        return GetWorldToScreen2D( worldPixel, camera );
    }
References tileToWorld().
Referenced by checkRatingList(), and PathfinderSystem::findPath().
tileToWorld()
Vector2 Convert::tileToWorld (Vector2I const & tilePosition) inline
Definition at line 30 of file Convert.h.
    {
        return Vector2{
            ( tilePosition.x * TileData::tileSize ),
            ( tilePosition.y * TileData::tileSize )
        };
    }
References TileData::tileSize, Vector2I::x, and Vector2I::y.
Referenced by ObjectsModule::createSingle(), TilesModule::createSingle(), insertSingle(), octantToWorld(), SceneModule::renderOutput(), GameModule::setupGameEvents(), tileToScreen(), CursorModule::update(), and verifyRequiredChunkExists().
transformFromOctant()
template<typename Type> Type Convert::transformFromOctant (Type const & octantPosition, int octant) inline
Definition at line 82 of file Convert.h.
    {
        switch ( octant )
        {
            default:
            case 0:
                return Type( { octantPosition.x, -octantPosition.y } );
            case 1:
                return Type( { octantPosition.y, -octantPosition.x } );
            case 2:
                return Type( { octantPosition.y, octantPosition.x } );
            case 3:
                return Type( { octantPosition.x, octantPosition.y } );
            case 4:
                return Type( { -octantPosition.x, octantPosition.y } );
            case 5:
                return Type( { -octantPosition.y, octantPosition.x } );
            case 6:
                return Type( { -octantPosition.y, -octantPosition.x } );
            case 7:
                return Type( { -octantPosition.x, -octantPosition.y } );
        }
    }
Referenced by octantToTile(), and octantToWorld().
worldToTile()
Vector2I Convert::worldToTile (Vector2 const & pixel) inline
Definition at line 20 of file Convert.h.
    {
        //* World pixel is center of tile
        return Vector2I{
            static_cast<int>( std::floor( ( pixel.x + ( TileData::tileSizeHalf ) ) / TileData::tileSize ) ),
            static_cast<int>( std::floor( ( pixel.y + ( TileData::tileSizeHalf ) ) / TileData::tileSize ) )
        };
    }
References TileData::tileSize, and TileData::tileSizeHalf.
Referenced by checkCollisionWithNextPosition(), ChunkSystem::init(), processDirectionalInput(), EnemiesModule::remove(), SceneModule::renderOutput(), screenToTile(), SceneModule::setupSceneEvents(), AISystem::takeAction(), UserInputSystem::takeAction(), AISystem::takeActions(), CursorModule::update(), EnemiesModule::update(), MovementSystem::updateEnemies(), MovementSystem::updateHero(), and SceneModule::updateState().