Roguelike: src/Scene/Systems/ChunkSystem.cpp File Reference
ChunkSystem.cpp File Reference
#include "ChunkSystem.h"
#include "Chunk.h"
#include "ChunkData.h"
#include "Colors.h"
#include "Convert.h"
#include "DenseMap.h"
#include "RenderSystem.h"
#include "raylibEx.h"
#include <raylib.h>
Functions
void verifyRequiredChunkExists (Vector2I const &tilePosition, snx::DenseMap< Vector2I, Chunk > &chunks)
Function Documentation
verifyRequiredChunkExists()
void verifyRequiredChunkExists (Vector2I const & tilePosition, snx::DenseMap< Vector2I, Chunk > & chunks)
Definition at line 12 of file ChunkSystem.cpp.
{
    Vector2I chunkPosition{ Convert::tileToChunk( tilePosition ) };
    //* If clause is needed due to exclude unnecessary LoadRenderTexture() calls
    if ( !chunks.contains( chunkPosition ) )
    {
        chunks.emplace(
            chunkPosition,
            Convert::tileToWorld( chunkPosition ),
            LoadRenderTexture(
                ChunkData::chunkSize_f,
                ChunkData::chunkSize_f
            )
        );
    }
}
References ChunkData::chunkSize_f, snx::DenseMap< Key, Type >::contains(), snx::DenseMap< Key, Type >::emplace(), Convert::tileToChunk(), and Convert::tileToWorld().
Referenced by ChunkSystem::init().