Roguelike: MapGeneratorSystem Namespace Reference
MapGeneratorSystem Namespace Reference
Functions
Map createTestRoom ()
Map createStartRoom ()
Map createRandomMap (int level)
Function Documentation
createRandomMap()
Map MapGeneratorSystem::createRandomMap (int level)
Definition at line 418 of file MapGeneratorSystem.cpp.
{
    Map newMap{};
    //* Choose map design
    switch ( 1 ) //* RNG::random(1, 2)
    {
        default:
        case 1:
        {
            newMap = createGridRooms( level );
            break;
        }
    }
    return newMap;
}
References createGridRooms().
Referenced by addNewMap().
createStartRoom()
Map MapGeneratorSystem::createStartRoom ()
Definition at line 386 of file MapGeneratorSystem.cpp.
{
    Map startRoom{};
    addRoom(
        startRoom.tiles,
        RectangleExI{
            Vector2I{
                0,
                0
            },
            15,
            15
        }
    );
    //* Add next level trigger
    ObjectsModule::createSingle(
        startRoom.objects,
        Vector2I{
            0,
            -5
        },
        RenderId::DESCEND,
        "Stairs",
        "Descend",
        EventId::NEXT_LEVEL
    );
    return startRoom;
}
References addRoom().
createTestRoom()
Map MapGeneratorSystem::createTestRoom ()
Definition at line 213 of file MapGeneratorSystem.cpp.
{
    Map testRoom{};
    //* Rooms
    addRoom(
        testRoom.tiles,
        RectangleExI{
            Vector2I{
                -75,
                -75
            },
            151,
            151
        }
    );
    addRoom(
        testRoom.tiles,
        RectangleExI{
            Vector2I{
                0,
                0
            },
            15,
            15
        }
    );
    addRoom(
        testRoom.tiles,
        RectangleExI{
            -7,
            2,
            7,
            4
        }
    );
    addRoom(
        testRoom.tiles,
        RectangleExI{
            3,
            -5,
            3,
            5
        }
    );
    //* Add walls
    addTiles(
        testRoom.tiles,
        RectangleExI{
            1,
            0,
            1,
            8
        },
        RenderId::WALL,
        true,
        true
    );
    addTiles(
        testRoom.tiles,
        RectangleExI{
            4,
            -5,
            1,
            5
        },
        RenderId::FLOOR
    );
    addTiles(
        testRoom.tiles,
        RectangleExI{
            3,
            -4,
            3,
            1
        },
        RenderId::FLOOR
    );
    addTiles(
        testRoom.tiles,
        RectangleExI{
            3,
            -2,
            3,
            1
        },
        RenderId::FLOOR
    );
    //* Tiles
    TilesModule::createSingle(
        testRoom.tiles,
        Vector2I{
            0,
            -1
        },
        RenderId::WALL,
        true,
        true
    );
    TilesModule::createSingle(
        testRoom.tiles,
        Vector2I{
            5,
            6
        },
        RenderId::WALL,
        true,
        true
    );
    TilesModule::createSingle(
        testRoom.tiles,
        Vector2I{
            6,
            5
        },
        RenderId::WALL,
        true,
        true
    );
    TilesModule::createSingle(
        testRoom.tiles,
        Vector2I{
            5,
            5
        },
        RenderId::WALL,
        true,
        true
    );
    TilesModule::createSingle(
        testRoom.tiles,
        Vector2I{
            -6,
            5
        },
        RenderId::FLOOR
    );
    //* Next level trigger
    ObjectsModule::createSingle(
        testRoom.objects,
        Vector2I{
            0,
            -5
        },
        RenderId::DESCEND,
        "Stairs",
        "Descend",
        EventId::NEXT_LEVEL
    );
    EnemiesModule::createAtPosition(
        testRoom.enemies,
        testRoom.tiles,
        RenderId::GOBLIN,
        Vector2I{ 3, 0 }
    );
    return testRoom;
}
References addRoom().