Roguelike: PanelSystem Namespace Reference
PanelSystem Namespace Reference
Functions
void init (Panels &panels)
void drawGameInfoPanelContent (Panels const &panels, int level)
void drawHeroInfoPanelContent (Panels const &panels, Hero const &hero)
void drawTileInfoPanelContent (Panels const &panels, Objects const &objects, Vector2I const &cursorPosition)
void drawLogPanelContent (Panels const &panels)
void drawPanelBorders (Panels const &panels)
Function Documentation
drawGameInfoPanelContent()
void PanelSystem::drawGameInfoPanelContent (Panels const & panels, int level)
Definition at line 75 of file PanelSystem.cpp.
{
    //* Draw text for current level
    char const* currentLevel{ TextFormat( "Level %i", level ) };
    Font const& font{ GameFont::font() };
    float fontSize{ GameFont::fontHeight };
    Vector2 textDimensions{
        MeasureTextEx(
            font,
            currentLevel,
            fontSize,
            0
        )
    };
    DrawTextEx(
        font,
        currentLevel,
        Vector2{
            ( ( 0.5f * panels.map.width() ) - ( 0.5f * textDimensions.x ) ),
            ( 0.5f * fontSize )
        },
        fontSize,
        GuiGetStyle( DEFAULT, TEXT_SPACING ),
        RAYWHITE
    );
}
References GameFont::font(), GameFont::fontHeight, Panels::map, and RectangleEx::width().
Referenced by SceneModule::renderOutput().
drawHeroInfoPanelContent()
void PanelSystem::drawHeroInfoPanelContent (Panels const & panels, Hero const & hero)
Definition at line 125 of file PanelSystem.cpp.
{
    int fontSize{ GuiGetStyle( DEFAULT, TEXT_SIZE ) };
    /*
    |= HERO ======|
    |HP : 100/100 |
    |ATK: 2       |
    |             |
    |> INVENTORY  |
    |HEA: RUSTY   |
    |_____________|
    */
    std::string info{};
    info.append( "|= HERO ======|\n" );
    info.append(
        printInfo(
            "HP : "
            + std::to_string( hero.health.currentHealth )
            + "/"
            + std::to_string( hero.health.maxHealth ).c_str()
        )
    );
    info.append( printInfo(
        "ATK : "
        + std::to_string( hero.damage.baseDamage )
    ) );
    info.append( "|_____________|" );
    DrawTextEx(
        GameFont::font(),
        TextFormat(
            info.c_str()
        ),
        Vector2{
            panels.heroInfo.left() + ( 0.5f * GameFont::fontWidth ),
            panels.heroInfo.top() + ( 0.5f * GameFont::fontHeight )
        },
        fontSize,
        0,
        LIGHTGRAY
    );
}
References GameFont::font(), and printInfo().
Referenced by SceneModule::renderOutput().
drawLogPanelContent()
void PanelSystem::drawLogPanelContent (Panels const & panels)
Definition at line 202 of file PanelSystem.cpp.
{
    int fontSize{ GuiGetStyle( DEFAULT, TEXT_SIZE ) };
    double lines{ ( panels.log.height() / ( 1.5 * fontSize ) ) - 1 };
    for ( int n{ 0 }; n < lines; ++n )
    {
        DrawTextEx(
            GameFont::font(),
            snx::Logger::getMessage( n ).c_str(),
            Vector2{
                panels.log.left() + ( 0.5f * fontSize ),
                panels.log.bottom() - ( fontSize * 1.5f ) - ( n * 1.5f * fontSize )
            },
            fontSize,
            0,
            LIGHTGRAY
        );
    }
}
References RectangleEx::bottom(), GameFont::font(), snx::Logger::getMessage(), RectangleEx::height(), RectangleEx::left(), and Panels::log.
Referenced by SceneModule::renderOutput().
drawPanelBorders()
void PanelSystem::drawPanelBorders (Panels const & panels)
Definition at line 224 of file PanelSystem.cpp.
{
    float panelBorderWeight = 1;
    DrawRectangleLinesEx(
        panels.tileInfo.rectangle(),
        panelBorderWeight,
        Color{ 25, 25, 25, 255 }
    );
    DrawRectangleLinesEx(
        panels.heroInfo.rectangle(),
        panelBorderWeight,
        Color{ 25, 25, 25, 255 }
    );
    DrawRectangleLinesEx(
        panels.status.rectangle(),
        panelBorderWeight,
        Color{ 25, 25, 25, 255 }
    );
    DrawRectangleLinesEx(
        panels.log.rectangle(),
        panelBorderWeight,
        Color{ 25, 25, 25, 255 }
    );
    DrawRectangleLinesEx(
        panels.map.rectangle(),
        panelBorderWeight,
        Color{ 25, 25, 25, 255 }
    );
}
References Panels::heroInfo, Panels::log, Panels::map, RectangleEx::rectangle(), Panels::status, and Panels::tileInfo.
Referenced by SceneModule::renderOutput().
drawTileInfoPanelContent()
void PanelSystem::drawTileInfoPanelContent (Panels const & panels, Objects const & objects, Vector2I const & cursorPosition)
Definition at line 175 of file PanelSystem.cpp.
{
    if ( !objects.names.contains( cursorPosition ) )
    {
        return;
    }
    int fontSize{ GuiGetStyle( DEFAULT, TEXT_SIZE ) };
    //* Draw tag and action from tile under cursor
    DrawTextEx(
        GameFont::font(),
        TextFormat( "Object: %s\nAction: %s", objects.names.at( cursorPosition ).c_str(), objects.actions.at( cursorPosition ).c_str() ),
        Vector2{
            panels.tileInfo.left() + ( 0.5f * GameFont::fontWidth ),
            panels.tileInfo.top() + ( 0.5f * fontSize )
        },
        fontSize,
        0,
        LIGHTGRAY
    );
}
References Objects::actions, snx::DenseMap< Key, Type >::at(), snx::DenseMap< Key, Type >::contains(), GameFont::font(), and Objects::names.
Referenced by SceneModule::renderOutput().
init()
void PanelSystem::init (Panels & panels)
Definition at line 17 of file PanelSystem.cpp.
{
    std::string widthString{};
    for ( int n{ 0 }; n < infoPanelWidth; ++n )
    {
        widthString.append( "I" );
    }
    float heroInfoPanelWidth =
        MeasureTextEx(
            GameFont::font(),
            widthString.c_str(),
            GameFont::fontHeight,
            0
        )
            .x;
    float gameInfoPanelHeight =
        static_cast<float>(
            ( /*Number of lines to print*/ 1 * GameFont::fontHeight )
            + GameFont::fontHeight
        );
    float logPanelHeight =
        static_cast<float>(
            ( /*Number of lines to print*/ 4 * GameFont::fontHeight )
            + GameFont::fontHeight
        );
    panels.tileInfo
        .setRight( static_cast<int>( GetRenderWidth() ) )
        .setBottom( static_cast<int>( GetRenderHeight() ) )
        .resizeWidthLeft( heroInfoPanelWidth )
        .resizeHeightTop( logPanelHeight );
    panels.heroInfo
        .setRight( static_cast<int>( GetRenderWidth() ) )
        .setBottom( panels.tileInfo.top() )
        .resizeWidthLeft( heroInfoPanelWidth );
    panels.status
        .setRight( panels.tileInfo.left() )
        .setBottom( gameInfoPanelHeight );
    panels.log
        .setRight( panels.tileInfo.left() )
        .setBottom( static_cast<int>( GetRenderHeight() ) )
        .resizeHeightTop( logPanelHeight );
    panels.map
        .setRight( panels.tileInfo.left() )
        .setBottom( panels.log.top() )
        .setTop( panels.status.bottom() );
    snx::PublisherStatic::publish( EventId::PANELS_RESIZED );
}
References RectangleEx::bottom(), GameFont::font(), GameFont::fontHeight, Panels::heroInfo, infoPanelWidth, RectangleEx::left(), Panels::log, Panels::map, PANELS_RESIZED, snx::PublisherStatic::publish(), RectangleEx::resizeHeightTop(), RectangleEx::resizeWidthLeft(), RectangleEx::setBottom(), RectangleEx::setRight(), RectangleEx::setTop(), Panels::status, Panels::tileInfo, and RectangleEx::top().
Referenced by SceneModule::init(), and SceneModule::setupSceneEvents().