Roguelike: WorldModule Namespace Reference
WorldModule Namespace Reference
Functions
void increaseMapLevel (World &world)
void decreaseMapLevel (World &world)
Function Documentation
decreaseMapLevel()
void WorldModule::decreaseMapLevel (World & world)
Definition at line 33 of file World.cpp.
    {
        if ( world.currentMapLevel == 0 )
        {
            return;
        }
        --world.currentMapLevel;
        setCurrentMap(
            world,
            world.currentMapLevel
        );
    }
References World::currentMapLevel, and setCurrentMap().
Referenced by GameModule::setupGameEvents().
increaseMapLevel()
void WorldModule::increaseMapLevel (World & world)
Definition at line 17 of file World.cpp.
    {
        if ( world.currentMapLevel == world.maxMapLevel )
        {
            ++world.maxMapLevel;
            addNewMap( world );
        }
        ++world.currentMapLevel;
        setCurrentMap(
            world,
            world.currentMapLevel
        );
    }
References addNewMap(), World::currentMapLevel, World::maxMapLevel, and setCurrentMap().
Referenced by GameModule::setupGameEvents().