Roguelike: MovementSystem Namespace Reference
MovementSystem Namespace Reference
Functions
void updateHero (TransformComponent &transform, Vector2 &position, EnergyComponent &energy, Vector2 const &heroPosition)
void updateEnemies (Enemies &enemies, Vector2 const &heroPosition)
void prepareByDirection (MovementComponent const &movement, Vector2I const &direction, TransformComponent &transform)
void prepareByNewPath (MovementComponent &movement, std::vector< Vector2I > const &path)
void prepareFromExistingPath (MovementComponent &movement, TransformComponent &transform)
void prepareByFromTo (MovementComponent &movement, TransformComponent &transform, Vector2I const &from, Vector2I const &to)
void resetTransform (TransformComponent &transform)
void resetCumulativeDistance (TransformComponent &transform)
Vector2 frameOffset (TransformComponent const &transform)
Function Documentation
frameOffset()
Vector2 MovementSystem::frameOffset (TransformComponent const & transform)
Definition at line 212 of file MovementSystem.cpp.
{
    return Vector2Scale(
        transform.direction,
        transform.speed * GetFrameTime()
    );
}
References TransformComponent::direction, TransformComponent::speed, and Vector2Scale().
Referenced by updateHero().
prepareByDirection()
void MovementSystem::prepareByDirection (MovementComponent const & movement, Vector2I const & direction, TransformComponent & transform)
Definition at line 136 of file MovementSystem.cpp.
{
    transform.direction = direction;
    transform.speed = movement.baseSpeed;
}
References MovementComponent::baseSpeed, TransformComponent::direction, and TransformComponent::speed.
Referenced by prepareByFromTo(), prepareFromExistingPath(), and processDirectionalInput().
prepareByFromTo()
void MovementSystem::prepareByFromTo (MovementComponent & movement, TransformComponent & transform, Vector2I const & from, Vector2I const & to)
Definition at line 183 of file MovementSystem.cpp.
{
    prepareByDirection(
        movement,
        Vector2Subtract(
            to,
            from
        ),
        transform
    );
}
References prepareByDirection(), and Vector2Subtract().
Referenced by AISystem::takeAction().
prepareByNewPath()
void MovementSystem::prepareByNewPath (MovementComponent & movement, std::vector< Vector2I > const & path)
Definition at line 170 of file MovementSystem.cpp.
{
    if ( path.empty() )
    {
        return;
    }
    movement.path = path;
}
References MovementComponent::path.
Referenced by UserInputSystem::takeAction().
prepareFromExistingPath()
void MovementSystem::prepareFromExistingPath (MovementComponent & movement, TransformComponent & transform)
Definition at line 146 of file MovementSystem.cpp.
{
    prepareByDirection(
        movement,
        Vector2Subtract(
            movement.path.rbegin()[1],
            movement.path.rbegin()[0]
        ),
        transform
    );
    //* Remove tilePosition moved from
    movement.path.pop_back();
    //* Clear path guided movement after last trigger if target reched (path_.size() == 1 (target))
    if ( movement.path.size() <= 1 )
    {
        movement.path.clear();
    }
}
References MovementComponent::path, prepareByDirection(), and Vector2Subtract().
Referenced by UserInputSystem::takeAction().
resetCumulativeDistance()
void MovementSystem::resetCumulativeDistance (TransformComponent & transform)
Definition at line 207 of file MovementSystem.cpp.
{
    transform.cumulativeDistance = 0;
}
References TransformComponent::cumulativeDistance.
Referenced by updateHero().
resetTransform()
void MovementSystem::resetTransform (TransformComponent & transform)
Definition at line 200 of file MovementSystem.cpp.
{
    // transform.isInProgress_ = false;
    transform.direction = Vector2I{ 0, 0 };
    transform.speed = .0f;
}
References TransformComponent::direction, and TransformComponent::speed.
Referenced by GameModule::setupGameEvents(), UserInputSystem::takeAction(), and updateHero().
updateEnemies()
void MovementSystem::updateEnemies (Enemies & enemies, Vector2 const & heroPosition)
Definition at line 98 of file MovementSystem.cpp.
{
    Vector2* currentPosition{};
    Vector2I oldPosition{};
    //* get new positions
    //* update all positions/movements/transforms
    for ( size_t idx{ 0 }; idx < enemies.transforms.size(); ++idx )
    {
        currentPosition = &enemies.positions.values().at( idx );
        oldPosition = Convert::worldToTile( *currentPosition );
        //* Update movement
        //* Update ids_ key if tilePosition changes
        MovementSystem::updateHero(
            enemies.transforms.values().at( idx ),
            // enemies.movements.values().at(i),
            *currentPosition,
            enemies.energies.values().at( idx ),
            heroPosition
        );
        if ( oldPosition != Convert::worldToTile( *currentPosition ) )
        {
            enemies.ids.changeKey(
                oldPosition,
                Convert::worldToTile( *currentPosition )
            );
        }
    }
}
References snx::DenseMap< Key, Type >::changeKey(), Enemies::energies, Enemies::ids, Enemies::positions, snx::DenseMap< Key, Type >::size(), Enemies::transforms, updateHero(), snx::DenseMap< Key, Type >::values(), and Convert::worldToTile().
Referenced by GameModule::updateState().
updateHero()
void MovementSystem::updateHero (TransformComponent & transform, Vector2 & position, EnergyComponent & energy, Vector2 const & heroPosition)
Definition at line 13 of file MovementSystem.cpp.
{
    //* Start movement from path
    // if (!movement.path.empty()
    //     && !transform.speed
    //     // && !CollisionSystem::checkCollision(
    //     //          map.tiles,
    //     //          map.enemies,
    //     //          target,
    //     //          Convert::worldToTile(hero.position))
    //     )
    // {
    //     prepareFromExistingPath(
    //         movement,
    //         transform);
    // }
    //* Check if action is in progress
    if ( transform.speed )
    {
        EnergyModule::consume( energy );
        snx::PublisherStatic::publish( EventId::MULTIFRAME_ACTION_ACTIVE );
    }
    else
    {
        return;
    }
    Vector2 offset{ frameOffset( transform ) };
    transform.cumulativeDistance += Vector2Length( offset );
    Vector2I oldPosition{ Convert::worldToTile( position ) };
    //* Check if movement exceeds tile length this frame
    if ( transform.cumulativeDistance < TileData::tileSize )
    {
        //* Move full distance this frame
        position += offset;
    }
    else
    {
        //* Move by remaining distance until TILE_SIZE
        position += Vector2ClampValue(
            offset,
            0,
            TileData::tileSize
                - ( transform.cumulativeDistance
                    - Vector2Length( offset ) )
        );
        //* === Moved one tile ===
        //* Clean precision errors
        position = Vector2Round( position );
        //* Reset cumulativeDistance
        resetCumulativeDistance( transform );
        resetTransform( transform );
        snx::PublisherStatic::publish( EventId::MULTIFRAME_ACTION_DONE );
    }
    //* Check if unit moving is the hero
    if ( position != heroPosition )
    {
        return;
    }
    //* Handle special case for hero
    snx::PublisherStatic::publish( EventId::HERO_MOVED );
    if ( oldPosition != Convert::worldToTile( position ) )
    {
        snx::PublisherStatic::publish( EventId::HERO_POSITION_CHANGED );
    }
}
References EnergyModule::consume(), TransformComponent::cumulativeDistance, frameOffset(), HERO_MOVED, HERO_POSITION_CHANGED, MULTIFRAME_ACTION_ACTIVE, MULTIFRAME_ACTION_DONE, snx::PublisherStatic::publish(), resetCumulativeDistance(), resetTransform(), TransformComponent::speed, TileData::tileSize, Vector2Length(), Vector2Round(), and Convert::worldToTile().
Referenced by EnemiesModule::update(), updateEnemies(), and GameModule::updateState().