Roguelike: GameCameraModule Namespace Reference
GameCameraModule Namespace Reference
Functions
void init (GameCamera &gameCamera, RectangleEx const &viewport, Vector2 const &heroPosition)
RectangleExI viewportInTiles (GameCamera &gameCamera)
void setOffset (GameCamera &gameCamera, Vector2 const &offset)
void setTarget (GameCamera &gameCamera, Vector2 const &target)
void setZoom (GameCamera &gameCamera, float zoom)
void updateViewport (GameCamera &gameCamera, RectangleEx const &viewport)
Function Documentation
init()
void GameCameraModule::init (GameCamera & gameCamera, RectangleEx const & viewport, Vector2 const & heroPosition)
Definition at line 9 of file GameCamera.cpp.
{
    gameCamera.viewport = &viewport;
    gameCamera.camera = Camera2D{
        viewport.center(),
        heroPosition,
        0,
        0.75
    };
    snx::PublisherStatic::publish( EventId::CAMERA_CHANGED );
}
References GameCamera::camera, CAMERA_CHANGED, RectangleEx::center(), snx::PublisherStatic::publish(), and GameCamera::viewport.
Referenced by SceneModule::init(), and SceneModule::setupSceneEvents().
setOffset()
void GameCameraModule::setOffset (GameCamera & gameCamera, Vector2 const & offset)
Definition at line 27 of file GameCamera.cpp.
{
    gameCamera.camera.offset = offset;
    snx::PublisherStatic::publish( EventId::CAMERA_CHANGED );
}
References GameCamera::camera, CAMERA_CHANGED, and snx::PublisherStatic::publish().
setTarget()
void GameCameraModule::setTarget (GameCamera & gameCamera, Vector2 const & target)
Definition at line 36 of file GameCamera.cpp.
{
    gameCamera.camera.target = target;
    snx::PublisherStatic::publish( EventId::CAMERA_CHANGED );
}
References GameCamera::camera, CAMERA_CHANGED, and snx::PublisherStatic::publish().
Referenced by SceneModule::setupSceneEvents().
setZoom()
void GameCameraModule::setZoom (GameCamera & gameCamera, float zoom)
Definition at line 45 of file GameCamera.cpp.
{
    gameCamera.camera.zoom = zoom;
    snx::PublisherStatic::publish( EventId::CAMERA_CHANGED );
}
References GameCamera::camera, CAMERA_CHANGED, and snx::PublisherStatic::publish().
updateViewport()
void GameCameraModule::updateViewport (GameCamera & gameCamera, RectangleEx const & viewport)
viewportInTiles()
RectangleExI GameCameraModule::viewportInTiles (GameCamera & gameCamera)
Definition at line 54 of file GameCamera.cpp.
{
    return RectangleExI{
        Convert::screenToTile(
            gameCamera.viewport->topLeft(),
            gameCamera.camera
        ),
        Convert::screenToTile(
            gameCamera.viewport->bottomRight(),
            gameCamera.camera
        )
    };
}
References RectangleEx::bottomRight(), GameCamera::camera, Convert::screenToTile(), RectangleEx::topLeft(), and GameCamera::viewport.
Referenced by SceneModule::setupSceneEvents().