Roguelike: src/App.cpp File Reference
App.cpp File Reference
#include "App.h"
#include "DeveloperMode.h"
#include "EventId.h"
#include "GameFont.h"
#include "PublisherStatic.h"
#include <raygui.h>
#include <raylib.h>
Functions
void emscriptenLoop (void *arg)
void updateWindowState ()
void updateDeveloperMode ()
Function Documentation
emscriptenLoop()
void emscriptenLoop (void * arg)
Definition at line 14 of file App.cpp.
{
    App* app = (App*)arg;
    SceneModule::update( app->scene );
}
References App::scene, and SceneModule::update().
Referenced by AppModule::update().
updateDeveloperMode()
void updateDeveloperMode ()
Definition at line 42 of file App.cpp.
{
    if ( IsKeyPressed( KEY_F1 ) )
    {
        DeveloperMode::toggle();
    }
}
References DeveloperMode::toggle().
Referenced by AppModule::update().
updateWindowState()
void updateWindowState ()
Definition at line 21 of file App.cpp.
{
    if ( IsKeyPressed( KEY_F11 ) )
    {
        if ( IsWindowMaximized() )
        {
            RestoreWindow();
        }
        else
        {
            MaximizeWindow();
        }
    }
    if ( IsWindowResized() )
    {
        snx::PublisherStatic::publish( EventId::WINDOW_RESIZED );
    }
}
References snx::PublisherStatic::publish(), and WINDOW_RESIZED.
Referenced by AppModule::update().