Roguelike: HealthModule Namespace Reference
HealthModule Namespace Reference
Functions
bool damage (HealthComponent &health, int value=0)
void heal (HealthComponent &health, int value=0)
void regenerate (HealthComponent &health)
Function Documentation
damage()
bool HealthModule::damage (HealthComponent & health, int value = 0)
Definition at line 10 of file HealthComponent.cpp.
{
#if defined(DEBUG) && defined(DEBUG_HEALTH)
    snx::debug::cliLog( "Remove " + std::to_string( value ) + " from " + std::to_string( health.currentHealth ) + " health\n" );
#endif
    if ( value )
    {
        health.currentHealth -= value;
    }
    else
    {
        health.currentHealth = 0;
    }
    snx::PublisherStatic::publish( EventId::INTERRUPT_MOVEMENT );
    if ( health.currentHealth <= 0 )
    {
        return true;
    }
    return false;
}
References snx::debug::cliLog(), HealthComponent::currentHealth, INTERRUPT_MOVEMENT, and snx::PublisherStatic::publish().
Referenced by DamageSystem::attack().
heal()
void HealthModule::heal (HealthComponent & health, int value = 0)
Definition at line 37 of file HealthComponent.cpp.
{
    if ( value )
    {
        health.currentHealth += value;
    }
    else
    {
        health.currentHealth = health.maxHealth;
    }
    if ( health.currentHealth > health.maxHealth )
    {
        health.currentHealth = health.maxHealth;
    }
}
References HealthComponent::currentHealth, and HealthComponent::maxHealth.
Referenced by regenerate().
regenerate()
void HealthModule::regenerate (HealthComponent & health)
Definition at line 57 of file HealthComponent.cpp.
{
#if defined(DEBUG) && defined(DEBUG_HEALTH)
    snx::debug::cliLog( "Gain " + std::to_string( health.regenRate ) + " to " + std::to_string( health.currentHealth ) + " health\n" );
#endif
    HealthModule::heal(
        health,
        health.regenRate
    );
}
References snx::debug::cliLog(), HealthComponent::currentHealth, heal(), and HealthComponent::regenRate.
Referenced by UserInputSystem::takeAction().