Roguelike: CursorModule Namespace Reference
CursorModule Namespace Reference
Functions
void toggle (Cursor &cursor)
void update (Cursor &cursor, Camera2D const &camera, Vector2I const &heroPosition)
Function Documentation
toggle()
void CursorModule::toggle (Cursor & cursor)
Definition at line 9 of file Cursor.cpp.
{
    cursor.isActive = !cursor.isActive;
    if ( cursor.isActive )
    {
        HideCursor();
        return;
    }
    ShowCursor();
}
References Cursor::isActive.
Referenced by SceneModule::setupSceneEvents().
update()
void CursorModule::update (Cursor & cursor, Camera2D const & camera, Vector2I const & heroPosition)
Definition at line 22 of file Cursor.cpp.
{
    //* Update cursor position if active
    if ( cursor.isActive )
    {
        Vector2I mouseTile{ Convert::screenToTile( GetMousePosition(), camera ) };
        if ( !( Convert::worldToTile( cursor.position ) == mouseTile ) )
        {
            cursor.position = Convert::tileToWorld( mouseTile );
            snx::PublisherStatic::publish( EventId::CURSOR_POSITION_CHANGED );
        }
        return;
    }
    //* Keep cursor on hero if inactive
    cursor.position = Convert::tileToWorld( heroPosition );
}
References CURSOR_POSITION_CHANGED, Cursor::isActive, Cursor::position, snx::PublisherStatic::publish(), Convert::screenToTile(), Convert::tileToWorld(), and Convert::worldToTile().
Referenced by SceneModule::updateState().