Roguelike: TilesModule Namespace Reference
TilesModule Namespace Reference
Functions
void createSingle (Tiles &tiles, Vector2I const &tilePosition, RenderId renderId, bool isSolid, bool isOpaque, VisibilityId visibilityId)
Function Documentation
createSingle()
void TilesModule::createSingle (Tiles & tiles, Vector2I const & tilePosition, RenderId renderId, bool isSolid, bool isOpaque, VisibilityId visibilityId)
Definition at line 29 of file Tiles.cpp.
    {
        tiles.positions[tilePosition] = Convert::tileToWorld( tilePosition );
        tiles.renderIds[tilePosition] = renderId;
        tiles.visibilityIds[tilePosition] = visibilityId;
        if ( isSolid )
        {
            tiles.isSolids.insert( tilePosition );
        }
        else
        {
            tiles.isSolids.erase( tilePosition );
        }
        if ( isOpaque )
        {
            tiles.isOpaques.insert( tilePosition );
        }
        else
        {
            tiles.isOpaques.erase( tilePosition );
        }
        updateMapSize(
            tiles,
            tilePosition
        );
    }
References Tiles::isOpaques, Tiles::isSolids, Tiles::positions, Tiles::renderIds, Convert::tileToWorld(), updateMapSize(), and Tiles::visibilityIds.
Referenced by addTiles().