Roguelike: snx::debug Class Reference
snx::debug Class Reference
#include <Debugger.h>
Static Public Member Functions
static GameCamera & gcam ()
template<typename Arg>
static void cliPrint (Arg message)
template<typename Arg, typename... Args>
static void cliPrint (Arg message, Args... args)
template<typename Arg>
static void cliLog (Arg message)
template<typename Arg, typename... Args>
static void cliLog (Arg message, Args... args)
Static Public Member Functions inherited from snx::Singleton< debug >
static debug & instance ()
Static Private Attributes
static GameCamera gcam_ {}
Additional Inherited Members
Protected Member Functions inherited from snx::Singleton< debug >
Singleton ()=default
Singleton (Singleton const &)=delete
virtual ~Singleton ()=default
Singleton & operator= (Singleton const &)=delete
Detailed Description
Definition at line 14 of file Debugger.h.
Member Function Documentation
cliLog() [1/2]
template<typename Arg> static void snx::debug::cliLog (Arg message) inline static
Definition at line 42 of file Debugger.h.
        {
            auto now = std::chrono::system_clock::now();
            std::string formatted_time = std::format( "{0:%T}", now );
            std::cout << "[" << formatted_time << "] " << message;
        }
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), InputModule::checkGesture(), cliLog(), HealthModule::damage(), HealthModule::regenerate(), SceneModule::setupSceneEvents(), and VisibilitySystem::updateShadowline().
cliLog() [2/2]
template<typename Arg, typename... Args> static void snx::debug::cliLog (Arg message, Args... args) inline static
Definition at line 50 of file Debugger.h.
        {
            cliLog( message );
            cliPrint( args... );
            std::cout << "\n";
        }
References cliLog(), and cliPrint().
cliPrint() [1/2]
template<typename Arg> static void snx::debug::cliPrint (Arg message) inline static
Definition at line 25 of file Debugger.h.
        {
            std::cout << message;
        }
Referenced by cliLog(), cliPrint(), SceneModule::setupSceneEvents(), and VisibilitySystem::update().
cliPrint() [2/2]
template<typename Arg, typename... Args> static void snx::debug::cliPrint (Arg message, Args... args) inline static
Definition at line 31 of file Debugger.h.
        {
            cliPrint( message );
            cliPrint( args... );
            std::cout << "\n";
        }
References cliPrint().
gcam()
static GameCamera & snx::debug::gcam () inline static
Definition at line 19 of file Debugger.h.
        {
            return instance().gcam_;
        }
References gcam_, and snx::Singleton< debug >::instance().
Referenced by checkRatingList(), PathfinderSystem::findPath(), SceneModule::init(), and SceneModule::updateState().
Member Data Documentation
gcam_
GameCamera snx::debug::gcam_ {} inline static private
Definition at line 16 of file Debugger.h.
{};
Referenced by gcam().
The documentation for this class was generated from the following file:
include/Debugger.h