Roguelike: ShadowModule Namespace Reference
ShadowModule Namespace Reference
Functions
float slopeLeft (Shadow const &shadow)
void setSlopeLeft (Shadow &shadow, Vector2I const &octantPosition)
void setSlopeLeft (Shadow &shadow, float slopeLeft)
float slopeRight (Shadow const &shadow)
void setSlopeRight (Shadow &shadow, Vector2I const &octantPosition)
void setSlopeRight (Shadow &shadow, float slopeRight)
float getLeftAtTop (Shadow const &shadow, Vector2I const &octantPosition)
float getLeftAtBottom (Shadow const &shadow, Vector2I const &octantPosition)
float getLeft (Shadow const &shadow, int octantPositionHeight)
float getRightAtTop (Shadow const &shadow, Vector2I const &octantPosition)
float getRightAtBottom (Shadow const &shadow, Vector2I const &octantPosition)
float getRight (Shadow const &shadow, int octantPositionHeight)
Function Documentation
getLeft()
float ShadowModule::getLeft (Shadow const & shadow, int octantPositionHeight)
Definition at line 97 of file VisibilitySystem.cpp.
{
    //* NOTE: x = y / m
    return ( octantPositionHeight ) / shadow.slopeLeft;
}
References Shadow::slopeLeft.
getLeftAtBottom()
float ShadowModule::getLeftAtBottom (Shadow const & shadow, Vector2I const & octantPosition)
Definition at line 89 of file VisibilitySystem.cpp.
{
    return ( octantPosition.y - 0.5f ) / shadow.slopeLeft;
}
References Shadow::slopeLeft, and Vector2I::y.
Referenced by VisibilitySystem::updateShadowline().
getLeftAtTop()
float ShadowModule::getLeftAtTop (Shadow const & shadow, Vector2I const & octantPosition)
Definition at line 81 of file VisibilitySystem.cpp.
{
    return ( octantPosition.y + 0.5f ) / shadow.slopeLeft;
}
References Shadow::slopeLeft, and Vector2I::y.
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), and VisibilitySystem::updateShadowline().
getRight()
float ShadowModule::getRight (Shadow const & shadow, int octantPositionHeight)
Definition at line 122 of file VisibilitySystem.cpp.
{
    //* NOTE: x = y / m
    return ( octantPositionHeight ) / shadow.slopeRight;
}
References Shadow::slopeRight.
getRightAtBottom()
float ShadowModule::getRightAtBottom (Shadow const & shadow, Vector2I const & octantPosition)
Definition at line 114 of file VisibilitySystem.cpp.
{
    return ( octantPosition.y - 0.5f ) / shadow.slopeRight;
}
References Shadow::slopeRight, and Vector2I::y.
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), and VisibilitySystem::updateShadowline().
getRightAtTop()
float ShadowModule::getRightAtTop (Shadow const & shadow, Vector2I const & octantPosition)
Definition at line 106 of file VisibilitySystem.cpp.
{
    return ( octantPosition.y + 0.5f ) / shadow.slopeRight;
}
References Shadow::slopeRight, and Vector2I::y.
Referenced by VisibilitySystem::updateShadowline().
setSlopeLeft() [1/2]
void ShadowModule::setSlopeLeft (Shadow & shadow, float slopeLeft)
Definition at line 50 of file VisibilitySystem.cpp.
{
    shadow.slopeLeft = slopeLeft;
}
References Shadow::slopeLeft, and slopeLeft().
setSlopeLeft() [2/2]
void ShadowModule::setSlopeLeft (Shadow & shadow, Vector2I const & octantPosition)
Definition at line 42 of file VisibilitySystem.cpp.
{
    shadow.slopeLeft = ( octantPosition.y + 0.5f ) / ( octantPosition.x - 0.5f );
}
References Shadow::slopeLeft, Vector2I::x, and Vector2I::y.
Referenced by Shadow::Shadow(), and VisibilitySystem::updateShadowline().
setSlopeRight() [1/2]
void ShadowModule::setSlopeRight (Shadow & shadow, float slopeRight)
Definition at line 73 of file VisibilitySystem.cpp.
{
    shadow.slopeRight = slopeRight;
}
References Shadow::slopeRight, and slopeRight().
setSlopeRight() [2/2]
void ShadowModule::setSlopeRight (Shadow & shadow, Vector2I const & octantPosition)
Definition at line 65 of file VisibilitySystem.cpp.
{
    shadow.slopeRight = std::max( EPSILON, ( octantPosition.y - 0.5f ) / ( octantPosition.x + 0.5f ) );
}
References Shadow::slopeRight, Vector2I::x, and Vector2I::y.
Referenced by Shadow::Shadow(), and VisibilitySystem::updateShadowline().
slopeLeft()
float ShadowModule::slopeLeft (Shadow const & shadow)
Definition at line 35 of file VisibilitySystem.cpp.
{
    return shadow.slopeLeft;
}
References Shadow::slopeLeft.
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), setSlopeLeft(), and VisibilitySystem::updateShadowline().
slopeRight()
float ShadowModule::slopeRight (Shadow const & shadow)
Definition at line 58 of file VisibilitySystem.cpp.
{
    return shadow.slopeRight;
}
References Shadow::slopeRight.
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), setSlopeRight(), and VisibilitySystem::updateShadowline().