Roguelike: RectangleExI Class Reference
RectangleExI Class Reference
#include <raylibEx.h>
Public Member Functions
RectangleExI ()=default
RectangleExI (int left, int top, int width=1, int height=1)
RectangleExI (Vector2I const &topLeft, Vector2I const &bottomRight={ 0, 0 })
RectangleExI (Vector2I const &center, int width, int height)
int left () const
RectangleExI & setLeft (int left)
RectangleExI & offsetLeft (int left)
int right () const
RectangleExI & setRight (int right)
RectangleExI & offsetRight (int right)
int top () const
RectangleExI & setTop (int top)
RectangleExI & offsetTop (int top)
int bottom () const
RectangleExI & setBottom (int bottom)
RectangleExI & offsetBottom (int bottom)
int width () const
RectangleExI & resizeWidthRight (int width)
RectangleExI & resizeWidthLeft (int width)
int height () const
RectangleExI & resizeHeightBottom (int height)
RectangleExI & resizeHeightTop (int height)
Vector2I topLeft () const
Vector2I bottomRight () const
Vector2I center () const
Rectangle rectangle () const
Private Member Functions
void updateWidth ()
void updateHeight ()
void updateLeft ()
void updateTop ()
void updateRight ()
void updateBottom ()
void validate ()
Private Attributes
int left_ {}
int top_ {}
int right_ {}
int bottom_ {}
int width_ {}
int height_ {}
Detailed Description
Definition at line 287 of file raylibEx.h.
Constructor & Destructor Documentation
RectangleExI() [1/4]
RectangleExI::RectangleExI () default
Referenced by offsetBottom(), offsetLeft(), offsetRight(), offsetTop(), resizeHeightBottom(), resizeHeightTop(), resizeWidthLeft(), resizeWidthRight(), setBottom(), setLeft(), setRight(), and setTop().
RectangleExI() [2/4]
RectangleExI::RectangleExI (int left, int top, int width = 1, int height = 1) inline
Definition at line 299 of file raylibEx.h.
        : left_( left )
        , top_( top )
        , right_( left + width - 1 )
        , bottom_( top + height - 1 )
        , width_( width )
        , height_( height )
    {
        validate();
    }
References bottom_, height(), height_, left(), left_, right_, top(), top_, validate(), width(), and width_.
RectangleExI() [3/4]
RectangleExI::RectangleExI (Vector2I const & topLeft, Vector2I const & bottomRight = { 0, 0 }) inline
Definition at line 315 of file raylibEx.h.
                                      { 0, 0 }
    )
        : left_( topLeft.x )
        , top_( topLeft.y )
        , right_( bottomRight.x )
        , bottom_( bottomRight.y )
        , width_( bottomRight.x - topLeft.x + 1 )
        , height_( bottomRight.y - topLeft.y + 1 )
    {
        validate();
    }
References bottomRight(), and topLeft().
RectangleExI() [4/4]
RectangleExI::RectangleExI (Vector2I const & center, int width, int height) inline
Definition at line 330 of file raylibEx.h.
        : left_( center.x - ( width / 2 ) )
        , top_( center.y - ( height / 2 ) )
        , right_( center.x + ( width / 2 ) )
        , bottom_( center.y + ( height / 2 ) )
        , width_( width )
        , height_( height )
    {
        validate();
#if defined(DEBUG)
        assert( ( width % 2 ) && ( height % 2 ) && "[ERROR] Width or height invalid; Must be odd value!" );
#endif
    }
References bottom_, center(), height(), height_, left_, right_, top_, validate(), width(), and width_.
Member Function Documentation
bottom()
int RectangleExI::bottom () const inline
Definition at line 405 of file raylibEx.h.
    {
        return bottom_;
    }
References bottom_.
Referenced by addRoom(), CheckCollisionPointRec(), offsetBottom(), setBottom(), and updateMapSize().
bottomRight()
Vector2I RectangleExI::bottomRight () const inline
Definition at line 470 of file raylibEx.h.
    {
        return Vector2I{
            right_,
            bottom_
        };
    }
References bottom_, and right_.
Referenced by RectangleExI().
center()
Vector2I RectangleExI::center () const inline
Definition at line 478 of file raylibEx.h.
    {
        return Vector2I{
            ( left_ + ( width_ / 2 ) ),
            ( top_ + ( height_ / 2 ) )
        };
    }
References height_, left_, top_, and width_.
Referenced by RectangleExI().
height()
int RectangleExI::height () const inline
Definition at line 443 of file raylibEx.h.
    {
        return height_;
    }
References height_.
Referenced by addRoom(), addTiles(), RectangleExI(), RectangleExI(), resizeHeightBottom(), resizeHeightTop(), and VisibilitySystem::update().
left()
int RectangleExI::left () const inline
Definition at line 348 of file raylibEx.h.
    {
        return left_;
    }
References left_.
Referenced by addRoom(), addTiles(), CheckCollisionPointRec(), offsetLeft(), RectangleExI(), setLeft(), and updateMapSize().
offsetBottom()
RectangleExI & RectangleExI::offsetBottom (int bottom) inline
Definition at line 417 of file raylibEx.h.
    {
        bottom_ += bottom;
        updateHeight();
        return *this;
    }
References bottom(), bottom_, RectangleExI(), and updateHeight().
offsetLeft()
RectangleExI & RectangleExI::offsetLeft (int left) inline
Definition at line 360 of file raylibEx.h.
    {
        left_ += left;
        updateWidth();
        return *this;
    }
References left(), left_, RectangleExI(), and updateWidth().
offsetRight()
RectangleExI & RectangleExI::offsetRight (int right) inline
Definition at line 379 of file raylibEx.h.
    {
        right_ += right;
        updateWidth();
        return *this;
    }
References RectangleExI(), right(), right_, and updateWidth().
offsetTop()
RectangleExI & RectangleExI::offsetTop (int top) inline
Definition at line 398 of file raylibEx.h.
    {
        top_ += top;
        updateHeight();
        return *this;
    }
References RectangleExI(), top(), top_, and updateHeight().
rectangle()
Rectangle RectangleExI::rectangle () const inline
Definition at line 486 of file raylibEx.h.
    {
        return Rectangle{
            static_cast<float>( left_ ),
            static_cast<float>( top_ ),
            static_cast<float>( width_ ),
            static_cast<float>( height_ )
        };
    }
References height_, left_, top_, and width_.
resizeHeightBottom()
RectangleExI & RectangleExI::resizeHeightBottom (int height) inline
Definition at line 448 of file raylibEx.h.
    {
        height_ = height;
        updateBottom();
        return *this;
    }
References height(), height_, RectangleExI(), and updateBottom().
resizeHeightTop()
RectangleExI & RectangleExI::resizeHeightTop (int height) inline
Definition at line 455 of file raylibEx.h.
    {
        height_ = height;
        updateTop();
        return *this;
    }
References height(), height_, RectangleExI(), and updateTop().
resizeWidthLeft()
RectangleExI & RectangleExI::resizeWidthLeft (int width) inline
Definition at line 436 of file raylibEx.h.
    {
        width_ = width;
        updateLeft();
        return *this;
    }
References RectangleExI(), updateLeft(), width(), and width_.
resizeWidthRight()
RectangleExI & RectangleExI::resizeWidthRight (int width) inline
Definition at line 429 of file raylibEx.h.
    {
        width_ = width;
        updateRight();
        return *this;
    }
References RectangleExI(), updateRight(), width(), and width_.
right()
int RectangleExI::right () const inline
Definition at line 367 of file raylibEx.h.
    {
        return right_;
    }
References right_.
Referenced by addRoom(), CheckCollisionPointRec(), offsetRight(), setRight(), and updateMapSize().
setBottom()
RectangleExI & RectangleExI::setBottom (int bottom) inline
Definition at line 410 of file raylibEx.h.
    {
        bottom_ = bottom;
        updateHeight();
        return *this;
    }
References bottom(), bottom_, RectangleExI(), and updateHeight().
setLeft()
RectangleExI & RectangleExI::setLeft (int left) inline
Definition at line 353 of file raylibEx.h.
    {
        left_ = left;
        updateWidth();
        return *this;
    }
References left(), left_, RectangleExI(), and updateWidth().
setRight()
RectangleExI & RectangleExI::setRight (int right) inline
Definition at line 372 of file raylibEx.h.
    {
        right_ = right;
        updateWidth();
        return *this;
    }
References RectangleExI(), right(), right_, and updateWidth().
setTop()
RectangleExI & RectangleExI::setTop (int top) inline
Definition at line 391 of file raylibEx.h.
    {
        top_ = top;
        updateHeight();
        return *this;
    }
References RectangleExI(), top(), top_, and updateHeight().
top()
int RectangleExI::top () const inline
Definition at line 386 of file raylibEx.h.
    {
        return top_;
    }
References top_.
Referenced by addRoom(), addTiles(), CheckCollisionPointRec(), offsetTop(), RectangleExI(), setTop(), and updateMapSize().
topLeft()
Vector2I RectangleExI::topLeft () const inline
Definition at line 462 of file raylibEx.h.
    {
        return Vector2I{
            left_,
            top_
        };
    }
References left_, and top_.
Referenced by RectangleExI().
updateBottom()
void RectangleExI::updateBottom () inline private
Definition at line 522 of file raylibEx.h.
    {
        bottom_ = top_ + height_ - 1;
    }
References bottom_, height_, and top_.
Referenced by resizeHeightBottom().
updateHeight()
void RectangleExI::updateHeight () inline private
Definition at line 502 of file raylibEx.h.
    {
        height_ = bottom_ - top_ + 1;
    }
References bottom_, height_, and top_.
Referenced by offsetBottom(), offsetTop(), setBottom(), setTop(), and validate().
updateLeft()
void RectangleExI::updateLeft () inline private
Definition at line 507 of file raylibEx.h.
    {
        left_ = right_ - width_ + 1;
    }
References left_, right_, and width_.
Referenced by resizeWidthLeft().
updateRight()
void RectangleExI::updateRight () inline private
Definition at line 517 of file raylibEx.h.
    {
        right_ = left_ + width_ - 1;
    }
References left_, right_, and width_.
Referenced by resizeWidthRight().
updateTop()
void RectangleExI::updateTop () inline private
Definition at line 512 of file raylibEx.h.
    {
        top_ = bottom_ - height_ + 1;
    }
References bottom_, height_, and top_.
Referenced by resizeHeightTop().
updateWidth()
void RectangleExI::updateWidth () inline private
Definition at line 497 of file raylibEx.h.
    {
        width_ = right_ - left_ + 1;
    }
References left_, right_, and width_.
Referenced by offsetLeft(), offsetRight(), setLeft(), setRight(), and validate().
validate()
void RectangleExI::validate () inline private
Definition at line 527 of file raylibEx.h.
    {
        if ( right_ < left_ )
        {
            int temp{ right_ };
            right_ = left_;
            left_ = temp;
            updateWidth();
        }
        if ( bottom_ < top_ )
        {
            int temp{ bottom_ };
            bottom_ = top_;
            top_ = temp;
            updateHeight();
        }
    }
References bottom_, left_, right_, top_, updateHeight(), and updateWidth().
Referenced by RectangleExI(), and RectangleExI().
width()
int RectangleExI::width () const inline
Definition at line 424 of file raylibEx.h.
    {
        return width_;
    }
References width_.
Referenced by addRoom(), addTiles(), RectangleExI(), RectangleExI(), resizeWidthLeft(), resizeWidthRight(), and VisibilitySystem::update().
Member Data Documentation
bottom_
int RectangleExI::bottom_ {} private
Definition at line 292 of file raylibEx.h.
{};
Referenced by bottom(), bottomRight(), offsetBottom(), RectangleExI(), RectangleExI(), setBottom(), updateBottom(), updateHeight(), updateTop(), and validate().
height_
int RectangleExI::height_ {} private
Definition at line 294 of file raylibEx.h.
{};
Referenced by center(), height(), rectangle(), RectangleExI(), RectangleExI(), resizeHeightBottom(), resizeHeightTop(), updateBottom(), updateHeight(), and updateTop().
left_
int RectangleExI::left_ {} private
Definition at line 289 of file raylibEx.h.
{};
Referenced by center(), left(), offsetLeft(), rectangle(), RectangleExI(), RectangleExI(), setLeft(), topLeft(), updateLeft(), updateRight(), updateWidth(), and validate().
right_
int RectangleExI::right_ {} private
Definition at line 291 of file raylibEx.h.
{};
Referenced by bottomRight(), offsetRight(), RectangleExI(), RectangleExI(), right(), setRight(), updateLeft(), updateRight(), updateWidth(), and validate().
top_
int RectangleExI::top_ {} private
Definition at line 290 of file raylibEx.h.
{};
Referenced by center(), offsetTop(), rectangle(), RectangleExI(), RectangleExI(), setTop(), top(), topLeft(), updateBottom(), updateHeight(), updateTop(), and validate().
width_
int RectangleExI::width_ {} private
Definition at line 293 of file raylibEx.h.
{};
Referenced by center(), rectangle(), RectangleExI(), RectangleExI(), resizeWidthLeft(), resizeWidthRight(), updateLeft(), updateRight(), updateWidth(), and width().
The documentation for this class was generated from the following file:
include/raylibEx.h