Roguelike: VisibilitySystem Namespace Reference
VisibilitySystem Namespace Reference
Functions
void update (snx::DenseMap< Vector2I, Fog > &fogs, snx::DenseMap< Vector2I, VisibilityId > &visibilityIds, std::unordered_set< Vector2I > const &isOpaques, RectangleExI const &viewportInTiles, int visionRange, Vector2I const &heroPosition)
void calculateVisibilitiesInOctant (snx::DenseMap< Vector2I, Fog > &fogs, int octant, snx::DenseMap< Vector2I, VisibilityId > &visibilityIds, std::unordered_set< Vector2I > const &isOpaques, Vector2I const &heroPosition, int visionRange, int range)
void updateShadowline (std::vector< Shadow > &shadowline, Vector2I const &octantPosition)
Function Documentation
calculateVisibilitiesInOctant()
void VisibilitySystem::calculateVisibilitiesInOctant (snx::DenseMap< Vector2I, Fog > & fogs, int octant, snx::DenseMap< Vector2I, VisibilityId > & visibilityIds, std::unordered_set< Vector2I > const & isOpaques, Vector2I const & heroPosition, int visionRange, int range)
Definition at line 415 of file VisibilitySystem.cpp.
{
    //* !!! Coordinates are usual cartesian !!!
    std::vector<Shadow> shadowline{};
#if defined(DEBUG) && defined(DEBUG_SHADOW)
    BeginDrawing();
#endif
    //* Iterate octant
    for ( int octY{ 0 }; octY < range; ++octY )
    {
        for ( int octX{ 0 }; octX <= octY + 1; ++octX )
        {
            Vector2I octantPosition{ octX, octY };
            Vector2I tilePosition{
                Convert::octantToTile(
                    octantPosition,
                    octant,
                    heroPosition
                )
            };
#if defined(DEBUG) && defined(DEBUG_SHADOW)
            snx::debug::cliLog(
                "octantPosition",
                octantPosition,
                ", TilePosition",
                tilePosition,
                "\n"
            );
#endif
            if ( !visibilityIds.contains( tilePosition ) )
            {
                continue;
            }
            VisibilityId tileVisibilityOld{ visibilityIds.at( tilePosition ) };
            //* < : Update only octant tiles including diagonal tiles (spare last row tile, needed for correct diagonal visibility)
            if ( octX <= octY )
            {
                //* Skip test (. set invis) if shadowline already covers whole octant
                if ( shadowline.size()
                     && ShadowModule::slopeLeft( shadowline[0] ) < 0
                     && ShadowModule::slopeRight( shadowline[0] ) < 1 )
                {
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                    snx::debug::cliLog(
                        "Shadow is max.",
                        "\n"
                    );
#endif
                    visibilityIds.at( tilePosition ) = updatedVisibility( tileVisibilityOld );
                    fogs[tilePosition] = updateFogOfWar( tileVisibilityOld );
                    continue;
                } //* Max shadow
                //* Check visibility by intersection with shadow line elements
                bool isVisible{ true };
                //* Check if tile is out of range (viewport and visionRange)
                if ( !(
                         ( octY < ( range - 1 ) )
                         && sqrt( pow( octX, 2 ) + pow( octY, 2 ) ) < visionRange
                     ) )
                {
                    isVisible = false;
                }
                else
                {
                    for ( Shadow const& shadow : shadowline )
                    {
                        //* Check if visible:
                        //* If top-left tile corner is left (<) from slopeLeft (at same height = tileTop)
                        //* OR
                        //* If slopeRight is left (<) from bottom-right tile corner (at same height = tileBottom)
                        [[maybe_unused]] auto test{ sqrt( pow( octX, 2 ) + pow( octY, 2 ) ) };
                        if ( ( ( octX - 0.5f ) < ( ShadowModule::getLeftAtTop(
                                   shadow,
                                   octantPosition
                               ) )
                               || ( ShadowModule::getRightAtBottom(
                                      shadow,
                                      octantPosition
                                  ) )
                                      < ( octX + 0.5f ) ) )
{
                            //* . visible (variable unchanged): top-left/bottom-right corner not in shadow
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                            snx::debug::cliLog(
                                "Tile is (partly) visible",
                                "\n"
                            );
#endif
                            continue;
                        }
                        isVisible = false;
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                        snx::debug::cliLog(
                            "Tile is invisible",
                            "\n"
                        );
#endif
                        break;
                    } //* Shadowline
                }
                //* Update visibility
                if ( isVisible )
                {
                    //* Tile IS visible
                    visibilityIds.at( tilePosition ) = VisibilityId::VISIBILE;
                }
                else
                {
                    visibilityIds.at( tilePosition ) = updatedVisibility( tileVisibilityOld );
                    fogs[tilePosition] = updateFogOfWar( tileVisibilityOld );
                }
            } //* Octant tiles only
            //* Update shadow line
            if ( !isOpaques.contains( tilePosition ) )
            {
                continue;
            }
#if defined(DEBUG) && defined(DEBUG_SHADOW)
            snx::debug::cliLog(
                "Tile is opaque, add shadow...",
                "\n"
            );
            drawShadow(
                Shadow{ octantPosition },
                octantPosition,
                octant,
                heroPosition,
                range
            );
#endif
            updateShadowline( shadowline, octantPosition );
        } //* Octant column
    } //* Octant row
#if defined(DEBUG) && defined(DEBUG_SHADOW)
    EndDrawing();
#endif
}
References snx::DenseMap< Key, Type >::at(), snx::debug::cliLog(), snx::DenseMap< Key, Type >::contains(), ShadowModule::getLeftAtTop(), ShadowModule::getRightAtBottom(), Convert::octantToTile(), ShadowModule::slopeLeft(), ShadowModule::slopeRight(), updatedVisibility(), updateFogOfWar(), updateShadowline(), and VISIBILE.
Referenced by update().
update()
void VisibilitySystem::update (snx::DenseMap< Vector2I, Fog > & fogs, snx::DenseMap< Vector2I, VisibilityId > & visibilityIds, std::unordered_set< Vector2I > const & isOpaques, RectangleExI const & viewportInTiles, int visionRange, Vector2I const & heroPosition)
Definition at line 584 of file VisibilitySystem.cpp.
{
    //* Input
    int quarterWidth{ 2 + ( viewportInTiles.width() / 2 ) };
    int quarterHeight{ 2 + ( viewportInTiles.height() / 2 ) };
    //* Init
    fogs.clear();
    visibilityIds.at( heroPosition ) = VisibilityId::VISIBILE;
    //* Iterate octants
    //* Orientation dependent range (horizontal, vertical)
    int range{};
    for ( int octant{ 0 }; octant < 8; ++octant )
    {
        //* Set range for octant
        //* viewport dependent:
        if ( ( ( octant + 1 ) / 2 ) % 2 ) //* := f tt ff tt f
        {
            range = quarterWidth;
        }
        else
        {
            range = quarterHeight;
        }
#if defined(DEBUG) && defined(DEBUG_SHADOW)
        snx::debug::cliPrint(
            "\nOctant: ",
            octant,
            "\n\n"
        );
#endif
        calculateVisibilitiesInOctant(
            fogs,
            octant,
            visibilityIds,
            isOpaques,
            heroPosition,
            visionRange,
            range
        );
    }
}
References snx::DenseMap< Key, Type >::at(), calculateVisibilitiesInOctant(), snx::DenseMap< Key, Type >::clear(), snx::debug::cliPrint(), RectangleExI::height(), VISIBILE, and RectangleExI::width().
Referenced by SceneModule::setupSceneEvents().
updateShadowline()
void VisibilitySystem::updateShadowline (std::vector< Shadow > & shadowline, Vector2I const & octantPosition)
Definition at line 195 of file VisibilitySystem.cpp.
{
    Shadow shadowNew{ octantPosition };
    float shadowNewLeftAtTop{ ShadowModule::getLeftAtTop(
        shadowNew,
        octantPosition
    ) };
    float shadowNewRightAtBottom{ ShadowModule::getRightAtBottom(
        shadowNew,
        octantPosition
    ) };
    int shadowContainingLeftEnd{ -1 };
    int shadowContainingRightEnd{ -1 };
    for ( size_t idx{ 0 }; idx < shadowline.size(); ++idx )
    {
#if defined(DEBUG) && defined(DEBUG_SHADOW)
        snx::debug::cliLog(
            "Compare new shadow(",
            shadowNew.slopeLeft(),
            ", ",
            shadowNew.slopeRight(),
            ") with old shadow[",
            i,
            "](",
            shadowline[i].slopeLeft(),
            ", ",
            shadowline[i].slopeRight(),
            "):\n"
        );
#endif
        //*           ||__old_
        //* -new--|
        if ( shadowNewRightAtBottom < ShadowModule::getLeftAtBottom( shadowline[idx], octantPosition ) )
        {
            //* New ends before current
            continue;
        }
        //* _old__||
        //*            |--new-
        if ( ShadowModule::getRightAtTop( shadowline[idx], octantPosition ) < shadowNewLeftAtTop )
        {
            //* Current ends before new
            continue;
        }
        //* ||__old_   _old__||
        //*  |--new-   -new--|
        if ( ShadowModule::getLeftAtTop( shadowline[idx], octantPosition ) <= shadowNewLeftAtTop
             && shadowNewRightAtBottom <= ShadowModule::getRightAtBottom( shadowline[idx], octantPosition ) )
        {
            //* Old contains new
            shadowContainingLeftEnd = idx;
            shadowContainingRightEnd = idx;
            break;
        }
        //*        ||__old_   _old__||
        //* |--new-   -new--|
        if ( shadowNewLeftAtTop < ShadowModule::getLeftAtTop( shadowline[idx], octantPosition )
             && ShadowModule::getLeftAtBottom( shadowline[idx], octantPosition ) <= shadowNewRightAtBottom
             && shadowNewRightAtBottom <= ShadowModule::getRightAtBottom( shadowline[idx], octantPosition ) )
        {
            //* Merge shadows if another shadow contains left end already
            if ( shadowContainingLeftEnd > -1 )
            {
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                snx::debug::cliLog( "Merge: Extend shadow[", i, "] to the right\n" );
#endif
                //* Adjust remaining
                ShadowModule::setSlopeRight(
                    shadowline[shadowContainingLeftEnd],
                    ShadowModule::slopeRight( shadowline[idx] )
                );
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                snx::debug::cliLog(
                    "New shadow is (",
                    shadowline[shadowContainingLeftEnd].slopeLeft(),
                    ", ",
                    shadowline[shadowContainingLeftEnd].slopeRight(),
                    ")\n"
                );
#endif
                //* Delete consumed
                shadowline.erase( shadowline.begin() + idx );
                break;
            }
            //* Extend old to left
#if defined(DEBUG) && defined(DEBUG_SHADOW)
            snx::debug::cliLog( "Extend left\n" );
#endif
            ShadowModule::setSlopeLeft(
                shadowline[idx],
                ShadowModule::slopeLeft( shadowNew )
            );
#if defined(DEBUG) && defined(DEBUG_SHADOW)
            snx::debug::cliLog(
                "New shadow is (",
                shadowline[i].slopeLeft(),
                ", ",
                shadowline[i].slopeRight(),
                ")\n"
            );
#endif
            shadowContainingRightEnd = idx;
        }
        //* ||__old_   _old__||
        //*          |--new-   -new--|
        if ( ShadowModule::getLeftAtTop( shadowline[idx], octantPosition ) <= shadowNewLeftAtTop
             && shadowNewLeftAtTop <= ShadowModule::getRightAtTop( shadowline[idx], octantPosition )
             && ShadowModule::getRightAtBottom( shadowline[idx], octantPosition ) < shadowNewRightAtBottom )
        {
            //* Merge shadows if another shadow contains right end already
            if ( shadowContainingRightEnd > -1 )
            {
                //* Adjust remaining
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                snx::debug::cliLog( "Merge: Extend shadow[", i, "] to the left\n" );
#endif
                ShadowModule::setSlopeLeft( shadowline[shadowContainingRightEnd], ShadowModule::slopeLeft( shadowline[idx] ) );
#if defined(DEBUG) && defined(DEBUG_SHADOW)
                snx::debug::cliLog(
                    "New shadow is (",
                    shadowline[shadowContainingLeftEnd].slopeLeft(),
                    ", ",
                    shadowline[shadowContainingLeftEnd].slopeRight(),
                    ")\n"
                );
#endif
                //* Delete consumed
                shadowline.erase( shadowline.begin() + idx );
                break;
            }
            //* Extend old to right
#if defined(DEBUG) && defined(DEBUG_SHADOW)
            snx::debug::cliLog( "Extend right\n" );
#endif
            ShadowModule::setSlopeRight(
                shadowline[idx],
                ShadowModule::slopeRight( shadowNew )
            );
#if defined(DEBUG) && defined(DEBUG_SHADOW)
            snx::debug::cliLog(
                "New shadow is (",
                shadowline[i].slopeLeft(),
                ", ",
                shadowline[i].slopeRight(),
                ")\n"
            );
#endif
            shadowContainingLeftEnd = idx;
        }
        //* Note: No case where new is covering old possible as shadows always get narrower the further from hero
    }
    //* If no intersection with new shadow
    if ( ( shadowContainingLeftEnd + shadowContainingRightEnd ) < -1 )
    {
        //* Add new shadow to shadow line
#if defined(DEBUG) && defined(DEBUG_SHADOW)
        snx::debug::cliLog( "Create new shadow\n" );
#endif
        shadowline.push_back( shadowNew );
    }
}
References snx::debug::cliLog(), ShadowModule::getLeftAtBottom(), ShadowModule::getLeftAtTop(), ShadowModule::getRightAtBottom(), ShadowModule::getRightAtTop(), ShadowModule::setSlopeLeft(), ShadowModule::setSlopeRight(), Shadow::slopeLeft, ShadowModule::slopeLeft(), Shadow::slopeRight, and ShadowModule::slopeRight().
Referenced by calculateVisibilitiesInOctant().