Roguelike: UserInputSystem Namespace Reference
UserInputSystem Namespace Reference
Functions
bool takeAction (InputActionId inputAction, Hero &hero, Cursor const &cursor, Map &map, GameCamera const &gameCamera)
Function Documentation
takeAction()
bool UserInputSystem::takeAction (InputActionId inputAction, Hero & hero, Cursor const & cursor, Map & map, GameCamera const & gameCamera)
Definition at line 89 of file UserInputSystem.cpp.
{
    bool isActionMultiFrame{ false };
    switch ( inputAction )
    {
        default:
        case InputActionId::NONE:
        {
            if ( !hero.movement.path.empty()
                 && !hero.transform.speed )
            {
                if ( !CollisionSystem::checkCollision(
                         map.tiles,
                         map.enemies,
                         hero.movement.path.rbegin()[1],
                         Convert::worldToTile( hero.position )
                     ) )
                {
                    MovementSystem::prepareFromExistingPath(
                        hero.movement,
                        hero.transform
                    );
                    isActionMultiFrame = true;
                }
                else
                {
                    MovementSystem::resetTransform( hero.transform );
                    hero.movement.path.clear();
                }
            }
            break;
        }
        case InputActionId::ACT_UP:
        {
            isActionMultiFrame = processDirectionalInput(
                hero,
                map,
                Directions::up
            );
            break;
        }
        case InputActionId::ACT_LEFT:
        {
            isActionMultiFrame = processDirectionalInput(
                hero,
                map,
                Directions::left
            );
            break;
        }
        case InputActionId::ACT_DOWN:
        {
            isActionMultiFrame = processDirectionalInput(
                hero,
                map,
                Directions::down
            );
            break;
        }
        case InputActionId::ACT_RIGHT:
        {
            isActionMultiFrame = processDirectionalInput(
                hero,
                map,
                Directions::right
            );
            break;
        }
        case InputActionId::MOVE_TO_TARGET:
        {
            std::vector<Vector2I> path{ PathfinderSystem::findPath(
                map,
                Convert::worldToTile( hero.position ),
                Convert::worldToTile( cursor.position ),
                gameCamera
            ) };
            if ( !path.empty() )
            {
                if ( map.enemies.ids.contains( path.rbegin()[1] ) )
                {
                    performAttack(
                        hero,
                        map.enemies,
                        path.rbegin()[1]
                    );
                    EnergyModule::consume( hero.energy );
                    path.clear();
                }
                else if ( !CollisionSystem::checkCollision(
                              map.tiles,
                              map.enemies,
                              path.rbegin()[1],
                              Convert::worldToTile( hero.position )
                          ) )
                {
                    MovementSystem::prepareByNewPath(
                        hero.movement,
                        path
                    );
                    MovementSystem::prepareFromExistingPath(
                        hero.movement,
                        hero.transform
                    );
                }
                else
                {
                    path.clear();
                }
            }
            isActionMultiFrame = !path.empty();
            break;
        }
        case InputActionId::ACT_IN_PLACE:
        {
            Vector2I heroTilePosition{ Convert::worldToTile( hero.position ) };
            //* Wait if nothing to interact
            if ( !map.objects.events.contains( heroTilePosition ) )
            {
                snx::Logger::log( "Hero waits..." );
                EnergyModule::consume( hero.energy );
                HealthModule::regenerate( hero.health );
                break;
            }
            snx::PublisherStatic::publish( map.objects.events.at( heroTilePosition ) );
            break;
        }
        case InputActionId::TOGGLE_CURSOR:
        {
            snx::PublisherStatic::publish( EventId::CURSOR_TOGGLE );
            break;
        }
    }
    inputAction = InputActionId::NONE;
    return isActionMultiFrame;
}
References ACT_DOWN, ACT_IN_PLACE, ACT_LEFT, ACT_RIGHT, ACT_UP, snx::DenseMap< Key, Type >::at(), CollisionSystem::checkCollision(), EnergyModule::consume(), snx::DenseMap< Key, Type >::contains(), CURSOR_TOGGLE, Directions::down, Map::enemies, Hero::energy, Objects::events, PathfinderSystem::findPath(), Hero::health, Enemies::ids, Directions::left, snx::Logger::log(), MOVE_TO_TARGET, Hero::movement, NONE, Map::objects, MovementComponent::path, performAttack(), Cursor::position, Hero::position, MovementSystem::prepareByNewPath(), MovementSystem::prepareFromExistingPath(), processDirectionalInput(), snx::PublisherStatic::publish(), HealthModule::regenerate(), MovementSystem::resetTransform(), Directions::right, TransformComponent::speed, Map::tiles, TOGGLE_CURSOR, Hero::transform, Directions::up, and Convert::worldToTile().
Referenced by GameModule::updateState().