Roguelike: TexturesModule Namespace Reference
TexturesModule Namespace Reference
Functions
void loadAtlas (Textures &textures, std::string const &filename)
void registerTexture (Textures &textures, RenderId textureId, Vector2 position)
Vector2 const & getTexturePosition (Textures const &textures, RenderId renderId)
void unloadAtlas (Textures &textures)
Function Documentation
getTexturePosition()
Vector2 const & TexturesModule::getTexturePosition (Textures const & textures, RenderId renderId)
Definition at line 27 of file Textures.cpp.
{
    return textures.textureIdToAtlasPosition.at( renderId );
}
References Textures::textureIdToAtlasPosition.
loadAtlas()
void TexturesModule::loadAtlas (Textures & textures, std::string const & filename)
Definition at line 9 of file Textures.cpp.
{
    TexturesModule::unloadAtlas( textures );
    textures.atlas = LoadTexture( ( TextureData::texturePath + filename ).c_str() );
}
References Textures::atlas, TextureData::texturePath, and unloadAtlas().
Referenced by RenderSystem::loadRenderData().
registerTexture()
void TexturesModule::registerTexture (Textures & textures, RenderId textureId, Vector2 position)
Definition at line 18 of file Textures.cpp.
{
    textures.textureIdToAtlasPosition.insert( { textureId, position } );
}
References Textures::textureIdToAtlasPosition.
Referenced by RenderSystem::loadRenderData().
unloadAtlas()
void TexturesModule::unloadAtlas (Textures & textures)
Definition at line 35 of file Textures.cpp.
{
    UnloadTexture( textures.atlas );
}
References Textures::atlas.
Referenced by RenderSystem::deinit(), and loadAtlas().