Roguelike: snx::IdManager Class Reference
snx::IdManager Class Reference
#include <IdManager.h>
Public Member Functions
size_t requestId ()
void suspendId (size_t id)
Private Member Functions
size_t recycledId ()
size_t incrementedId ()
Private Attributes
std::unordered_set< size_t > activeIds_ {}
std::unordered_set< size_t > freeIds_ {}
Detailed Description
Definition at line 11 of file IdManager.h.
Member Function Documentation
incrementedId()
size_t snx::IdManager::incrementedId () inline private
Definition at line 52 of file IdManager.h.
        {
            [[maybe_unused]] static size_t maxId = std::numeric_limits<size_t>::max();
            static size_t lastId{ 0 };
            //* START WITH ID = 1
            ++lastId;
            assert( lastId < maxId && "ID OVERFLOWING!" );
            activeIds_.insert( lastId );
            return lastId;
        }
References activeIds_.
Referenced by requestId().
recycledId()
size_t snx::IdManager::recycledId () inline private
Definition at line 40 of file IdManager.h.
        {
            size_t id{};
            auto freeIdsIterator{ freeIds_.begin() };
            id = *freeIdsIterator;
            activeIds_.insert( id );
            freeIds_.erase( freeIdsIterator );
            return id;
        }
References activeIds_, and freeIds_.
Referenced by requestId().
requestId()
size_t snx::IdManager::requestId () inline
Definition at line 17 of file IdManager.h.
        {
            if ( !freeIds_.empty() )
            {
                return recycledId();
            }
            return incrementedId();
        }
References freeIds_, incrementedId(), and recycledId().
Referenced by EnemiesModule::createAtPosition().
suspendId()
void snx::IdManager::suspendId (size_t id) inline
Definition at line 27 of file IdManager.h.
        {
            if ( activeIds_.count( id ) < 1 )
            {
                return;
            }
            auto usedIdsIterator{ activeIds_.find( id ) };
            freeIds_.insert( *usedIdsIterator );
            activeIds_.erase( usedIdsIterator );
        }
References activeIds_, and freeIds_.
Member Data Documentation
activeIds_
std::unordered_set<size_t> snx::IdManager::activeIds_ {} private
Definition at line 13 of file IdManager.h.
{};
Referenced by incrementedId(), recycledId(), and suspendId().
freeIds_
std::unordered_set<size_t> snx::IdManager::freeIds_ {} private
Definition at line 14 of file IdManager.h.
{};
Referenced by recycledId(), requestId(), and suspendId().
The documentation for this class was generated from the following file:
include/IdManager.h