Roguelike: RectangleEx Class Reference
RectangleEx Class Reference
#include <raylibEx.h>
Public Member Functions
RectangleEx ()=default
RectangleEx (float left, float top, float width=0, float height=0)
RectangleEx (Vector2 const &topLeft, Vector2 const &bottomRight={ 0, 0 })
RectangleEx (Vector2 const &center, float width, float height)
RectangleEx (Rectangle const &rectangle)
float left () const
RectangleEx & setLeft (float left)
RectangleEx & offsetLeft (float left)
float right () const
RectangleEx & setRight (float right)
RectangleEx & offsetRight (float right)
float top () const
RectangleEx & setTop (float top)
RectangleEx & offsetTop (float top)
float bottom () const
RectangleEx & setBottom (float bottom)
RectangleEx & offsetBottom (float bottom)
float width () const
RectangleEx & resizeWidthRight (float width)
RectangleEx & resizeWidthLeft (float width)
float height () const
RectangleEx & resizeHeightBottom (float height)
RectangleEx & resizeHeightTop (float height)
Vector2 topLeft () const
Vector2 bottomRight () const
Vector2 center () const
Rectangle rectangle () const
Private Member Functions
void updateWidth ()
void updateHeight ()
void updateLeft ()
void updateTop ()
void updateRight ()
void updateBottom ()
void validate ()
Private Attributes
float left_ {}
float top_ {}
float right_ {}
float bottom_ {}
float width_ {}
float height_ {}
Detailed Description
Definition at line 16 of file raylibEx.h.
Constructor & Destructor Documentation
RectangleEx() [1/5]
RectangleEx::RectangleEx () default
Referenced by offsetBottom(), offsetLeft(), offsetRight(), offsetTop(), resizeHeightBottom(), resizeHeightTop(), resizeWidthLeft(), resizeWidthRight(), setBottom(), setLeft(), setRight(), and setTop().
RectangleEx() [2/5]
RectangleEx::RectangleEx (float left, float top, float width = 0, float height = 0) inline
Definition at line 28 of file raylibEx.h.
        : left_( left )
        , top_( top )
        , right_( left + width )
        , bottom_( top + height )
        , width_( width )
        , height_( height )
    {
        validate();
    }
References bottom_, height(), height_, left(), left_, right_, top(), top_, validate(), width(), and width_.
RectangleEx() [3/5]
RectangleEx::RectangleEx (Vector2 const & topLeft, Vector2 const & bottomRight = { 0, 0 }) inline
Definition at line 44 of file raylibEx.h.
                                     { 0, 0 }
    )
        : left_( topLeft.x )
        , top_( topLeft.y )
        , right_( bottomRight.x )
        , bottom_( bottomRight.y )
        , width_( bottomRight.x - topLeft.x )
        , height_( bottomRight.y - topLeft.y )
    {
        validate();
    }
References bottomRight(), and topLeft().
RectangleEx() [4/5]
RectangleEx::RectangleEx (Vector2 const & center, float width, float height) inline
Definition at line 58 of file raylibEx.h.
        : left_( center.x - ( 0.5f * width ) )
        , top_( center.y - ( 0.5f * height ) )
        , right_( center.x + ( 0.5f * width ) )
        , bottom_( center.y + ( 0.5f * height ) )
        , width_( width )
        , height_( height )
    {
        validate();
    }
References bottom_, center(), height(), height_, left_, right_, top_, validate(), width(), and width_.
RectangleEx() [5/5]
RectangleEx::RectangleEx (Rectangle const & rectangle) inline explicit
Definition at line 73 of file raylibEx.h.
        : left_( rectangle.x )
        , top_( rectangle.y )
        , right_( rectangle.x + rectangle.width )
        , bottom_( rectangle.y + rectangle.height )
        , width_( rectangle.width )
        , height_( rectangle.height )
    {
        validate();
    }
References bottom_, height(), height_, left_, rectangle(), right_, top_, validate(), width(), and width_.
Member Function Documentation
bottom()
float RectangleEx::bottom () const inline
Definition at line 141 of file raylibEx.h.
    {
        return bottom_;
    }
References bottom_.
Referenced by CheckCollisionLineRec(), PanelSystem::drawLogPanelContent(), PanelSystem::init(), offsetBottom(), and setBottom().
bottomRight()
Vector2 RectangleEx::bottomRight () const inline
Definition at line 206 of file raylibEx.h.
    {
        return Vector2{
            right_,
            bottom_
        };
    }
References bottom_, and right_.
Referenced by CheckCollisionLineRec(), RectangleEx(), and GameCameraModule::viewportInTiles().
center()
Vector2 RectangleEx::center () const inline
Definition at line 214 of file raylibEx.h.
    {
        return Vector2{
            ( left_ + ( 0.5f * width_ ) ),
            ( top_ + ( 0.5f * height_ ) )
        };
    }
References height_, left_, top_, and width_.
Referenced by GameCameraModule::init(), and RectangleEx().
height()
float RectangleEx::height () const inline
Definition at line 179 of file raylibEx.h.
    {
        return height_;
    }
References height_.
Referenced by PanelSystem::drawLogPanelContent(), RectangleEx(), RectangleEx(), RectangleEx(), SceneModule::renderOutput(), resizeHeightBottom(), and resizeHeightTop().
left()
float RectangleEx::left () const inline
Definition at line 84 of file raylibEx.h.
    {
        return left_;
    }
References left_.
Referenced by CheckCollisionLineRec(), PanelSystem::drawLogPanelContent(), PanelSystem::init(), offsetLeft(), RectangleEx(), SceneModule::renderOutput(), and setLeft().
offsetBottom()
RectangleEx & RectangleEx::offsetBottom (float bottom) inline
Definition at line 153 of file raylibEx.h.
    {
        bottom_ += bottom;
        updateHeight();
        return *this;
    }
References bottom(), bottom_, RectangleEx(), and updateHeight().
offsetLeft()
RectangleEx & RectangleEx::offsetLeft (float left) inline
Definition at line 96 of file raylibEx.h.
    {
        left_ += left;
        updateWidth();
        return *this;
    }
References left(), left_, RectangleEx(), and updateWidth().
offsetRight()
RectangleEx & RectangleEx::offsetRight (float right) inline
Definition at line 115 of file raylibEx.h.
    {
        right_ += right;
        updateWidth();
        return *this;
    }
References RectangleEx(), right(), right_, and updateWidth().
offsetTop()
RectangleEx & RectangleEx::offsetTop (float top) inline
Definition at line 134 of file raylibEx.h.
    {
        top_ += top;
        updateHeight();
        return *this;
    }
References RectangleEx(), top(), top_, and updateHeight().
rectangle()
Rectangle RectangleEx::rectangle () const inline
Definition at line 222 of file raylibEx.h.
    {
        return Rectangle{
            left_,
            top_,
            width_,
            height_
        };
    }
References height_, left_, top_, and width_.
Referenced by CheckCollisionPointRec(), PanelSystem::drawPanelBorders(), and RectangleEx().
resizeHeightBottom()
RectangleEx & RectangleEx::resizeHeightBottom (float height) inline
Definition at line 184 of file raylibEx.h.
    {
        height_ = height;
        updateBottom();
        return *this;
    }
References height(), height_, RectangleEx(), and updateBottom().
resizeHeightTop()
RectangleEx & RectangleEx::resizeHeightTop (float height) inline
Definition at line 191 of file raylibEx.h.
    {
        height_ = height;
        updateTop();
        return *this;
    }
References height(), height_, RectangleEx(), and updateTop().
Referenced by PanelSystem::init().
resizeWidthLeft()
RectangleEx & RectangleEx::resizeWidthLeft (float width) inline
Definition at line 172 of file raylibEx.h.
    {
        width_ = width;
        updateLeft();
        return *this;
    }
References RectangleEx(), updateLeft(), width(), and width_.
Referenced by PanelSystem::init().
resizeWidthRight()
RectangleEx & RectangleEx::resizeWidthRight (float width) inline
Definition at line 165 of file raylibEx.h.
    {
        width_ = width;
        updateRight();
        return *this;
    }
References RectangleEx(), updateRight(), width(), and width_.
right()
float RectangleEx::right () const inline
Definition at line 103 of file raylibEx.h.
    {
        return right_;
    }
References right_.
Referenced by CheckCollisionLineRec(), offsetRight(), and setRight().
setBottom()
RectangleEx & RectangleEx::setBottom (float bottom) inline
Definition at line 146 of file raylibEx.h.
    {
        bottom_ = bottom;
        updateHeight();
        return *this;
    }
References bottom(), bottom_, RectangleEx(), and updateHeight().
Referenced by PanelSystem::init().
setLeft()
RectangleEx & RectangleEx::setLeft (float left) inline
Definition at line 89 of file raylibEx.h.
    {
        left_ = left;
        updateWidth();
        return *this;
    }
References left(), left_, RectangleEx(), and updateWidth().
setRight()
RectangleEx & RectangleEx::setRight (float right) inline
Definition at line 108 of file raylibEx.h.
    {
        right_ = right;
        updateWidth();
        return *this;
    }
References RectangleEx(), right(), right_, and updateWidth().
Referenced by PanelSystem::init().
setTop()
RectangleEx & RectangleEx::setTop (float top) inline
Definition at line 127 of file raylibEx.h.
    {
        top_ = top;
        updateHeight();
        return *this;
    }
References RectangleEx(), top(), top_, and updateHeight().
Referenced by PanelSystem::init().
top()
float RectangleEx::top () const inline
Definition at line 122 of file raylibEx.h.
    {
        return top_;
    }
References top_.
Referenced by CheckCollisionLineRec(), PanelSystem::init(), offsetTop(), RectangleEx(), SceneModule::renderOutput(), and setTop().
topLeft()
Vector2 RectangleEx::topLeft () const inline
Definition at line 198 of file raylibEx.h.
    {
        return Vector2{
            left_,
            top_
        };
    }
References left_, and top_.
Referenced by CheckCollisionLineRec(), RectangleEx(), and GameCameraModule::viewportInTiles().
updateBottom()
void RectangleEx::updateBottom () inline private
Definition at line 258 of file raylibEx.h.
    {
        bottom_ = top_ + height_;
    }
References bottom_, height_, and top_.
Referenced by resizeHeightBottom().
updateHeight()
void RectangleEx::updateHeight () inline private
Definition at line 238 of file raylibEx.h.
    {
        height_ = bottom_ - top_;
    }
References bottom_, height_, and top_.
Referenced by offsetBottom(), offsetTop(), setBottom(), and setTop().
updateLeft()
void RectangleEx::updateLeft () inline private
Definition at line 243 of file raylibEx.h.
    {
        left_ = right_ - width_;
    }
References left_, right_, and width_.
Referenced by resizeWidthLeft().
updateRight()
void RectangleEx::updateRight () inline private
Definition at line 253 of file raylibEx.h.
    {
        right_ = left_ + width_;
    }
References left_, right_, and width_.
Referenced by resizeWidthRight().
updateTop()
void RectangleEx::updateTop () inline private
Definition at line 248 of file raylibEx.h.
    {
        top_ = bottom_ - height_;
    }
References bottom_, height_, and top_.
Referenced by resizeHeightTop().
updateWidth()
void RectangleEx::updateWidth () inline private
Definition at line 233 of file raylibEx.h.
    {
        width_ = right_ - left_;
    }
References left_, right_, and width_.
Referenced by offsetLeft(), offsetRight(), setLeft(), and setRight().
validate()
void RectangleEx::validate () inline private
Definition at line 263 of file raylibEx.h.
    {
        if ( right_ < left_ )
        {
            float temp{ right_ };
            right_ = left_;
            left_ = temp;
        }
        if ( bottom_ < top_ )
        {
            float temp{ bottom_ };
            bottom_ = top_;
            top_ = temp;
        }
    }
References bottom_, left_, right_, and top_.
Referenced by RectangleEx(), RectangleEx(), and RectangleEx().
width()
float RectangleEx::width () const inline
Definition at line 160 of file raylibEx.h.
    {
        return width_;
    }
References width_.
Referenced by PanelSystem::drawGameInfoPanelContent(), RectangleEx(), RectangleEx(), RectangleEx(), SceneModule::renderOutput(), resizeWidthLeft(), and resizeWidthRight().
Member Data Documentation
bottom_
float RectangleEx::bottom_ {} private
Definition at line 21 of file raylibEx.h.
{};
Referenced by bottom(), bottomRight(), offsetBottom(), RectangleEx(), RectangleEx(), RectangleEx(), setBottom(), updateBottom(), updateHeight(), updateTop(), and validate().
height_
float RectangleEx::height_ {} private
Definition at line 23 of file raylibEx.h.
{};
Referenced by center(), height(), rectangle(), RectangleEx(), RectangleEx(), RectangleEx(), resizeHeightBottom(), resizeHeightTop(), updateBottom(), updateHeight(), and updateTop().
left_
float RectangleEx::left_ {} private
Definition at line 18 of file raylibEx.h.
{};
Referenced by center(), left(), offsetLeft(), rectangle(), RectangleEx(), RectangleEx(), RectangleEx(), setLeft(), topLeft(), updateLeft(), updateRight(), updateWidth(), and validate().
right_
float RectangleEx::right_ {} private
Definition at line 20 of file raylibEx.h.
{};
Referenced by bottomRight(), offsetRight(), RectangleEx(), RectangleEx(), RectangleEx(), right(), setRight(), updateLeft(), updateRight(), updateWidth(), and validate().
top_
float RectangleEx::top_ {} private
Definition at line 19 of file raylibEx.h.
{};
Referenced by center(), offsetTop(), rectangle(), RectangleEx(), RectangleEx(), RectangleEx(), setTop(), top(), topLeft(), updateBottom(), updateHeight(), updateTop(), and validate().
width_
float RectangleEx::width_ {} private
Definition at line 22 of file raylibEx.h.
{};
Referenced by center(), rectangle(), RectangleEx(), RectangleEx(), RectangleEx(), resizeWidthLeft(), resizeWidthRight(), updateLeft(), updateRight(), updateWidth(), and width().
The documentation for this class was generated from the following file:
include/raylibEx.h