Roguelike: ChunkSystem Namespace Reference
ChunkSystem Namespace Reference
Functions
void init (Textures const &textures, snx::DenseMap< Vector2I, Chunk > &chunks, snx::DenseMap< Vector2I, Vector2 > const &tilesPositions, snx::DenseMap< Vector2I, RenderId > const &tilesRenderIds)
Function Documentation
init()
void ChunkSystem::init (Textures const & textures, snx::DenseMap< Vector2I, Chunk > & chunks, snx::DenseMap< Vector2I, Vector2 > const & tilesPositions, snx::DenseMap< Vector2I, RenderId > const & tilesRenderIds)
Definition at line 33 of file ChunkSystem.cpp.
{
    //* Reset
    for ( Chunk const& chunk : chunks )
    {
        UnloadRenderTexture( chunk.renderTexture );
    }
    chunks.clear();
    //* Create necessary chunks
    for ( Vector2 const& position : tilesPositions )
    {
        verifyRequiredChunkExists(
            Convert::worldToTile( position ),
            chunks
        );
    }
    //* Render to chunk
    for ( Chunk& chunk : chunks )
    {
        RectangleExI const& chunkSize{ chunk.corners };
        BeginTextureMode( chunk.renderTexture );
        ClearBackground( Colors::bg );
        //* Iterate all tilePositions in chunk
        for ( int x{ chunkSize.left() - 1 }; x < ( chunkSize.right() + 2 ); ++x )
        {
            for ( int y{ chunkSize.top() - 1 }; y < ( chunkSize.bottom() + 2 ); ++y )
            {
                Vector2I tilePosition{ x, y };
                if ( !tilesRenderIds.contains( tilePosition ) )
                {
                    continue;
                }
                RenderSystem::renderToChunk(
                    textures,
                    tilesRenderIds.at( tilePosition ),
                    tilesPositions.at( tilePosition ),
                    chunk
                );
            }
        }
        EndTextureMode();
    }
}
References snx::DenseMap< Key, Type >::at(), Colors::bg, snx::DenseMap< Key, Type >::clear(), snx::DenseMap< Key, Type >::contains(), RenderSystem::renderToChunk(), verifyRequiredChunkExists(), and Convert::worldToTile().
Referenced by SceneModule::init(), and SceneModule::setupSceneEvents().