Roguelike: src/Game/Systems/PathfinderSystem.cpp File Reference
PathfinderSystem.cpp File Reference
#include "PathfinderSystem.h"
#include "Convert.h"
#include "GameCamera.h"
#include "Map.h"
#include "RNG.h"
#include "Tiles.h"
#include "VisibilityId.h"
#include "raylibEx.h"
#include <cstdlib>
#include <forward_list>
#include <map>
#include <raylib.h>
#include <raymath.h>
#include <unordered_set>
#include <vector>
Functions
bool checkRatingList (int currentRating, std::forward_list< RatedTile > &ratedTiles, std::map< int, std::vector< RatedTile * > > &ratingList, std::unordered_set< Vector2I > &tilesToIgnore, Map const &map, Vector2I const &target, GameCamera const &gameCamera, int maxRange, std::vector< Vector2I > &path)
Variables
int constexpr bias { 2 }
Function Documentation
checkRatingList()
bool checkRatingList (int currentRating, std::forward_list< RatedTile > & ratedTiles, std::map< int, std::vector< RatedTile * > > & ratingList, std::unordered_set< Vector2I > & tilesToIgnore, Map const & map, Vector2I const & target, GameCamera const & gameCamera, int maxRange, std::vector< Vector2I > & path)
Definition at line 68 of file PathfinderSystem.cpp.
{
    //* Buffer rated tiles to allow neighbours with same rating
    std::vector<RatedTile*> tileList{ ratingList[currentRating] };
    //* All tiles with same rating will be checked . remove key
    ratingList.erase( currentRating );
    //* Check all tiles in vector for current best rating before choosing new best rating
    for ( RatedTile* currentTile : tileList )
    {
        Vector2I distanceToTarget{ currentTile->distanceToTarget };
        Vector2I mainDirection{ Vector2MainDirection( distanceToTarget ) };
        Vector2I offDirection{ Vector2OffDirection( distanceToTarget ) };
        //* Handle exceptions
        //* Exception: |x| == |y| . main is RNG, off is dependent
        if ( abs( distanceToTarget.x ) == abs( distanceToTarget.y ) )
        {
            if ( snx::RNG::random() )
            {
                mainDirection = Vector2Normalize(
                    Vector2I{
                        distanceToTarget.x,
                        0
                    }
                );
                offDirection = Vector2Normalize(
                    Vector2I{
                        0,
                        distanceToTarget.y
                    }
                );
            }
            else
            {
                mainDirection = Vector2Normalize(
                    Vector2I{
                        0,
                        distanceToTarget.y
                    }
                );
                offDirection = Vector2Normalize(
                    Vector2I{
                        distanceToTarget.x,
                        0
                    }
                );
            }
        }
        //* Exception: offDirection == {0 , 0}
        if ( offDirection == Vector2I{ 0, 0 } )
        {
            if ( snx::RNG::random() )
            {
                offDirection = Vector2Swap( mainDirection );
            }
            else
            {
                offDirection = Vector2Negate( Vector2Swap( mainDirection ) );
            }
        }
        //* Test all four directions for currentTile, prioritise main direction to target
        for ( Vector2I const& direction : {
                  mainDirection,
                  offDirection,
                  Vector2Negate( offDirection ),
                  Vector2Negate( mainDirection )
              } )
        {
            //* Calculate new tilePosition
            Vector2I newTilePosition{
                Vector2Add(
                    direction,
                    currentTile->tilePosition
                )
            };
            //* Needs to be in map panel
            if ( !CheckCollisionPointRec(
                     Convert::tileToScreen(
                         newTilePosition,
                         gameCamera.camera
                     ),
                     *gameCamera.viewport
                 ) )
            {
                continue;
            }
            //* Ignore ancestor
            if ( currentTile->ancestor
                 && ( newTilePosition == currentTile->ancestor->tilePosition ) )
            {
                continue;
            }
            //* Add rating penalty if
            //* - Enemy is present
            int penalty{ 0 };
            if ( map.enemies.ids.contains( newTilePosition ) )
            {
                penalty += 4;
            }
            RatedTile newRatedTile{
                newTilePosition,
                target,
                currentTile->stepsNeeded + ( 1 + penalty ),
                currentTile
            };
            //* If Target found
            if ( ( newTilePosition == target ) )
            {
                RatedTileModule::reconstructPath(
                    newRatedTile,
                    path
                );
                return true;
            }
            //* Skip if is in tilesToIgnore
            if ( tilesToIgnore.contains( newTilePosition ) )
            {
                continue;
            }
            //* Skip if tile is invalid:
            //* - Not in map
            //* - Is invisible
            //* - Not accessible
            //* - Steps needed exceed maxRange
            if ( !map.tiles.visibilityIds.contains( newTilePosition )
                 || ( map.tiles.visibilityIds.at( newTilePosition ) == VisibilityId::INVISIBLE )
                 || map.tiles.isSolids.contains( newTilePosition )
                 || ( ( maxRange > 0 ) && ( newRatedTile.stepsNeeded > maxRange ) ) )
            {
                //* Invalid! Add to ignore set so it doesn't get checked again
                tilesToIgnore.insert( newTilePosition );
                continue;
            }
            //* Create new ratedTile in vector
            ratedTiles.push_front( newRatedTile );
            //* Add newRatedTile
            ratingList[RatedTileModule::getRating( newRatedTile )].push_back( &ratedTiles.front() );
            //* Valid! Add to ignore set so it doesn't get checked again
            tilesToIgnore.insert( newTilePosition );
#if defined(DEBUG) && defined(DEBUG_PATHFINDER)
            DrawText(
                std::format(
                    "{:.0f}",
                    newRatedTile.rating()
                )
                    .c_str(),
                Convert::tileToScreen(
                    newTilePosition,
                    snx::debug::gcam().camera()
                )
                        .x
                    + 10,
                Convert::tileToScreen(
                    newTilePosition,
                    snx::debug::gcam().camera()
                )
                        .y
                    + 10,
                10,
                WHITE
            );
#endif
        }
    }
    //* Check new best rated tiles
    if ( !ratingList.empty()
         && checkRatingList(
             ratingList.begin()->first,
             ratedTiles,
             ratingList,
             tilesToIgnore,
             map,
             target,
             gameCamera,
             maxRange,
             path
         ) )
    {
        return true;
    }
    return false;
}
References snx::DenseMap< Key, Type >::at(), GameCamera::camera, CheckCollisionPointRec(), checkRatingList(), snx::DenseMap< Key, Type >::contains(), Map::enemies, snx::debug::gcam(), RatedTileModule::getRating(), Enemies::ids, INVISIBLE, Tiles::isSolids, snx::RNG::random(), RatedTileModule::reconstructPath(), Map::tiles, Convert::tileToScreen(), Vector2Add(), Vector2MainDirection(), Vector2Negate(), Vector2Normalize(), Vector2OffDirection(), Vector2Swap(), GameCamera::viewport, and Tiles::visibilityIds.
Referenced by checkRatingList(), and PathfinderSystem::findPath().
Variable Documentation
bias
int constexpr bias { 2 } constexpr
Definition at line 31 of file PathfinderSystem.cpp.
{ 2 };
Referenced by RatedTileModule::getRating().