Roguelike: DamageModule Namespace Reference
DamageModule Namespace Reference
Functions
int damageRNG (DamageComponent const &damageComponent)
int damageAverage (DamageComponent const &damageComponent)
Function Documentation
damageAverage()
int DamageModule::damageAverage (DamageComponent const & damageComponent)
Definition at line 27 of file DamageComponent.cpp.
{
    return damageComponent.baseDamage + ( damageComponent.baseDamage * damageComponent.critChanceFactor * damageComponent.critDamageFactor );
}
References DamageComponent::baseDamage, DamageComponent::critChanceFactor, and DamageComponent::critDamageFactor.
damageRNG()
int DamageModule::damageRNG (DamageComponent const & damageComponent)
Definition at line 14 of file DamageComponent.cpp.
{
    int damage = damageComponent.baseDamage
                 + ( damageComponent.baseDamage
                     * ( snx::RNG::random( 0.0f, 100.0f )
                         < damageComponent.critChanceFactor )
                     * damageComponent.critDamageFactor );
    snx::Logger::logAppend( TextFormat( "%i damage", damage ) );
    return damage;
}
References DamageComponent::baseDamage, DamageComponent::critChanceFactor, DamageComponent::critDamageFactor, snx::Logger::logAppend(), and snx::RNG::random().
Referenced by DamageSystem::attack().