Roguelike: src/Game/Classes/Enemies.cpp File Reference
Enemies.cpp File Reference
#include "Enemies.h"
#include "AIComponent.h"
#include "Convert.h"
#include "DamageComponent.h"
#include "DenseMap.h"
#include "EnemyData.h"
#include "EnergyComponent.h"
#include "HealthComponent.h"
#include "IdManager.h"
#include "MovementComponent.h"
#include "MovementSystem.h"
#include "RNG.h"
#include "RenderId.h"
#include "Tiles.h"
#include "TransformComponent.h"
#include "VisibilityId.h"
#include "raylibEx.h"
#include <cstddef>
#include <vector>
Functions
bool isSpawnPositionValid (Tiles const &tiles, snx::DenseMap< Vector2I, size_t > const &enemiesIds, Vector2I const &tilePosition)
Vector2I getRandomPosition (Tiles const &tiles, snx::DenseMap< Vector2I, size_t > const &enemiesIds)
void insertSingle (Enemies &enemies, TransformComponent const &transform, MovementComponent const &movement, EnergyComponent const &energy, HealthComponent const &health, DamageComponent const &damage, Vector2I const &tilePosition, size_t enemyId, RenderId renderId, int scanRange)
Function Documentation
getRandomPosition()
Vector2I getRandomPosition (Tiles const & tiles, snx::DenseMap< Vector2I, size_t > const & enemiesIds)
Definition at line 44 of file Enemies.cpp.
{
    RectangleExI const& mapSize{ tiles.mapSize };
    Vector2I randomPosition{};
    while ( true )
    {
        randomPosition.x = snx::RNG::random(
            mapSize.left(),
            mapSize.right()
        );
        randomPosition.y = snx::RNG::random(
            mapSize.top(),
            mapSize.bottom()
        );
        if ( isSpawnPositionValid(
                 tiles,
                 enemiesIds,
                 randomPosition
             ) )
        {
            return randomPosition;
        };
    }
}
References isSpawnPositionValid(), Tiles::mapSize, and snx::RNG::random().
Referenced by EnemiesModule::createAtRandomPosition().
insertSingle()
void insertSingle (Enemies & enemies, TransformComponent const & transform, MovementComponent const & movement, EnergyComponent const & energy, HealthComponent const & health, DamageComponent const & damage, Vector2I const & tilePosition, size_t enemyId, RenderId renderId, int scanRange)
Definition at line 76 of file Enemies.cpp.
{
    enemies.ids.insert( tilePosition, enemyId );
    enemies.positions.insert( enemyId, Convert::tileToWorld( tilePosition ) );
    enemies.renderIds.insert( enemyId, renderId );
    enemies.transforms.insert( enemyId, transform );
    enemies.movements.insert( enemyId, movement );
    enemies.energies.insert( enemyId, energy );
    enemies.healths.insert( enemyId, health );
    enemies.damages.insert( enemyId, damage );
    enemies.ais.insert( enemyId, AIComponent{ scanRange } );
}
References Enemies::ais, Enemies::damages, Enemies::energies, Enemies::healths, Enemies::ids, snx::DenseMap< Key, Type >::insert(), Enemies::movements, Enemies::positions, Enemies::renderIds, Convert::tileToWorld(), and Enemies::transforms.
Referenced by EnemiesModule::createAtPosition().
isSpawnPositionValid()
bool isSpawnPositionValid (Tiles const & tiles, snx::DenseMap< Vector2I, size_t > const & enemiesIds, Vector2I const & tilePosition)
Definition at line 22 of file Enemies.cpp.
{
    //* Check if random position is
    //* - on map
    //* - not visible
    //* - not solid
    //* - not occupied by other enemy
    if ( tiles.positions.contains( tilePosition )
         && !( tiles.visibilityIds.at( tilePosition ) == VisibilityId::VISIBILE )
         && !tiles.isSolids.contains( tilePosition )
         && !enemiesIds.contains( tilePosition ) )
    {
        return true;
    }
    return false;
}
References snx::DenseMap< Key, Type >::at(), snx::DenseMap< Key, Type >::contains(), Tiles::isSolids, Tiles::positions, VISIBILE, and Tiles::visibilityIds.
Referenced by EnemiesModule::createAtPosition(), and getRandomPosition().