Roguelike: src/Game/Systems/CollisionSystem.cpp File Reference
CollisionSystem.cpp File Reference
#include "CollisionSystem.h"
#include "Convert.h"
#include "Enemies.h"
#include "Tiles.h"
#include "raylibEx.h"
Functions
bool checkCollisionWithNextPosition (Enemies const &enemies, Vector2I const &tilePositionToCheck)
Function Documentation
checkCollisionWithNextPosition()
bool checkCollisionWithNextPosition (Enemies const & enemies, Vector2I const & tilePositionToCheck)
Definition at line 8 of file CollisionSystem.cpp.
{
    for ( size_t idx{ 0 }; idx < enemies.transforms.size(); ++idx )
    {
        if ( Vector2Equals( tilePositionToCheck, Vector2Add( Convert::worldToTile( enemies.positions.values().at( idx ) ), enemies.transforms.values().at( idx ).direction ) ) )
        {
            return true;
        }
    }
    return false;
}
References Enemies::positions, snx::DenseMap< Key, Type >::size(), Enemies::transforms, snx::DenseMap< Key, Type >::values(), Vector2Add(), Vector2Equals(), and Convert::worldToTile().
Referenced by CollisionSystem::checkCollision().