Roguelike: snx::DenseMap< Key, Type > Class Template Reference
snx::DenseMap< Key, Type > Class Template Reference
#include <DenseMap.h>
Public Member Functions
auto begin () const
auto begin ()
auto end () const
auto end ()
size_t size () const
Type * assign (Key const &key, Type const &value=Type{})
Type const & insert (Key const &key, Type const &value=Type{})
Type const & insert_or_assign (Key const &key, Type const &value=Type{})
template<typename... Args>
Type const & emplace (Key const &key, Args &&... args)
template<typename... Args>
Type const & emplace_or_assign (Key const &key, Args &&... args)
void erase (Key const &key)
void changeKey (Key const &from, Key const &to)
void clear ()
Type const & at (Key const &key) const
Type & at (Key const &key)
Type & operator[] (Key const &key)
bool contains (Key const &key) const
Key const & key (size_t index) const
std::vector< Type > const & values () const
std::vector< Type > & values ()
void validate ()
Private Attributes
std::vector< Type > values_ {}
std::unordered_map< Key, size_t > keyToIndex_ {}
std::vector< Key > indexToKey_ {}
Detailed Description
template<typename Key, typename Type>
class snx::DenseMap< Key, Type >
Definition at line 13 of file DenseMap.h.
Member Function Documentation
assign()
template<typename Key, typename Type> Type * snx::DenseMap< Key, Type >::assign (Key const & key, Type const & value = Type{}) inline
Definition at line 45 of file DenseMap.h.
                                    {}
        )
        {
            if ( !keyToIndex_.contains( key ) )
            {
                return nullptr;
            }
            at( key ) = value;
            return &at( key );
        }
References key().
Referenced by emplace_or_assign().
at() [1/2]
template<typename Key, typename Type> Type & snx::DenseMap< Key, Type >::at (Key const & key) inline
Definition at line 205 of file DenseMap.h.
        {
            return const_cast<Type&>( std::as_const( *this ).at( key ) );
        }
References key().
at() [2/2]
template<typename Key, typename Type> Type const & snx::DenseMap< Key, Type >::at (Key const & key) const inline
Definition at line 199 of file DenseMap.h.
        {
            return values_.at( keyToIndex_.at( key ) );
        }
References key(), keyToIndex_, and values_.
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), checkRatingList(), PanelSystem::drawTileInfoPanelContent(), PathfinderSystem::findPath(), ChunkSystem::init(), isSpawnPositionValid(), operator[](), performAttack(), EnemiesModule::remove(), SceneModule::renderOutput(), SceneModule::setupSceneEvents(), UserInputSystem::takeAction(), and VisibilitySystem::update().
begin() [1/2]
template<typename Key, typename Type> auto snx::DenseMap< Key, Type >::begin () inline
Definition at line 22 of file DenseMap.h.
        {
            return values_.begin();
        }
References values_.
begin() [2/2]
template<typename Key, typename Type> auto snx::DenseMap< Key, Type >::begin () const inline
Definition at line 17 of file DenseMap.h.
        {
            return values_.begin();
        }
References values_.
changeKey()
template<typename Key, typename Type> void snx::DenseMap< Key, Type >::changeKey (Key const & from, Key const & to) inline
Definition at line 172 of file DenseMap.h.
        {
            assert( !contains( to ) && "Key already exists, possible loss of data!" );
            //* Add new key with old index
            keyToIndex_[to] = keyToIndex_.at( from );
            //* Remove old key
            keyToIndex_.erase( from );
            //* Remap index to new key
            indexToKey_[keyToIndex_.at( to )] = to;
        }
References contains(), indexToKey_, and keyToIndex_.
Referenced by EnemiesModule::update(), and MovementSystem::updateEnemies().
clear()
template<typename Key, typename Type> void snx::DenseMap< Key, Type >::clear () inline
Definition at line 190 of file DenseMap.h.
        {
            values_.clear();
            keyToIndex_.clear();
            indexToKey_.clear();
        }
References indexToKey_, keyToIndex_, and values_.
Referenced by ChunkSystem::init(), and VisibilitySystem::update().
contains()
template<typename Key, typename Type> bool snx::DenseMap< Key, Type >::contains (Key const & key) const inline
Definition at line 221 of file DenseMap.h.
        {
            return keyToIndex_.contains( key );
        }
References key(), and keyToIndex_.
Referenced by VisibilitySystem::calculateVisibilitiesInOctant(), changeKey(), CollisionSystem::checkCollision(), checkRatingList(), PanelSystem::drawTileInfoPanelContent(), PathfinderSystem::findPath(), ChunkSystem::init(), isSpawnPositionValid(), operator[](), processDirectionalInput(), SceneModule::setupSceneEvents(), UserInputSystem::takeAction(), and verifyRequiredChunkExists().
emplace()
template<typename Key, typename Type> template<typename... Args> Type const & snx::DenseMap< Key, Type >::emplace (Key const & key, Args &&... args) inline
Definition at line 101 of file DenseMap.h.
        {
            Type value{ std::forward<Args>( args )... };
            return insert( key, value );
        }
References insert(), and key().
Referenced by verifyRequiredChunkExists().
emplace_or_assign()
template<typename Key, typename Type> template<typename... Args> Type const & snx::DenseMap< Key, Type >::emplace_or_assign (Key const & key, Args &&... args) inline
Definition at line 112 of file DenseMap.h.
        {
            Type value{ std::forward<Args>( args )... };
            if ( !keyToIndex_.contains( key ) )
            {
                return insert( key, value );
            }
            return *assign( key, value );
        }
References assign(), insert(), key(), and keyToIndex_.
end() [1/2]
template<typename Key, typename Type> auto snx::DenseMap< Key, Type >::end () inline
Definition at line 32 of file DenseMap.h.
        {
            return values_.end();
        }
References values_.
end() [2/2]
template<typename Key, typename Type> auto snx::DenseMap< Key, Type >::end () const inline
Definition at line 27 of file DenseMap.h.
        {
            return values_.end();
        }
References values_.
erase()
template<typename Key, typename Type> void snx::DenseMap< Key, Type >::erase (Key const & key) inline
Definition at line 128 of file DenseMap.h.
        {
            if ( !keyToIndex_.contains( key ) )
            {
                return;
            }
            //* Get list index of removed value
            size_t removedValueIndex{ keyToIndex_[key] };
            size_t keptValueIndex{};
            size_t size{ this->size() };
            //* Replace removed value with last value before popping (if more than one value exists) to keep values contiguous
            if ( size > 1 )
            {
                //* Get index of (kept) last value that replaces removed value
                keptValueIndex = size - 1;
                //* Get key of replacing/kept value
                Key keptkey = indexToKey_[keptValueIndex];
                //* Replace (removed) value with kept value (by index) so last entry (duplicate) can be popped (becomes new removed)
                values_[removedValueIndex] = values_[keptValueIndex];
                //* Update value index after replacement
                keptValueIndex = removedValueIndex;
                //* Update key to valueIndex mapping for kept key
                keyToIndex_[keptkey] = keptValueIndex;
                //* Update index to key mapping for kept key
                indexToKey_[keptValueIndex] = keptkey;
            }
            //* Remove removed key from mapping
            keyToIndex_.erase( key );
            //* Remove (duplicate) last value
            values_.pop_back();
            //* Remove removed value from mapping
            indexToKey_.pop_back();
        }
References indexToKey_, key(), keyToIndex_, size(), and values_.
Referenced by EnemiesModule::remove().
insert()
template<typename Key, typename Type> Type const & snx::DenseMap< Key, Type >::insert (Key const & key, Type const & value = Type{}) inline
Definition at line 60 of file DenseMap.h.
                                    {}
        )
        {
            if ( keyToIndex_.contains( key ) )
            {
                return at( key );
            }
            //* Get new list index for value before modifying values_
            size_t valueIndex = size();
            //* Add key to valueIndex mapping
            keyToIndex_.insert( { key, valueIndex } );
            //* Add valueIndex to key mapping (internal use only to keep list contiguous)
            indexToKey_.push_back( key );
            //* Add new value to list
            values_.push_back( value );
            assert( ( keyToIndex_.size() == indexToKey_.size() ) && "Internal mismatch!" );
            return at( key );
        }
References key().
Referenced by emplace(), emplace_or_assign(), insertSingle(), and operator[]().
insert_or_assign()
template<typename Key, typename Type> Type const & snx::DenseMap< Key, Type >::insert_or_assign (Key const & key, Type const & value = Type{}) inline
Definition at line 87 of file DenseMap.h.
                                    {}
        )
        {
            if ( !keyToIndex_.contains( key ) )
            {
                return insert( key, value );
            }
            return *assign( key, value );
        }
References key().
key()
template<typename Key, typename Type> Key const & snx::DenseMap< Key, Type >::key (size_t index) const inline
Definition at line 227 of file DenseMap.h.
        {
            return indexToKey_.at( index );
        }
References indexToKey_.
Referenced by assign(), at(), at(), contains(), emplace(), emplace_or_assign(), erase(), EnemiesModule::getActive(), insert(), insert_or_assign(), operator[](), and SceneModule::renderOutput().
operator[]()
template<typename Key, typename Type> Type & snx::DenseMap< Key, Type >::operator[] (Key const & key) inline
Definition at line 211 of file DenseMap.h.
        {
            if ( !contains( key ) )
            {
                insert( key );
            }
            return at( key );
        }
References at(), contains(), insert(), and key().
size()
template<typename Key, typename Type> size_t snx::DenseMap< Key, Type >::size () const inline
Definition at line 39 of file DenseMap.h.
        {
            return values_.size();
        }
References values_.
Referenced by checkCollisionWithNextPosition(), erase(), EnemiesModule::fillEnemies(), EnemiesModule::getActive(), SceneModule::renderOutput(), EnemiesModule::update(), and MovementSystem::updateEnemies().
validate()
template<typename Key, typename Type> void snx::DenseMap< Key, Type >::validate () inline
Definition at line 244 of file DenseMap.h.
        {
        }
values() [1/2]
template<typename Key, typename Type> std::vector< Type > & snx::DenseMap< Key, Type >::values () inline
Definition at line 239 of file DenseMap.h.
        {
            return const_cast<std::vector<Type>&>( std::as_const( *this ).values() );
        }
values() [2/2]
template<typename Key, typename Type> std::vector< Type > const & snx::DenseMap< Key, Type >::values () const inline
Definition at line 233 of file DenseMap.h.
        {
            return values_;
        }
References values_.
Referenced by checkCollisionWithNextPosition(), EnemiesModule::getActive(), SceneModule::renderOutput(), EnemiesModule::replaceDead(), EnemiesModule::update(), and MovementSystem::updateEnemies().
Member Data Documentation
indexToKey_
template<typename Key, typename Type> std::vector<Key> snx::DenseMap< Key, Type >::indexToKey_ {} private
Definition at line 256 of file DenseMap.h.
{};
Referenced by changeKey(), clear(), erase(), and key().
keyToIndex_
template<typename Key, typename Type> std::unordered_map<Key, size_t> snx::DenseMap< Key, Type >::keyToIndex_ {} private
Definition at line 253 of file DenseMap.h.
{};
Referenced by at(), changeKey(), clear(), contains(), emplace_or_assign(), and erase().
values_
template<typename Key, typename Type> std::vector<Type> snx::DenseMap< Key, Type >::values_ {} private
Definition at line 250 of file DenseMap.h.
{};
Referenced by at(), begin(), begin(), clear(), end(), end(), erase(), size(), and values().
The documentation for this class was generated from the following file:
include/DenseMap.h