#ifndef IG20240315181752
#define IG20240315181752

enum class EventId
{
    NONE = 0,
    //* Application interaction
    WINDOW_RESIZED,
    PANELS_RESIZED,
    CAMERA_CHANGED,
    CURSOR_TOGGLE,
    CURSOR_POSITION_CHANGED,
    MAP_CHANGE,
    CHANGE_COLOR_THEME,
    //* Game events
    MULTIFRAME_ACTION_DONE,
    MULTIFRAME_ACTION_ACTIVE,
    HERO_MOVED,
    HERO_POSITION_CHANGED,
    NEXT_LEVEL,
    PREVIOUS_LEVEL,
    INTERRUPT_MOVEMENT,
};

#endif
