Roguelike: snx::RNG Class Reference
snx::RNG Class Reference
#include <RNG.h>
Static Public Member Functions
static void seed (int seed)
static int random (int min=0, int max=1)
Static Private Attributes
static std::random_device rd_ {}
static std::seed_seq ss_
static std::mt19937 rng_ { ss_ }
Detailed Description
Definition at line 8 of file RNG.h.
Member Function Documentation
random()
static int snx::RNG::random (int min = 0, int max = 1) inline static
Definition at line 33 of file RNG.h.
        {
            std::uniform_int_distribution<int> distribution{ min, max };
            return distribution( rng_ );
        }
References rng_.
Referenced by checkRatingList(), createGridRooms(), DamageModule::damageRNG(), and getRandomPosition().
seed()
static void snx::RNG::seed (int seed) inline static
Definition at line 27 of file RNG.h.
        {
            rng_.seed( seed );
        }
References rng_, and seed().
Referenced by GameModule::init(), and seed().
Member Data Documentation
rd_
std::random_device snx::RNG::rd_ {} inline static private
Definition at line 10 of file RNG.h.
{};
rng_
std::mt19937 snx::RNG::rng_ { ss_ } inline static private
Definition at line 24 of file RNG.h.
{ ss_ };
Referenced by random(), and seed().
ss_
std::seed_seq snx::RNG::ss_ inline static private
Initial value:
{
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_()
        }
Definition at line 13 of file RNG.h.
{
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_(),
            rd_()
        };
The documentation for this class was generated from the following file:
include/RNG.h