Roguelike: AISystem Namespace Reference
AISystem Namespace Reference
Functions
bool takeActions (World &world, Hero &hero, size_t &activeEnemyId, GameCamera const &gameCamera, int turn)
bool takeAction (AIComponent const &ai, Vector2 &position, MovementComponent &movement, TransformComponent &transform, EnergyComponent &energy, DamageComponent &damage, Map const &map, Vector2I const &heroPosition, HealthComponent &heroHealth, GameCamera const &gameCamera)
Function Documentation
takeAction()
bool AISystem::takeAction (AIComponent const & ai, Vector2 & position, MovementComponent & movement, TransformComponent & transform, EnergyComponent & energy, DamageComponent & damage, Map const & map, Vector2I const & heroPosition, HealthComponent & heroHealth, GameCamera const & gameCamera)
Definition at line 61 of file AISystem.cpp.
{
    bool isActionMultiFrame{ false };
    //* Instant action: attack
    if ( Vector2Length(
             Vector2Subtract(
                 Convert::worldToTile( position ),
                 heroPosition
             )
         )
         == 1 )
    {
        //* Attack
        snx::Logger::log( "Hero takes " );
        DamageSystem::attack(
            damage,
            heroHealth
        );
        EnergyModule::consume( energy );
    }
    //* Check path
    else
    {
        std::vector<Vector2I> path{ PathfinderSystem::findPath(
            map,
            Convert::worldToTile( position ),
            heroPosition,
            gameCamera,
            false,
            ai.scanRange
        ) };
        size_t pathSize{ path.size() };
        //* Path is valid: has at least 2 entries (start and target) -> Multi-frame action: move
        //* TODO: Check all enemies->next position to avoid two enemies moving to the same spot
        if ( pathSize > 2
             && !CollisionSystem::checkCollision(
                 map.tiles,
                 map.enemies,
                 path.rbegin()[1],
                 heroPosition
             ) )
        {
            //* Prepare multi-frame action
            MovementSystem::prepareByFromTo(
                movement,
                transform,
                Convert::worldToTile( position ),
                path.rbegin()[1]
            );
            EnergyModule::consume( energy );
            isActionMultiFrame = true;
        }
        //* Path is empty -> Instant action: wait
        else
        {
            //* Wait
            EnergyModule::consume( energy );
        }
    }
    // return false;
    return isActionMultiFrame;
}
References DamageSystem::attack(), CollisionSystem::checkCollision(), EnergyModule::consume(), Map::enemies, PathfinderSystem::findPath(), snx::Logger::log(), MovementSystem::prepareByFromTo(), AIComponent::scanRange, Map::tiles, Vector2Length(), Vector2Subtract(), and Convert::worldToTile().
Referenced by takeActions().
takeActions()
bool AISystem::takeActions (World & world, Hero & hero, size_t & activeEnemyId, GameCamera const & gameCamera, int turn)
Definition at line 19 of file AISystem.cpp.
{
    bool multiFrameActionActive{ false };
    Enemies& enemies{ world.currentMap->enemies };
    do
    {
        activeEnemyId = EnemiesModule::getActive(
            enemies.energies,
            enemies.ais,
            turn
        );
        if ( activeEnemyId )
        {
            enemies.ais[activeEnemyId].turn = turn;
            multiFrameActionActive |= AISystem::takeAction(
                enemies.ais.at( activeEnemyId ),
                enemies.positions.at( activeEnemyId ),
                enemies.movements.at( activeEnemyId ),
                enemies.transforms.at( activeEnemyId ),
                enemies.energies.at( activeEnemyId ),
                enemies.damages.at( activeEnemyId ),
                *world.currentMap,
                Convert::worldToTile( hero.position ),
                hero.health,
                gameCamera
            );
        }
    } while ( activeEnemyId );
    return multiFrameActionActive;
}
References World::currentMap, Map::enemies, EnemiesModule::getActive(), Hero::health, Hero::position, takeAction(), and Convert::worldToTile().
Referenced by GameModule::updateState().