Roguelike: snx::SparseSet< Type > Class Template Reference
snx::SparseSet< Type > Class Template Reference
#include <SparseSet.h>
Public Member Functions
auto begin () const
auto begin ()
auto end () const
auto end ()
size_t size () const
Type * assign (size_t key, Type const &value=Type{})
Type const & insert (size_t key, Type const &value=Type{})
Type const & insert (Type const &value=Type{})
Type const & insert_or_assign (size_t key, Type const &value=Type{})
template<typename... Args>
Type const & emplace (size_t key, Args &&... args)
template<typename... Args>
Type const & emplace_or_assign (size_t key, Args &&... args)
void erase (size_t keyToRemove)
void clear ()
Type const & at (size_t key) const
Type & at (size_t key)
Type & operator[] (size_t key)
bool contains (size_t key) const
size_t find (Type const &value) const
size_t key (size_t index) const
std::vector< Type > const & values () const
std::vector< Type > & values ()
std::vector< size_t > const & keys () const
Private Attributes
std::vector< Type > values_ { Type{} }
std::vector< size_t > keyToIndex_ {}
std::vector< size_t > indexToKey_ { 0 }
Detailed Description
template<typename Type>
class snx::SparseSet< Type >
Definition at line 12 of file SparseSet.h.
Member Function Documentation
assign()
template<typename Type> Type * snx::SparseSet< Type >::assign (size_t key, Type const & value = Type{}) inline
Definition at line 44 of file SparseSet.h.
                                    {}
        )
        {
            if ( keyToIndex_.size() <= key
                 || !keyToIndex_.at( key ) )
            {
                return nullptr;
            }
            at( key ) = value;
            return &at( key );
        }
References key().
Referenced by emplace_or_assign().
at() [1/2]
template<typename Type> Type & snx::SparseSet< Type >::at (size_t key) inline
Definition at line 203 of file SparseSet.h.
        {
            return const_cast<Type&>( std::as_const( *this ).at( key ) );
        }
References key().
at() [2/2]
template<typename Type> Type const & snx::SparseSet< Type >::at (size_t key) const inline
Definition at line 197 of file SparseSet.h.
        {
            return values_.at( keyToIndex_.at( key ) );
        }
References key(), keyToIndex_, and values_.
Referenced by operator[]().
begin() [1/2]
template<typename Type> auto snx::SparseSet< Type >::begin () inline
Definition at line 21 of file SparseSet.h.
        {
            return values_.begin();
        }
References values_.
begin() [2/2]
template<typename Type> auto snx::SparseSet< Type >::begin () const inline
Definition at line 16 of file SparseSet.h.
        {
            return values_.begin();
        }
References values_.
clear()
template<typename Type> void snx::SparseSet< Type >::clear () inline
Definition at line 188 of file SparseSet.h.
        {
            values_.clear();
            keyToIndex_.clear();
            indexToKey_.clear();
        }
References indexToKey_, keyToIndex_, and values_.
contains()
template<typename Type> bool snx::SparseSet< Type >::contains (size_t key) const inline
Definition at line 219 of file SparseSet.h.
        {
            if ( keyToIndex_.size() <= key )
            {
                return false;
            }
            return keyToIndex_[key];
        }
References key(), and keyToIndex_.
Referenced by emplace_or_assign(), erase(), and operator[]().
emplace()
template<typename Type> template<typename... Args> Type const & snx::SparseSet< Type >::emplace (size_t key, Args &&... args) inline
Definition at line 116 of file SparseSet.h.
        {
            Type value{ std::forward<Args>( args )... };
            return insert( key, value );
        }
References insert(), and key().
emplace_or_assign()
template<typename Type> template<typename... Args> Type const & snx::SparseSet< Type >::emplace_or_assign (size_t key, Args &&... args) inline
Definition at line 127 of file SparseSet.h.
        {
            Type value{ std::forward<Args>( args )... };
            // if ( keyToIndex_.size() <= key
            //      || !keyToIndex_.at( key ) )
            if ( !contains( key ) )
            {
                return insert( key, value );
            }
            return *assign( key, value );
        }
References assign(), contains(), insert(), and key().
end() [1/2]
template<typename Type> auto snx::SparseSet< Type >::end () inline
Definition at line 31 of file SparseSet.h.
        {
            return values_.end();
        }
References values_.
end() [2/2]
template<typename Type> auto snx::SparseSet< Type >::end () const inline
Definition at line 26 of file SparseSet.h.
        {
            return values_.end();
        }
References values_.
erase()
template<typename Type> void snx::SparseSet< Type >::erase (size_t keyToRemove) inline
Definition at line 145 of file SparseSet.h.
        {
            // if ( keyToRemove > ( keyToIndex_.size() - 1 )
            if ( !contains( keyToRemove ) )
            {
                return;
            }
            size_t size{ this->size() };
            //* Replace removed value with last value before popping (if more than one value exists) to keep values contiguous without rearranging the whole vector
            if ( size > 1 )
            {
                //* Get list index of removed value
                size_t replacedIndex{ keyToIndex_[keyToRemove] };
                //* Get index of (kept) last value that replaces removed value
                size_t keptIndex{ size - 1 };
                //* Get key of replacing/kept value
                size_t keptkey = indexToKey_[keptIndex];
                //* Replace (removed) value with kept value (by index) so last entry (duplicate) can be popped
                values_[replacedIndex] = values_[keptIndex];
                //* Update key to valueIndex mapping for kept key
                keyToIndex_[keptkey] = replacedIndex;
                //* Update index to key mapping for kept key
                indexToKey_[replacedIndex] = keptkey;
            }
            //* Reset removed key in mapping
            keyToIndex_[keyToRemove] = 0;
            //* Remove (duplicate) last value
            values_.pop_back();
            //* Remove removed value from mapping
            indexToKey_.pop_back();
        }
References contains(), indexToKey_, keyToIndex_, size(), and values_.
find()
template<typename Type> size_t snx::SparseSet< Type >::find (Type const & value) const inline
Definition at line 229 of file SparseSet.h.
        {
            for ( size_t idx{ 0 }; idx < values_.size(); ++idx )
            {
                if ( value == values_.at( idx ) )
                {
                    return indexToKey_[idx];
                }
            }
            return 0;
        }
References indexToKey_, and values_.
insert() [1/2]
template<typename Type> Type const & snx::SparseSet< Type >::insert (size_t key, Type const & value = Type{}) inline
Definition at line 60 of file SparseSet.h.
                                    {}
        )
        {
            // if ( keyToIndex_.size() > key
            //      && keyToIndex_.at( key ) )
            if ( contains( key ) )
            {
                return at( key );
            }
            //* Get new list index for value before modifying values_
            size_t valueIndex = values_.size();
            //* Check size
            keyToIndex_.resize( key + 1, 0 );
            //* Add key to valueIndex mapping
            keyToIndex_[key] = valueIndex;
            //* Add valueIndex to key mapping (internal use only to keep list contiguous)
            indexToKey_.push_back( key );
            //* Add new value to list
            values_.push_back( value );
            return at( key );
        }
References key().
Referenced by emplace(), emplace_or_assign(), and operator[]().
insert() [2/2]
template<typename Type> Type const & snx::SparseSet< Type >::insert (Type const & value = Type{}) inline
Definition at line 90 of file SparseSet.h.
                                    {}
        )
        {
            return insert(
                indexToKey_,
                value
            );
        }
insert_or_assign()
template<typename Type> Type const & snx::SparseSet< Type >::insert_or_assign (size_t key, Type const & value = Type{}) inline
Definition at line 100 of file SparseSet.h.
                                    {}
        )
        {
            // if ( keyToIndex_.size() <= key
            //      || !keyToIndex_.at( key ) )
            if ( !contains( key ) )
            {
                return insert( key, value );
            }
            return *assign( key, value );
        }
References key().
key()
template<typename Type> size_t snx::SparseSet< Type >::key (size_t index) const inline
Definition at line 243 of file SparseSet.h.
        {
            return indexToKey_.at( index );
        }
References indexToKey_.
Referenced by assign(), at(), at(), contains(), emplace(), emplace_or_assign(), insert(), insert_or_assign(), and operator[]().
keys()
template<typename Type> std::vector< size_t > const & snx::SparseSet< Type >::keys () const inline
Definition at line 260 of file SparseSet.h.
        {
            return indexToKey_;
        }
References indexToKey_.
operator[]()
template<typename Type> Type & snx::SparseSet< Type >::operator[] (size_t key) inline
Definition at line 209 of file SparseSet.h.
        {
            if ( !contains( key ) )
            {
                insert( key );
            }
            return at( key );
        }
References at(), contains(), insert(), and key().
size()
template<typename Type> size_t snx::SparseSet< Type >::size () const inline
Definition at line 38 of file SparseSet.h.
        {
            return values_.size();
        }
References values_.
Referenced by erase().
values() [1/2]
template<typename Type> std::vector< Type > & snx::SparseSet< Type >::values () inline
Definition at line 255 of file SparseSet.h.
        {
            return const_cast<std::vector<Type>&>( std::as_const( *this ).values() );
        }
values() [2/2]
template<typename Type> std::vector< Type > const & snx::SparseSet< Type >::values () const inline
Definition at line 249 of file SparseSet.h.
        {
            return values_;
        }
References values_.
Member Data Documentation
indexToKey_
template<typename Type> std::vector<size_t> snx::SparseSet< Type >::indexToKey_ { 0 } private
Definition at line 273 of file SparseSet.h.
{ 0 };
Referenced by clear(), erase(), find(), key(), and keys().
keyToIndex_
template<typename Type> std::vector<size_t> snx::SparseSet< Type >::keyToIndex_ {} private
Definition at line 270 of file SparseSet.h.
{};
Referenced by at(), clear(), contains(), and erase().
values_
template<typename Type> std::vector<Type> snx::SparseSet< Type >::values_ { Type{} } private
Definition at line 267 of file SparseSet.h.
{ Type{} };
Referenced by at(), begin(), begin(), clear(), end(), end(), erase(), find(), size(), and values().
The documentation for this class was generated from the following file:
include/SparseSet.h