Roguelike: GameFont Class Reference
GameFont Class Reference
#include <GameFont.h>
Static Public Member Functions
static void load ()
static void unload ()
static Font const & font ()
Static Public Attributes
static float const fontHeight { 24 }
static float fontWidth {}
Static Private Attributes
static Font font_ {}
Detailed Description
Definition at line 6 of file GameFont.h.
Member Function Documentation
font()
static Font const & GameFont::font () inline static
Definition at line 39 of file GameFont.h.
    {
        return font_;
    }
References font_.
Referenced by PanelSystem::drawGameInfoPanelContent(), PanelSystem::drawHeroInfoPanelContent(), PanelSystem::drawLogPanelContent(), PanelSystem::drawTileInfoPanelContent(), and PanelSystem::init().
load()
static void GameFont::load () inline static
Definition at line 16 of file GameFont.h.
    {
        font_ = LoadFontEx(
            "assets/fonts/LiberationMono-Regular.ttf",
            GameFont::fontHeight,
            nullptr,
            0
        );
        fontWidth = static_cast<float>(
            MeasureTextEx(
                font_,
                "1",
                fontHeight,
                0
            )
                .x
        );
    }
References font_, fontHeight, and fontWidth.
Referenced by AppModule::init().
unload()
static void GameFont::unload () inline static
Definition at line 36 of file GameFont.h.
{ UnloadFont(font_); }
References font_.
Referenced by AppModule::deinit().
Member Data Documentation
font_
Font GameFont::font_ {} inline static private
Definition at line 8 of file GameFont.h.
{};
Referenced by font(), load(), and unload().
fontHeight
float const GameFont::fontHeight { 24 } inline static
Definition at line 11 of file GameFont.h.
{ 24 };
Referenced by PanelSystem::drawGameInfoPanelContent(), AppModule::init(), PanelSystem::init(), and load().
fontWidth
float GameFont::fontWidth {} inline static
Definition at line 13 of file GameFont.h.
{};
Referenced by load().
The documentation for this class was generated from the following file:
src/Scene/Data/GameFont.h