Roguelike: SceneModule Namespace Reference
SceneModule Namespace Reference
Functions
void init (Scene &scene)
void update (Scene &scene)
void deinitialize (Scene &scene)
void processInput (Scene &scene)
void updateState (Scene &scene)
void renderOutput (Scene &scene)
void setupSceneEvents (Scene &scene)
void drawSceneBorder ()
Function Documentation
deinitialize()
void SceneModule::deinitialize (Scene & scene)
Definition at line 418 of file Scene.cpp.
{
    RenderSystem::deinit( scene.renderData.textures );
}
References RenderSystem::deinit(), Scene::renderData, and RenderData::textures.
Referenced by AppModule::deinit().
drawSceneBorder()
void SceneModule::drawSceneBorder ()
Definition at line 423 of file Scene.cpp.
{
    DrawRectangleLinesEx(
        GetWindowRec(),
        SceneData::borderWidth,
        Colors::border
    );
}
References Colors::border, SceneData::borderWidth, and GetWindowRec().
Referenced by update().
init()
void SceneModule::init (Scene & scene)
Definition at line 33 of file Scene.cpp.
{
    GameModule::init( scene.game );
    PanelSystem::init( scene.panels );
    GameCameraModule::init(
        scene.gameCamera,
        scene.panels.map,
        scene.game.hero.position
    );
#if defined(DEBUG)
    snx::debug::gcam() = scene.gameCamera;
#endif
    RenderSystem::loadRenderData( scene.renderData );
    ChunkSystem::init(
        scene.renderData.textures,
        scene.chunks,
        scene.game.world.currentMap->tiles.positions,
        scene.game.world.currentMap->tiles.renderIds
    );
    //* Setup events
    SceneModule::setupSceneEvents( scene );
}
References Scene::chunks, World::currentMap, Scene::game, Scene::gameCamera, snx::debug::gcam(), Game::hero, ChunkSystem::init(), GameCameraModule::init(), GameModule::init(), PanelSystem::init(), RenderSystem::loadRenderData(), Panels::map, Scene::panels, Hero::position, Tiles::positions, Scene::renderData, Tiles::renderIds, setupSceneEvents(), RenderData::textures, Map::tiles, and Game::world.
Referenced by AppModule::init().
processInput()
void SceneModule::processInput (Scene & scene)
Definition at line 253 of file Scene.cpp.
{
    //* Color theme
    if ( IsKeyPressed( KEY_F2 ) )
    {
        snx::PublisherStatic::publish( EventId::COLOR_THEME_CHANGE );
    }
    //* Allow input if hero is ready (= full energy)
    if ( scene.game.hero.energy.state == EnergyState::READY )
    {
        GameModule::processInput(
            scene.game.inputMappings,
            scene.cursor.isActive,
            scene.game.inputHandler,
            scene.game.inputAction
        );
    }
}
References COLOR_THEME_CHANGE, Scene::cursor, Hero::energy, Scene::game, Game::hero, Game::inputAction, Game::inputHandler, Game::inputMappings, Cursor::isActive, GameModule::processInput(), snx::PublisherStatic::publish(), READY, and EnergyComponent::state.
Referenced by update().
renderOutput()
void SceneModule::renderOutput (Scene & scene)
Definition at line 292 of file Scene.cpp.
{
    //* Draw map panel content
    BeginMode2D( scene.gameCamera.camera );
    BeginScissorMode(
        scene.gameCamera.viewport->left(),
        scene.gameCamera.viewport->top(),
        scene.gameCamera.viewport->width(),
        scene.gameCamera.viewport->height()
    );
    //* World
    //* Draw map
    //* Draw tiles
    for ( Chunk const& chunk : scene.chunks )
    {
        RenderSystem::renderChunk( chunk );
    }
    //* Draw objects
    auto const& objects{ scene.game.world.currentMap->objects };
    auto const& objectRenderIds{ objects.renderIds.values() };
    auto const& objectPositions{ objects.positions.values() };
    for ( size_t idx{ 0 }; idx < objectRenderIds.size(); ++idx )
    {
        RenderSystem::renderTile(
            scene.renderData.textures,
            objectRenderIds.at( idx ),
            objectPositions.at( idx )
        );
    }
    //* Draw enemies
    auto const& enemies{ scene.game.world.currentMap->enemies };
    auto const& enemyRenderIds{ enemies.renderIds.values() };
    auto const& enemyPositions{ enemies.positions.values() };
    for ( size_t idx{ 0 }; idx < enemyRenderIds.size(); ++idx )
    {
        if ( scene.game.world.currentMap->tiles.visibilityIds.at( Convert::worldToTile( enemyPositions.at( idx ) ) ) != VisibilityId::VISIBILE )
        {
            continue;
        }
        RenderSystem::renderTile(
            scene.renderData.textures,
            enemyRenderIds.at( idx ),
            enemyPositions.at( idx )
        );
    }
    //* VisibilitySystem
    for ( size_t idx{ 0 }; idx < scene.fogs.size(); ++idx )
    {
        RenderSystem::renderFog(
            Convert::tileToWorld( scene.fogs.key( idx ) ),
            scene.fogs.values().at( idx )
        );
    }
    //* Units
    //* Draw hero
    RenderSystem::renderTile(
        scene.renderData.textures,
        scene.game.hero.renderId,
        scene.game.hero.position
    );
    //* UI
    //* Draw cursor
    if ( scene.cursor.isActive )
    {
        RenderSystem::renderTile(
            scene.renderData.textures,
            scene.cursor.renderId,
            scene.cursor.position
        );
    }
    EndScissorMode();
    EndMode2D();
    PanelSystem::drawLogPanelContent( scene.panels );
    PanelSystem::drawHeroInfoPanelContent(
        scene.panels,
        scene.game.hero
    );
    PanelSystem::drawTileInfoPanelContent(
        scene.panels,
        scene.game.world.currentMap->objects,
        Convert::worldToTile( scene.cursor.position )
    );
    PanelSystem::drawGameInfoPanelContent(
        scene.panels,
        scene.game.world.currentMapLevel
    );
    PanelSystem::drawPanelBorders( scene.panels );
}
References snx::DenseMap< Key, Type >::at(), GameCamera::camera, Scene::chunks, World::currentMap, World::currentMapLevel, Scene::cursor, PanelSystem::drawGameInfoPanelContent(), PanelSystem::drawHeroInfoPanelContent(), PanelSystem::drawLogPanelContent(), PanelSystem::drawPanelBorders(), PanelSystem::drawTileInfoPanelContent(), Map::enemies, Scene::fogs, Scene::game, Scene::gameCamera, RectangleEx::height(), Game::hero, Cursor::isActive, snx::DenseMap< Key, Type >::key(), RectangleEx::left(), Map::objects, Scene::panels, Cursor::position, Hero::position, RenderSystem::renderChunk(), Scene::renderData, RenderSystem::renderFog(), Cursor::renderId, Hero::renderId, RenderSystem::renderTile(), snx::DenseMap< Key, Type >::size(), RenderData::textures, Map::tiles, Convert::tileToWorld(), RectangleEx::top(), snx::DenseMap< Key, Type >::values(), GameCamera::viewport, VISIBILE, Tiles::visibilityIds, RectangleEx::width(), Game::world, and Convert::worldToTile().
Referenced by update().
setupSceneEvents()
void SceneModule::setupSceneEvents (Scene & scene)
Definition at line 62 of file Scene.cpp.
{
    snx::PublisherStatic::addSubscriber(
        EventId::WINDOW_RESIZED,
        [&]()
        {
            PanelSystem::init( scene.panels );
        },
        true
    );
    snx::PublisherStatic::addSubscriber(
        EventId::PANELS_RESIZED,
        [&]()
        {
            GameCameraModule::init(
                scene.gameCamera,
                scene.panels.map,
                scene.game.hero.position
            );
            VisibilitySystem::update(
                scene.fogs,
                scene.game.world.currentMap->tiles.visibilityIds,
                scene.game.world.currentMap->tiles.isOpaques,
                GameCameraModule::viewportInTiles( scene.gameCamera ),
                scene.game.hero.visionRange,
                Convert::worldToTile( scene.game.hero.position )
            );
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::HERO_MOVED,
        [&]()
        {
            GameCameraModule::setTarget(
                scene.gameCamera,
                scene.game.hero.position
            );
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::HERO_POSITION_CHANGED,
        [&]()
        {
            //* VisibilitySystem
            VisibilitySystem::update(
                scene.fogs,
                scene.game.world.currentMap->tiles.visibilityIds,
                scene.game.world.currentMap->tiles.isOpaques,
                GameCameraModule::viewportInTiles( scene.gameCamera ),
                scene.game.hero.visionRange,
                Convert::worldToTile( scene.game.hero.position )
            );
        },
        true
    );
    snx::PublisherStatic::addSubscriber(
        EventId::MAP_CHANGE,
        [&]()
        {
            ChunkSystem::init(
                scene.renderData.textures,
                scene.chunks,
                scene.game.world.currentMap->tiles.positions,
                scene.game.world.currentMap->tiles.renderIds
            );
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::COLOR_THEME_CHANGE,
        [&]()
        {
            RenderSystem::cycleThemes( scene.renderData.theme );
            RenderSystem::loadRenderData( scene.renderData );
            snx::PublisherStatic::publish( EventId::MAP_CHANGE );
        }
    );
    snx::PublisherStatic::addSubscriber(
        EventId::CURSOR_TOGGLE,
        [&]()
        {
            CursorModule::toggle( scene.cursor );
        }
    );
#if defined(DEBUG) && defined(DEBUG_TILEINFO)
    snx::PublisherStatic::addSubscriber(
        EventId::CURSOR_POSITION_CHANGED,
        [&]()
        {
            Vector2I cursorPos{ Convert::worldToTile( scene.cursor.position ) };
            if ( !scene.game.world.currentMap->tiles.positions.contains( cursorPos ) )
            {
                return;
            }
            snx::debug::cliPrint( "\n" );
            snx::debug::cliLog( "TILE:\n" );
            snx::debug::cliLog(
                "TilePosition: "
                + std::to_string( cursorPos.x )
                + ", "
                + std::to_string( cursorPos.y )
                + "\n"
            );
            snx::debug::cliLog(
                "WorldPixel: "
                + std::to_string( scene.game.world.currentMap->tiles.positions.at( cursorPos ).x )
                + ", "
                + std::to_string( scene.game.world.currentMap->tiles.positions.at( cursorPos ).y )
                + "\n"
            );
            snx::debug::cliLog(
                "RenderId: "
                + std::to_string( static_cast<int>( scene.game.world.currentMap->tiles.renderIds.at( cursorPos ) ) )
                + "\n"
            );
            snx::debug::cliLog(
                "VisibilityId: "
                + std::to_string( static_cast<int>( scene.game.world.currentMap->tiles.visibilityIds.at( cursorPos ) ) )
                + "\n"
            );
            snx::debug::cliLog(
                "IsSolid: "
                + std::to_string( scene.game.world.currentMap->tiles.isSolids.contains( cursorPos ) )
                + "\n"
            );
            snx::debug::cliLog(
                "IsOpaque: "
                + std::to_string( scene.game.world.currentMap->tiles.isOpaques.contains( cursorPos ) )
                + "\n"
            );
            if ( scene.game.world.currentMap->objects.positions.contains( cursorPos ) )
            {
                snx::debug::cliLog( "OBJECT\n" );
                snx::debug::cliLog(
                    "\nName: "
                    + scene.game.world.currentMap->objects.names.at( cursorPos )
                    + "\n"
                );
                snx::debug::cliLog(
                    "\nActions: "
                    + scene.game.world.currentMap->objects.actions.at( cursorPos )
                    + "\n"
                );
                snx::debug::cliLog(
                    "RenderId: "
                    + std::to_string( static_cast<int>( scene.game.world.currentMap->objects.renderIds.at( cursorPos ) ) )
                    + "\n"
                );
                snx::debug::cliLog(
                    "Event: "
                    + std::to_string( static_cast<int>( scene.game.world.currentMap->objects.events.at( cursorPos ) ) )
                    + "\n"
                );
            }
            if ( scene.game.world.currentMap->enemies.ids.contains( cursorPos ) )
            {
                snx::debug::cliLog( "ENEMY\n" );
                snx::debug::cliLog(
                    "Id: "
                    + std::to_string( scene.game.world.currentMap->enemies.ids.at( cursorPos ) )
                    + "\n"
                );
            }
        }
    );
#endif
}
References Objects::actions, snx::PublisherStatic::addSubscriber(), snx::DenseMap< Key, Type >::at(), Scene::chunks, snx::debug::cliLog(), snx::debug::cliPrint(), COLOR_THEME_CHANGE, snx::DenseMap< Key, Type >::contains(), World::currentMap, Scene::cursor, CURSOR_POSITION_CHANGED, CURSOR_TOGGLE, RenderSystem::cycleThemes(), Map::enemies, Objects::events, Scene::fogs, Scene::game, Scene::gameCamera, Game::hero, HERO_MOVED, HERO_POSITION_CHANGED, Enemies::ids, ChunkSystem::init(), GameCameraModule::init(), PanelSystem::init(), Tiles::isOpaques, Tiles::isSolids, RenderSystem::loadRenderData(), Panels::map, MAP_CHANGE, Objects::names, Map::objects, Scene::panels, PANELS_RESIZED, Cursor::position, Hero::position, Objects::positions, Tiles::positions, snx::PublisherStatic::publish(), Scene::renderData, Objects::renderIds, Tiles::renderIds, GameCameraModule::setTarget(), RenderData::textures, RenderData::theme, Map::tiles, CursorModule::toggle(), VisibilitySystem::update(), GameCameraModule::viewportInTiles(), Tiles::visibilityIds, Hero::visionRange, WINDOW_RESIZED, Game::world, and Convert::worldToTile().
Referenced by init().
update()
void SceneModule::update (Scene & scene)
Definition at line 396 of file Scene.cpp.
{
    processInput( scene );
    updateState( scene );
    BeginDrawing();
    ClearBackground( Colors::bg );
    renderOutput( scene );
    //* Draw simple frame
    drawSceneBorder();
    if ( DeveloperMode::isActive() )
    {
        DrawFPS( 0, 0 );
    }
    EndDrawing();
}
References Colors::bg, drawSceneBorder(), DeveloperMode::isActive(), processInput(), renderOutput(), and updateState().
Referenced by emscriptenLoop(), and AppModule::update().
updateState()
void SceneModule::updateState (Scene & scene)
Definition at line 273 of file Scene.cpp.
{
    CursorModule::update(
        scene.cursor,
        scene.gameCamera.camera,
        Convert::worldToTile( scene.game.hero.position )
    );
    GameModule::updateState(
        scene.game,
        scene.gameCamera,
        scene.cursor
    );
#if defined(DEBUG)
    snx::debug::gcam() = scene.gameCamera;
#endif
}
References GameCamera::camera, Scene::cursor, Scene::game, Scene::gameCamera, snx::debug::gcam(), Game::hero, Hero::position, CursorModule::update(), GameModule::updateState(), and Convert::worldToTile().
Referenced by update().