Roguelike: src/Game/Classes/Tiles.cpp File Reference
Tiles.cpp File Reference
#include "Tiles.h"
#include "Convert.h"
#include "DenseMap.h"
#include "RenderId.h"
#include "VisibilityId.h"
#include "raylibEx.h"
#include <algorithm>
#include <unordered_set>
Namespaces
namespace TilesModule
Functions
void updateMapSize (Tiles &tiles, Vector2I const &tilePosition)
void TilesModule::createSingle (Tiles &tiles, Vector2I const &tilePosition, RenderId renderId, bool isSolid, bool isOpaque, VisibilityId visibilityId)
Function Documentation
updateMapSize()
void updateMapSize (Tiles & tiles, Vector2I const & tilePosition)
Definition at line 10 of file Tiles.cpp.
{
    tiles.mapSize = RectangleExI{
        Vector2I{
            std::min( tilePosition.x, tiles.mapSize.left() ),
            std::min( tilePosition.y, tiles.mapSize.top() )
        },
        Vector2I{
            std::max( tilePosition.x, tiles.mapSize.right() ),
            std::max( tilePosition.y, tiles.mapSize.bottom() )
        }
    };
}
References RectangleExI::bottom(), RectangleExI::left(), Tiles::mapSize, RectangleExI::right(), RectangleExI::top(), Vector2I::x, and Vector2I::y.
Referenced by TilesModule::createSingle().