Roguelike: PathfinderSystem Namespace Reference
PathfinderSystem Namespace Reference
Functions
std::vector< Vector2I > findPath (Map const &map, Vector2I const &start, Vector2I const &target, GameCamera const &gameCamera, bool skipInvisibleTiles=true, int maxRange=0)
Function Documentation
findPath()
std::vector< Vector2I > PathfinderSystem::findPath (Map const & map, Vector2I const & start, Vector2I const & target, GameCamera const & gameCamera, bool skipInvisibleTiles = true, int maxRange = 0)
Definition at line 283 of file PathfinderSystem.cpp.
{
#if defined(DEBUG) && defined(DEBUG_PATHFINDER)
    BeginDrawing();
#endif
    std::vector<Vector2I> path{};
    //* Return empty path if target is
    //* - Not in map
    //* - Is invisible
    //* - Not accessible
    //* - Equal to start
    if ( !map.tiles.visibilityIds.contains( target )
         || ( skipInvisibleTiles
              && ( map.tiles.visibilityIds.at( target ) == VisibilityId::INVISIBLE ) )
         || map.tiles.isSolids.contains( target )
         || ( start == target ) )
    {
        return path;
    }
    //* Create tile to start
    RatedTile firstTile{
        start,
        target,
        0,
        nullptr
    };
    //* Vector of rated tiles (persistent for ancestor pointers)
    std::forward_list<RatedTile> ratedTiles{ firstTile };
    //* Map of tile pointers, sorted by rating (lowest first)
    std::map<int, std::vector<RatedTile*>> ratingList{};
    ratingList[RatedTileModule::getRating( firstTile )].push_back( &ratedTiles.front() );
    //* List of ignored tiles to avoid double checks
    std::unordered_set<Vector2I> tilesToIgnore{ start };
    checkRatingList(
        RatedTileModule::getRating( firstTile ),
        ratedTiles,
        ratingList,
        tilesToIgnore,
        map,
        target,
        gameCamera,
        maxRange,
        path
    );
    //* Path is either empty or has at least 2 entries (target and start)
#if defined(DEBUG) && defined(DEBUG_PATHFINDER)
    for ( Vector2I const& position : path )
    {
        DrawCircleV(
            Vector2Add(
                Convert::tileToScreen(
                    position,
                    snx::debug::gcam().camera()
                ),
                Vector2{ TileData::TILE_SIZE_HALF, TileData::TILE_SIZE_HALF }
            ),
            5,
            ColorAlpha(
                GREEN,
                0.5
            )
        );
    }
    EndDrawing();
#endif
    return path;
}
References snx::DenseMap< Key, Type >::at(), checkRatingList(), snx::DenseMap< Key, Type >::contains(), snx::debug::gcam(), RatedTileModule::getRating(), INVISIBLE, Tiles::isSolids, Map::tiles, Convert::tileToScreen(), Vector2Add(), and Tiles::visibilityIds.
Referenced by AISystem::takeAction(), and UserInputSystem::takeAction().