Roguelike: snx::Logger Class Reference
snx::Logger Class Reference
#include <Logger.h>
Static Public Member Functions
static void log (std::string const &message)
static void logAppend (std::string const &message)
static std::string const & getMessage (int number)
static void setStamp (std::string const &stamp)
Static Private Attributes
static std::string stamp_ {}
static std::deque< std::string > history_ { 100, "" }
Detailed Description
Definition at line 11 of file Logger.h.
Member Function Documentation
getMessage()
static std::string const & snx::Logger::getMessage (int number) inline static
Definition at line 33 of file Logger.h.
        {
            return history_.at( number );
        }
References history_.
Referenced by PanelSystem::drawLogPanelContent().
log()
static void snx::Logger::log (std::string const & message) inline static
Definition at line 18 of file Logger.h.
        {
            history_.push_front( "[" + stamp_ + "] " + message );
            if ( history_.size() > historySizeMax )
            {
                history_.pop_back();
            }
        }
References history_, historySizeMax, and stamp_.
Referenced by InputModule::checkGesture(), performAttack(), GameModule::setupGameEvents(), AISystem::takeAction(), and UserInputSystem::takeAction().
logAppend()
static void snx::Logger::logAppend (std::string const & message) inline static
Definition at line 28 of file Logger.h.
        {
            history_.front() += message;
        }
References history_.
Referenced by DamageModule::damageRNG().
setStamp()
static void snx::Logger::setStamp (std::string const & stamp) inline static
Definition at line 38 of file Logger.h.
        {
            stamp_ = stamp;
        }
References stamp_.
Referenced by GameModule::updateState().
Member Data Documentation
history_
std::deque<std::string> snx::Logger::history_ { 100, "" } inline static private
Definition at line 15 of file Logger.h.
{ 100, "" };
Referenced by getMessage(), log(), and logAppend().
stamp_
std::string snx::Logger::stamp_ {} inline static private
Definition at line 13 of file Logger.h.
{};
Referenced by log(), and setStamp().
The documentation for this class was generated from the following file:
include/Logger.h