Roguelike: src/Game/Classes/World.cpp File Reference
World.cpp File Reference
#include "World.h"
#include "MapGeneratorSystem.h"
Namespaces
namespace WorldModule
Functions
void addNewMap (World &world)
void setCurrentMap (World &world, int level)
void WorldModule::increaseMapLevel (World &world)
void WorldModule::decreaseMapLevel (World &world)
Function Documentation
addNewMap()
void addNewMap (World & world)
Definition at line 5 of file World.cpp.
{
    world.maps.push_back( MapGeneratorSystem::createRandomMap( world.maxMapLevel + 1 ) );
}
References MapGeneratorSystem::createRandomMap(), World::maps, and World::maxMapLevel.
Referenced by WorldModule::increaseMapLevel().
setCurrentMap()
void setCurrentMap (World & world, int level)
Definition at line 10 of file World.cpp.
{
    world.currentMap = &world.maps[level];
}
References World::currentMap, and World::maps.
Referenced by WorldModule::decreaseMapLevel(), and WorldModule::increaseMapLevel().