Roguelike: include/raylibEx.h File Reference
raylibEx.h File Reference
#include <cassert>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <functional>
#include <iostream>
#include <raylib.h>
#include <raymath.h>
#include <utility>
Classes
class RectangleEx
struct Vector2I
class RectangleExI
struct Matrix2x2
struct Matrix2x2I
struct std::hash< Vector2 >
struct std::hash< Vector2I >
Functions
RMAPI Vector2I Vector2Add (Vector2I const &v1, Vector2I const &v2)
RMAPI Vector2I Vector2AddValue (Vector2I const &v1, int value)
RMAPI Vector2I Vector2Subtract (Vector2I const &v1, Vector2I const &v2)
RMAPI Vector2I Vector2SubtractValue (Vector2I const &v1, int value)
RMAPI Vector2 Vector2Scale (Vector2I const &v, float scale)
RMAPI Vector2I Vector2Scale (Vector2I const &v, int scale)
RMAPI bool Vector2Equals (Vector2I const &v1, Vector2I const &v2)
RMAPI Vector2 Vector2Round (Vector2 v)
RMAPI Vector2I Vector2TransMove (Matrix2x2I const &M, Vector2I const &v)
RMAPI Vector2 Vector2TransMove (Matrix2x2 const &M, Vector2 const &v)
RMAPI Vector2I Vector2Negate (Vector2I const &v)
RMAPI int Vector2Distance (Vector2I const &start, Vector2I const &target)
RMAPI Vector2I Vector2Normalize (Vector2I const &v)
RMAPI int Vector2Length (Vector2I const &v)
bool CheckCollisionPointRec (Vector2I const &point, RectangleExI const &rec)
bool CheckCollisionPointRec (Vector2 const &point, RectangleEx const &rec)
int GetOrientation (Vector2 const &p1, Vector2 const &p2, Vector2 const &p3)
bool CheckCollisionLines (Vector2 const &a1, Vector2 const &b1, Vector2 const &c2, Vector2 const &d2)
bool CheckCollisionLineRec (Vector2 const &a1, Vector2 const &b1, RectangleEx const &rectangle)
Vector2 GetDisplaySize ()
int Vector2Sum (Vector2I const &v)
Vector2 Vector2MainDirection (Vector2 v)
Vector2I Vector2MainDirection (Vector2I v)
Vector2 Vector2MainDirection (Vector2 const &from, Vector2 const &to)
Vector2I Vector2MainDirection (Vector2I const &from, Vector2I const &to)
Vector2 Vector2OffDirection (Vector2 v)
Vector2I Vector2OffDirection (Vector2I v)
Vector2 Vector2OffDirection (Vector2 const &from, Vector2 const &to)
Vector2I Vector2OffDirection (Vector2I const &from, Vector2I const &to)
Vector2I Vector2Swap (Vector2I v)
Rectangle GetWindowRec ()
Vector2 ConvertToVector2 (Vector2I const &v)
Vector2I ConvertToVector2I (Vector2 const &v)
Vector2I GetMin (Vector2I const &v1, Vector2I const &v2)
Vector2I GetMax (Vector2I const &v1, Vector2I const &v2)
Vector2I & operator+= (Vector2I &lhs, Vector2I const &rhs)
Vector2I & operator-= (Vector2I &lhs, Vector2I const &rhs)
bool operator== (Vector2I const &lhs, Vector2I const &rhs)
std::ostream & operator<< (std::ostream &os, Vector2 const &v)
std::ostream & operator<< (std::ostream &os, Vector2I const &v)
Variables
int constexpr prime { 2946901 }
Function Documentation
CheckCollisionLineRec()
bool CheckCollisionLineRec (Vector2 const & a1, Vector2 const & b1, RectangleEx const & rectangle) inline
Definition at line 738 of file raylibEx.h.
{
    //* Check collsion of line with Rectangle diagonals
    if ( CheckCollisionLines(
             a1,
             b1,
             rectangle.topLeft(),
             rectangle.bottomRight()
         )
         || CheckCollisionLines(
             a1,
             b1,
             Vector2(
                 {
                     rectangle.left(),
                     rectangle.bottom()
                 }
             ),
             Vector2(
                 { rectangle.right(),
                   rectangle.top() }
             )
         ) )
    {
        return true;
    }
    return false;
}
References RectangleEx::bottom(), RectangleEx::bottomRight(), CheckCollisionLines(), RectangleEx::left(), RectangleEx::right(), RectangleEx::top(), and RectangleEx::topLeft().
CheckCollisionLines()
bool CheckCollisionLines (Vector2 const & a1, Vector2 const & b1, Vector2 const & c2, Vector2 const & d2) inline
Definition at line 702 of file raylibEx.h.
{
    //* https://www.geeksforgeeks.org/check-if-two-given-line-segments-intersect/
    //* REQUIREMENT:
    //*  - Orientation of a1-b1-c2 and a1-b1-d2 differs
    //*  AND
    //*  - Orientation of c2-d2-a1 and c2-d2-b1 differs
    //* CONCLUSION: No collision if
    //*  - one orientation is colinear (0) := touch but no intersection
    //*  OR
    //*  - one orientation pair is equal
    int abc{ GetOrientation( a1, b1, c2 ) };
    int abd{ GetOrientation( a1, b1, d2 ) };
    int cda{ GetOrientation( c2, d2, a1 ) };
    int cdb{ GetOrientation( c2, d2, b1 ) };
    if ( //* Colinear orientations
        !( abc * abd * cda * cdb )
        //* No intersection
        || ( abc == abd )
        || ( cda == cdb )
    )
    {
        return false;
    }
    return true;
}
References GetOrientation().
Referenced by CheckCollisionLineRec().
CheckCollisionPointRec() [1/2]
bool CheckCollisionPointRec (Vector2 const & point, RectangleEx const & rec) inline
Definition at line 679 of file raylibEx.h.
{
    return CheckCollisionPointRec(
        point,
        rec.rectangle()
    );
}
References CheckCollisionPointRec(), and RectangleEx::rectangle().
CheckCollisionPointRec() [2/2]
bool CheckCollisionPointRec (Vector2I const & point, RectangleExI const & rec) inline
Definition at line 666 of file raylibEx.h.
{
    return (
        ( point.x >= rec.left() )
        && ( point.x <= rec.right() )
        && ( point.y >= rec.top() )
        && ( point.y <= rec.bottom() )
    );
}
References RectangleExI::bottom(), RectangleExI::left(), RectangleExI::right(), RectangleExI::top(), Vector2I::x, and Vector2I::y.
Referenced by CheckCollisionPointRec(), and checkRatingList().
ConvertToVector2()
Vector2 ConvertToVector2 (Vector2I const & v) inline
Definition at line 887 of file raylibEx.h.
{
    return Vector2{
        static_cast<float>( v.x ),
        static_cast<float>( v.y )
    };
}
References Vector2I::x, and Vector2I::y.
ConvertToVector2I()
Vector2I ConvertToVector2I (Vector2 const & v) inline
Definition at line 895 of file raylibEx.h.
{
    return Vector2I{
        static_cast<int>( v.x ),
        static_cast<int>( v.y )
    };
}
GetDisplaySize()
Vector2 GetDisplaySize () inline
Definition at line 776 of file raylibEx.h.
{
    if ( IsWindowFullscreen() )
    {
        return Vector2{ static_cast<float>( GetMonitorWidth( GetCurrentMonitor() ) ), static_cast<float>( GetMonitorHeight( GetCurrentMonitor() ) ) };
    }
    else
    {
        return Vector2{ static_cast<float>( GetRenderWidth() ), static_cast<float>( GetRenderHeight() ) };
    }
}
GetMax()
Vector2I GetMax (Vector2I const & v1, Vector2I const & v2) inline
Definition at line 914 of file raylibEx.h.
{
    return Vector2I{
        ( v1.x > v2.x ? v1.x : v2.x ),
        ( v1.y > v2.y ? v1.y : v2.y )
    };
}
References Vector2I::x, and Vector2I::y.
GetMin()
Vector2I GetMin (Vector2I const & v1, Vector2I const & v2) inline
Definition at line 903 of file raylibEx.h.
{
    return Vector2I{
        ( v1.x < v2.x ? v1.x : v2.x ),
        ( v1.y < v2.y ? v1.y : v2.y )
    };
}
References Vector2I::x, and Vector2I::y.
GetOrientation()
int GetOrientation (Vector2 const & p1, Vector2 const & p2, Vector2 const & p3) inline
Definition at line 691 of file raylibEx.h.
{
    //* https://www.geeksforgeeks.org/orientation-3-ordered-points/
    float n{ ( p2.y - p1.y ) * ( p3.x - p2.x ) - ( p2.x - p1.x ) * ( p3.y - p2.y ) };
    return n / abs( n );
}
Referenced by CheckCollisionLines().
GetWindowRec()
Rectangle GetWindowRec () inline
Definition at line 877 of file raylibEx.h.
{
    return Rectangle{
        0,
        0,
        static_cast<float>( GetRenderWidth() ),
        static_cast<float>( GetRenderHeight() )
    };
}
Referenced by SceneModule::drawSceneBorder(), and snx::IScene::drawWindowBorder().
operator+=()
Vector2I & operator+= (Vector2I & lhs, Vector2I const & rhs) inline
Definition at line 926 of file raylibEx.h.
{
    lhs.x += rhs.x;
    lhs.y += rhs.y;
    return lhs;
}
References Vector2I::x, and Vector2I::y.
operator-=()
Vector2I & operator-= (Vector2I & lhs, Vector2I const & rhs) inline
Definition at line 933 of file raylibEx.h.
{
    lhs.x -= rhs.x;
    lhs.y -= rhs.y;
    return lhs;
}
References Vector2I::x, and Vector2I::y.
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, Vector2 const & v) inline
Definition at line 970 of file raylibEx.h.
{
    return os
           << "("
           << v.x
           << ", "
           << v.y
           << ")";
}
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, Vector2I const & v) inline
Definition at line 980 of file raylibEx.h.
{
    return os
           << "("
           << v.x
           << ", "
           << v.y
           << ")";
}
References Vector2I::x, and Vector2I::y.
operator==()
bool operator== (Vector2I const & lhs, Vector2I const & rhs) inline
Definition at line 940 of file raylibEx.h.
{
    return ( ( lhs.x == rhs.x ) && ( lhs.y == rhs.y ) );
}
References Vector2I::x, and Vector2I::y.
Vector2Add()
RMAPI Vector2I Vector2Add (Vector2I const & v1, Vector2I const & v2)
Definition at line 564 of file raylibEx.h.
{
    return Vector2I{
        v1.x + v2.x,
        v1.y + v2.y
    };
}
References Vector2I::x, and Vector2I::y.
Referenced by checkCollisionWithNextPosition(), checkRatingList(), PathfinderSystem::findPath(), Convert::octantToTile(), Convert::octantToWorld(), and processDirectionalInput().
Vector2AddValue()
RMAPI Vector2I Vector2AddValue (Vector2I const & v1, int value)
Definition at line 572 of file raylibEx.h.
{
    return Vector2I{
        v1.x + value,
        v1.y + value
    };
}
References Vector2I::x, and Vector2I::y.
Vector2Distance()
RMAPI int Vector2Distance (Vector2I const & start, Vector2I const & target)
Definition at line 648 of file raylibEx.h.
{
    return ( abs( target.x - start.x ) + abs( target.y - start.y ) );
}
References Vector2I::x, and Vector2I::y.
Vector2Equals()
RMAPI bool Vector2Equals (Vector2I const & v1, Vector2I const & v2)
Definition at line 615 of file raylibEx.h.
{
    return ( ( v1.x == v2.x ) && ( v1.y == v2.y ) );
}
References Vector2I::x, and Vector2I::y.
Referenced by CollisionSystem::checkCollision(), and checkCollisionWithNextPosition().
Vector2Length()
RMAPI int Vector2Length (Vector2I const & v)
Definition at line 661 of file raylibEx.h.
{
    return ( abs( v.x ) + abs( v.y ) );
}
References Vector2I::x, and Vector2I::y.
Referenced by RatedTileModule::getRating(), AISystem::takeAction(), and MovementSystem::updateHero().
Vector2MainDirection() [1/4]
Vector2 Vector2MainDirection (Vector2 const & from, Vector2 const & to) inline
Definition at line 812 of file raylibEx.h.
{
    return Vector2MainDirection(
        Vector2Subtract(
            to,
            from
        )
    );
}
References Vector2MainDirection(), and Vector2Subtract().
Vector2MainDirection() [2/4]
Vector2 Vector2MainDirection (Vector2 v) inline
Definition at line 794 of file raylibEx.h.
{
    ( abs( v.x ) > abs( v.y ) )
        ? ( v.y = 0 )
        : ( v.x = 0 );
    return Vector2Normalize( v );
}
References Vector2Normalize().
Referenced by InputModule::checkGesture(), checkRatingList(), Vector2MainDirection(), and Vector2MainDirection().
Vector2MainDirection() [3/4]
Vector2I Vector2MainDirection (Vector2I const & from, Vector2I const & to) inline
Definition at line 822 of file raylibEx.h.
{
    return Vector2MainDirection(
        Vector2Subtract(
            to,
            from
        )
    );
}
References Vector2MainDirection(), and Vector2Subtract().
Vector2MainDirection() [4/4]
Vector2I Vector2MainDirection (Vector2I v) inline
Definition at line 803 of file raylibEx.h.
{
    ( abs( v.x ) > abs( v.y ) )
        ? ( v.y = 0 )
        : ( v.x = 0 );
    return Vector2Normalize( v );
}
References Vector2Normalize(), Vector2I::x, and Vector2I::y.
Vector2Negate()
RMAPI Vector2I Vector2Negate (Vector2I const & v)
Definition at line 643 of file raylibEx.h.
{
    return Vector2I{ -v.x, -v.y };
}
References Vector2I::x, and Vector2I::y.
Referenced by checkRatingList().
Vector2Normalize()
RMAPI Vector2I Vector2Normalize (Vector2I const & v)
Definition at line 653 of file raylibEx.h.
{
    return Vector2I{
        ( ( v.x ) ? v.x / abs( v.x ) : v.x ),
        ( ( v.y ) ? v.y / abs( v.y ) : v.y )
    };
}
References Vector2I::x, and Vector2I::y.
Referenced by checkRatingList(), Vector2MainDirection(), Vector2MainDirection(), Vector2OffDirection(), and Vector2OffDirection().
Vector2OffDirection() [1/4]
Vector2 Vector2OffDirection (Vector2 const & from, Vector2 const & to) inline
Definition at line 850 of file raylibEx.h.
{
    return Vector2OffDirection(
        Vector2Subtract(
            to,
            from
        )
    );
}
References Vector2OffDirection(), and Vector2Subtract().
Vector2OffDirection() [2/4]
Vector2 Vector2OffDirection (Vector2 v) inline
Definition at line 832 of file raylibEx.h.
{
    ( abs( v.x ) < abs( v.y ) )
        ? ( v.y = 0 )
        : ( v.x = 0 );
    return Vector2Normalize( v );
}
References Vector2Normalize().
Referenced by checkRatingList(), Vector2OffDirection(), and Vector2OffDirection().
Vector2OffDirection() [3/4]
Vector2I Vector2OffDirection (Vector2I const & from, Vector2I const & to) inline
Definition at line 860 of file raylibEx.h.
{
    return Vector2OffDirection(
        Vector2Subtract(
            to,
            from
        )
    );
}
References Vector2OffDirection(), and Vector2Subtract().
Vector2OffDirection() [4/4]
Vector2I Vector2OffDirection (Vector2I v) inline
Definition at line 841 of file raylibEx.h.
{
    ( abs( v.x ) < abs( v.y ) )
        ? ( v.y = 0 )
        : ( v.x = 0 );
    return Vector2Normalize( v );
}
References Vector2Normalize(), Vector2I::x, and Vector2I::y.
Vector2Round()
RMAPI Vector2 Vector2Round (Vector2 v)
Definition at line 620 of file raylibEx.h.
{
    v.x = roundf( v.x );
    v.y = roundf( v.y );
    return v;
}
References Vector2I::x.
Referenced by MovementSystem::updateHero().
Vector2Scale() [1/2]
RMAPI Vector2 Vector2Scale (Vector2I const & v, float scale)
Definition at line 598 of file raylibEx.h.
{
    return Vector2{
        v.x * scale,
        v.y * scale
    };
}
References Vector2I::x, and Vector2I::y.
Referenced by createGridRooms(), and MovementSystem::frameOffset().
Vector2Scale() [2/2]
RMAPI Vector2I Vector2Scale (Vector2I const & v, int scale)
Definition at line 606 of file raylibEx.h.
{
    return Vector2I{
        v.x * scale,
        v.y * scale
    };
}
References Vector2I::x, and Vector2I::y.
Vector2Subtract()
RMAPI Vector2I Vector2Subtract (Vector2I const & v1, Vector2I const & v2)
Definition at line 581 of file raylibEx.h.
{
    return Vector2I{
        v1.x - v2.x,
        v1.y - v2.y
    };
}
References Vector2I::x, and Vector2I::y.
Referenced by MovementSystem::prepareByFromTo(), MovementSystem::prepareFromExistingPath(), RatedTile::RatedTile(), AISystem::takeAction(), Vector2MainDirection(), Vector2MainDirection(), Vector2OffDirection(), and Vector2OffDirection().
Vector2SubtractValue()
RMAPI Vector2I Vector2SubtractValue (Vector2I const & v1, int value)
Definition at line 589 of file raylibEx.h.
{
    return Vector2I{
        v1.x - value,
        v1.y - value
    };
}
References Vector2I::x, and Vector2I::y.
Vector2Sum()
int Vector2Sum (Vector2I const & v) inline
Definition at line 789 of file raylibEx.h.
{
    return abs( v.x ) + abs( v.y );
}
References Vector2I::x, and Vector2I::y.
Referenced by createGridRooms().
Vector2Swap()
Vector2I Vector2Swap (Vector2I v) inline
Definition at line 870 of file raylibEx.h.
{
    std::swap( v.x, v.y );
    return v;
}
References Vector2I::x, and Vector2I::y.
Referenced by checkRatingList().
Vector2TransMove() [1/2]
RMAPI Vector2 Vector2TransMove (Matrix2x2 const & M, Vector2 const & v)
Definition at line 635 of file raylibEx.h.
{
    return Vector2{
        ( ( M.m11 * v.x ) + ( M.m12 * v.y ) ),
        ( ( M.m21 * v.x ) + ( M.m22 * v.y ) )
    };
}
References Matrix2x2::m11, Matrix2x2::m12, Matrix2x2::m21, and Matrix2x2::m22.
Vector2TransMove() [2/2]
RMAPI Vector2I Vector2TransMove (Matrix2x2I const & M, Vector2I const & v)
Definition at line 627 of file raylibEx.h.
{
    return Vector2I{
        ( ( M.m11 * v.x ) + ( M.m12 * v.y ) ),
        ( ( M.m21 * v.x ) + ( M.m22 * v.y ) )
    };
}
References Matrix2x2I::m11, Matrix2x2I::m12, Matrix2x2I::m21, Matrix2x2I::m22, Vector2I::x, and Vector2I::y.
Variable Documentation
prime
int constexpr prime { 2946901 } constexpr
Definition at line 949 of file raylibEx.h.
{ 2946901 };
Referenced by std::hash< Vector2 >::operator()(), and std::hash< Vector2I >::operator()().