Roguelike: RatedTileModule Namespace Reference
RatedTileModule Namespace Reference
Functions
int getRating (RatedTile const &ratedTile)
void reconstructPath (RatedTile const &ratedTile, std::vector< Vector2I > &path)
Function Documentation
getRating()
int RatedTileModule::getRating (RatedTile const & ratedTile)
Definition at line 34 of file PathfinderSystem.cpp.
{
    return
        //* Distance to target
        Vector2Length( ratedTile.distanceToTarget )
        + bias * ratedTile.stepsNeeded;
}
References bias, RatedTile::distanceToTarget, RatedTile::stepsNeeded, and Vector2Length().
Referenced by checkRatingList(), and PathfinderSystem::findPath().
reconstructPath()
void RatedTileModule::reconstructPath (RatedTile const & ratedTile, std::vector< Vector2I > & path)
Definition at line 42 of file PathfinderSystem.cpp.
{
    //* Add this to path
    path.push_back( ratedTile.tilePosition );
    //* Abort (includes root/start)
    if ( !ratedTile.ancestor )
    {
        return;
    }
    //* Add ancestor to path
    reconstructPath(
        *ratedTile.ancestor,
        path
    );
}
References RatedTile::ancestor, reconstructPath(), and RatedTile::tilePosition.
Referenced by checkRatingList(), and reconstructPath().