Roguelike: src/main.cpp File Reference
main.cpp File Reference
Entrypoint.
#include "App.h"
#include "../assets/iconset/iconset.rgi.h"
#include <raygui.h>
Macros
#define RAYGUI_IMPLEMENTATION
#define RAYGUI_CUSTOM_ICONS
Functions
int main ()
Entrypoint.
Detailed Description
Entrypoint.
Definition in file main.cpp.
Macro Definition Documentation
RAYGUI_CUSTOM_ICONS
#define RAYGUI_CUSTOM_ICONS
Definition at line 11 of file main.cpp.
RAYGUI_IMPLEMENTATION
#define RAYGUI_IMPLEMENTATION
Definition at line 9 of file main.cpp.
Function Documentation
main()
int main ()
Entrypoint.
Definition at line 19 of file main.cpp.
{
    App app{};
    AppModule::init(
        app.scene,
        app.config
    );
    AppModule::update( app.scene );
    AppModule::deinit( app.scene );
    return 0;
}
References AppModule::deinit(), AppModule::init(), and AppModule::update().