Roguelike: CollisionSystem Namespace Reference
CollisionSystem Namespace Reference
Functions
bool checkCollision (Tiles const &tiles, Enemies const &enemies, Vector2I const &tilePositionToCheck, Vector2I const &heroPosition)
Function Documentation
checkCollision()
bool CollisionSystem::checkCollision (Tiles const & tiles, Enemies const & enemies, Vector2I const & tilePositionToCheck, Vector2I const & heroPosition)
Definition at line 24 of file CollisionSystem.cpp.
{
    return (
        //* Next tilePosition unit moves to
        enemies.ids.contains( tilePositionToCheck )
        // || map.objects_.getIsSolids().contains(tilePositionToCheck)
        || tiles.isSolids.contains( tilePositionToCheck )
        || Vector2Equals( tilePositionToCheck, heroPosition )
        || checkCollisionWithNextPosition(
            enemies,
            tilePositionToCheck
        )
    );
}
References checkCollisionWithNextPosition(), snx::DenseMap< Key, Type >::contains(), Enemies::ids, Tiles::isSolids, and Vector2Equals().
Referenced by processDirectionalInput(), AISystem::takeAction(), and UserInputSystem::takeAction().